### ISSUE TITLE
Windows 10, Python3.7, Pygame 1.9.5, pygame.display.set_mode fails in Docker

### ISSUE THREAD

**Issue by Kartikei-12** [pygame/pygame#1001]
OS: Windows 10
Python: 3.7
Pygame: 1.9.5
Docker: 18.03.0-ce, build 0520e24302
When running python script that uses pygame, inside docker, pygame.display.set_mode fails even after pygame.init() with error message "pygame.error: No available video device".
Works perfectly good outside docker on host machine, when run directly

**Comment by robertpfeiffer** [comment]
Well, is that Docker environment headless? Is there a way to open windows? I would think this is the intended behaviour. Can you elaborate on your Docker setup?

**Comment by MyreMylar** [comment]
It does seem, from scouring the internet, that other people have got pygame working inside Docker on linux. For example:

https://stackoverflow.com/questions/56668021/run-pygame-with-audio-in-docker-container

But that it didn't work on OSX:

https://opeonikute.dev/posts/running-pygame-in-a-docker-container-macos

Finally this thread from last month suggests that you can't run _any_ graphical applications in Docker on Windows because of how Docker works:

https://www.reddit.com/r/learnpython/comments/fknrrj/pygameerror_no_available_audio_device_when/

I think this is a case where Docker on Windows doesn't do what the OP wants.

Does that explain things @Kartikei-12 ?

**Comment by MyreMylar** [comment]
No response from OP, so closing for now.
