### ISSUE TITLE
Applying scale transformation to the same surface throws error

### ISSUE THREAD

**Issue by andrhua** [pygame/pygame#1017]
`pygame.transform.scale(surface, (width, height), surface)`
ValueError: Destination surface not the given width or height
It might be because tuple parameter packing is not supported in Python 3, which I use.

**Comment by charlesej** [comment]
I think what you are describing is expected behavior.

As per the [pygame.transform.scale documentation](https://www.pygame.org/docs/ref/transform.html#pygame.transform.scale):

> An optional destination surface can be used, rather than have it create a new one. This is quicker if you want to repeatedly scale something. However the destination must be the same size as the (width, height) passed in. Also the destination surface must be the same format.

The destination surface must be the same size as the (width, height) parameter. Trying to reuse the source surface as the destination surface has 2 cases.

```python
import pygame

size = (10, 20)
surface = pygame.Surface(size)

# Case 1: The surface will be written onto itself with no scaling done.
pygame.transform.scale(surface, size, surface)

# Case 2: A ValueError will be raised as the destination surface is not the same size
# as the given (width, height) parameter.
pygame.transform.scale(surface, (size[0] * 2, size[1] * 2), surface)
```

To scale the source surface you need to provide a destination surface that is the same size as the (width, height) parameter. Or alternatively, don't provide a destination surface and let the function create one for you.
