### ISSUE TITLE
Update freetype version to 2.9.1+

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1113]
I noticed that pygame is about 6 versions (and at least 5 years) behind the latest version of freetype. It looks like there have been some potentially nice changes over the last five years that may improve font rendering for pygame - mainly the addition of ClearType hinting.

I suppose there is a chance it might just be an easy copy and paste job :)

**To Do**

- [ ] Test what freetype version reported on linux with `freetype.get_version()`.
- [x] Test what freetype version reported on mac with `freetype.get_version()`.
- [x] Test what freetype version reported on windows dev10 wheel with `freetype.get_version()`.
- [ ] Resolve issue with out of date freetype library used in windows wheels.

**Related Docs:** https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.get_version

**Comment by MyreMylar** [comment]
The current version of freetype reported in 2.0.0.dev2 (SDL 2.0.9, python 3.7.2) is 2.4.12.

I'm not sure what version pygame.font is getting via SDL_ttf but:
https://www.libsdl.org/projects/SDL_ttf/

tells us that there is a version of SDL_ttf (2.0.15) with at least freetype 2.9.1 support which would bew new enough to include the cleartype hinting as well.

**Comment by dlon** [comment]
On Windows pygame uses the binaries on this page, which include FreeType: https://libsdl.org/download-2.0.php. Maybe it would be ideal for it to be updated there instead

**Comment by MyreMylar** [comment]
This has been partially resolved - 

- SDL_ttf has been updated to 2.0.15 - Hooray!
- But the pre-built data used on windows for c header files, .lib files and the like is still out of date and referring to 2.4.12 and this is used to populate the results of `freetype.get_version()`, At least that is the case for the version of pygame I can build on windows.


Simple test for multiple platforms:

    import pygame.freetype
    print(pygame.freetype.get_version())

What version does this report?

On Windows, on 2.0.0.dev7 I get: 

    pygame 2.0.0.dev7 (SDL 2.0.12, python 3.8.2)
    Hello from the pygame community. https://www.pygame.org/contribute.html
    (2, 4, 12)

When according to the version of SDL_ttf we are using it should be:

    pygame 2.0.0.dev7 (SDL 2.0.12, python 3.8.2)
    Hello from the pygame community. https://www.pygame.org/contribute.html
    (2, 9, 1)

See: https://www.libsdl.org/projects/SDL_ttf/

It is possible, even likely, that the situation is correct on linux & mac but it would be good to confirm.

**Comment by MyreMylar** [comment]
- [ ] Test what freetype version reported on linux with `freetype.get_version()`.
- [ ] Test what freetype version reported on mac with `freetype.get_version()`.
- [ ] Test what freetype version reported on windows dev8 wheel with `freetype.get_version()`.

If they are all reporting (2, 9, 1) then we can close this as it is really an issue with the out of date data for self compiling on windows....

- [ ] Raise issue for out of date pre-compiled data for self-compile on windows (may be fixed by conan build?

**Comment by Starbuck5** [comment]
Hopefully this is still helpful

Mac 2.0.0.dev10 -> (2, 10, 1)
Windows 2.0.0.dev10 -> (2, 4, 1)

**Comment by MyreMylar** [comment]
Looks like it is an actual issue with the build on windows then. Boo.

**Comment by MyreMylar** [comment]
Useful github repo for this:
https://github.com/ubawurinna/freetype-windows-binaries

**Comment by Starbuck5** [comment]
This issue is so confusing.

I went into my `site-packages` folder and inspected the installed pygame version. 

The freetype dll in the folder reports its version as 2.9.1
![Capture](https://user-images.githubusercontent.com/46412508/119469667-6e1b5e80-bcfc-11eb-8334-c093026bc9de.PNG)

I also tested pygame 1.9.6, which didn't have a freetype dll (however the _freetype pyd was much bigger)
And on 1.9.6, `freetype.get_version()` reported `(2, 10, 1)`!

Why is it reporting `(2, 4, 1)` when it clearly has a `(2, 9, 1)` DLL?

Also, it might be helpful to note that SDL2_TTF comes with a modern enough freetype version, so we can get that in the prebuilt downloads properly without downloading another freetype DLL in the buildconfig process.

**Theorizing time**
What if pygame.freetype is being built alongside an old freetype version downloaded pygame.org/ftp into the prebuilt-x64/lib folder, but actually exported with a new freetype version found in prebuilt-x64/SDL2_TTF-2.0.15. That could explain my obervsations, if that is something that is even possible.

**Comment by Starbuck5** [comment]
I think my theory is right...

I was able to modify our freetype files to use the `FT_Library_Version` function rather than compile time defines, and I was able to get it to spit out 2.9.1
![Capture2](https://user-images.githubusercontent.com/46412508/119475844-5ba42380-bd02-11eb-9c53-caad8b5bf3bc.PNG)
(Although it requires the library to be initialized first to not segfault)

Maybe something in the mess of `Deps` in config_win can be changed so that it only picks up the right freetype, and therefore compiles against it?

**Comment by MyreMylar** [comment]
This issue is still present on windows in 2.1.2. 

```
import pygame.freetype
print('Freetype version:' + str(pygame.freetype.get_version()))
```
Gives:
```
pygame 2.1.2 (SDL 2.0.18, Python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Freetype version:(2, 4, 12)
```

indicating that we still have some old freetype .lib/header files getting compiled into the windows build.

I assume it is coming from these two zip files:

https://pygame.org/ftp/prebuilt-x86-pygame-1.9.2-20150922.zip
https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip

Which rather tellingly have pygame 1.9.2 in the file name.

**Comment by illume** [comment]
Note, there’s a new mingw64 based tool chain that does all the dependencies including freetype. Worth a try I reckon.

Alternatively it might be awesome to use our build scripts with mingw. Perhaps we would need to convert them a bit to use cmake more and probably a few other hacks. But if it worked, that would be awesome to be able to use all the same scripts.

**Comment by Starbuck5** [comment]
The solution is to update the header files with the prebuilts to be the correct version of freetype to match with the freetype we get bundled from SDL_ttf. That version should be 2.9.1.

I meticulously went through the prebuilts and cleaned out a lot of unused crud (like SDL1 headers, SDL1 prebuilts), reducing the bundle size from ~10 mb to ~1.5mb.

Here's the x64 version: 
[prebuilt-x64-pygame-2.1.3-20220317.zip](https://github.com/pygame/pygame/files/8282570/prebuilt-x64-pygame-2.1.3-20220317.zip)

I would put this in a PR, but I also want to get us up to SDL_ttf 2.0.18, which will necessitate changing this again, since SDL_ttf is now statically linked to freetype, so we can't rely on it to supply freetype anymore.
