### ISSUE TITLE
What's new in pygame 2?

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1146]
pygame 2 has a lot of new things. 

But we need to tell people about all the new goodies.

We need:
- small paragraphs of text explaining exciting features.
- tweet sized texts explaining new stuff
- benchmarks
- mini examples of how to use the new stuff

How to find what's new anyway?
- have a look at closed pull requests
- have a look at the SDL2 what's new annoucements
- ask people (here or in the discord chat)

**To Do list for the feature list:**
- [x] Produce draft of 'Pygame 2 New Features List' from release announcements and PRs.
- [x] Sort features into major/minor/bug fix.
- [ ] Review list and make sure all the descriptions are detailed enough.

**Other To Dos**

- [ ] create benchmarks comparing pygame 1 and pygame 2 performance with blitting.
- [ ] Create promo 'tweetable' list of features?
- [ ] Add examples for new stuff.

**Comment by Spl99** [comment]
Hey, I'd like to help with this issue. Would it be best to take all the closed PR's with 2.0 labels on them and try and turn them into more readable bit of information? Or is there only specific PR's I should be looking at?

**Comment by MyreMylar** [comment]
> Hey, I'd like to help with this issue. Would it be best to take all the closed PR's with 2.0 labels on them and try and turn them into more readable bit of information? Or is there only specific PR's I should be looking at?

I suspect @illume's release descriptions [are a good place to start](https://github.com/pygame/pygame/releases) as to what is more important for a final Pygame 2 feature list. Probably the best thing to do is scroll through those, produce a draft and then post it in an issue (maybe here) and then people can argue over what should be in it, what should be highlighted and so on. Pull requests can be a bit more messy to sort noise from signal but are a good backup resource if there is something that's been missed.

**To Do list for the feature list:**
- [ ] Produce draft of 'Pygame 2 New Features List' from release announcements and PRs.
- [ ] Sort features into major/minor/bug fix.
- [ ] Review list and make sure all the descriptions are detailed enough.

**Comment by ankith26** [comment]
I’m starting to work on this.

**Comment by Starbuck5** [comment]
Here's my crack at it:
I didn't get everything, but I think this is a fair list.

**Major**
The big focus of pygame 2 was to upgrade the backend from `SDL1` to the hugely more recent (and actively maintained) `SDL2`. Why does this matter? It allows pygame to support many more features, and it gives pygame much better support for systems that `SDL1` was never designed to support.

- New window flags: `pygame.SHOWN`, `pygame.HIDDEN`, and `pygame.SCALED`.
- Backwards compatibility. (Still supports Python 2 even!)
- Countless documentation improvements.

**Minor**
- Type Hints. (Gives users a better experience in editors).
- Rects can be drawn with rounded corners.
- Image.save namehint for saving to bytes objects.
- Mask.to_surface, Mask.copy, and Mask.get_rect added.
- Use Color arguments anywhere. `surf.fill("black")`
- Experimental vsync support (only works with `pygame.OPENGL` and `pygame.SCALED`).
- Added pygame.event.custom_type(). (important for libraries especially).
- Set font bold, italic, and underline with direct attributes.
- Added `pygame.TEXTINPUT` events for better text handling.
- Added support for touch input.
- Added support for dropping files into a window with `pygame.DROPFILE`.
- Rect.clipline for Rect v. line collision detection.
- Joystick.get_power_level, get_instance_id, and get_guid methods added.
- Better support for PyInstaller.

**Bugfix**
- Ellipse with width > 1 draws without holes.
- Many memory handling fixes.
- Fix case where transform.chop() could return a surface larger than the original.
- Works much better on newer versions of macOS X. (But now macOS 11 is out and we have to start again :cry:)
- Python 3.8 and 3.9 compatibility.
Of course, more than 6 bugs were fixed in the ~1.5 years of development of pygame 2, these are just a few.

**Comment by twistios** [comment]
What is expected for the blit-benchmark?
My current investigations already show a difference for the number of updates per second, if the screen was just filled with a color at the beginning (it also may come because of the different Python versions I used for testing, I am pretty new to testing and developing in general).

**Comment by twistios** [comment]
I started the development of a very simple benchmark. I attached the current version of the benchmark (it is a WIP) and plots of example runs on my maschine (I was to lazy to use the venv :D )
-Pygame 2.0.0 using Python 3.9.1
-Pygame 1.9.6 using Python 3.8.6

![pygame1_9_6-benchmark](https://user-images.githubusercontent.com/54811436/130168389-a0742924-77cd-4679-b81b-fb2f4fc5a8ef.png)
![pygame2_0_0-benchmark](https://user-images.githubusercontent.com/54811436/130168400-ad6d8bbc-5294-4bb0-a829-c3b94225869e.png)

[pygame_benchmark.zip](https://github.com/pygame/pygame/files/7018684/pygame_benchmark.zip)

**Comment by MyreMylar** [comment]
My suspicion on any blitting benchmarks is that you want to do blits at various sizes and blend modes. My intuition is that the default blitter on 1.9.6 likely performs better/more competitively with 2.0.0 on smaller and more standard blits but the 2.0.0 does better with larger ones and some of the more unusual blits. Some blits (e.g. the _ADD, _SUB and _MUL ones) should currently be equally bad on both versions as they still need to be SIMD accelerated. 

I wanted to do some proper testing of it all at some point but life has kept getting in the way.

**Comment by twistios** [comment]
I improved the benchmark I developed:
-it now can show the plots by itself
-added benchmark for different blend modes
and other small improvements.

I createded a repo with the code: https://github.com/twistios/pygame_tools

At least on my maschine it looks like (at least for BLEND_ADD) that 2.0.0 is better than 1.9.6 (I used the same Python installation with venv's: Python 3.8.6 on Windows 10 x86-64Bit).
![pygame1_9_6-benchmark_blending](https://user-images.githubusercontent.com/54811436/130370088-6c83513f-dca7-4635-94db-0dc5e0c9aefa.png)
![pygame2_0_0-benchmark_blending](https://user-images.githubusercontent.com/54811436/130370089-ebbe1eb3-04b8-481a-a2bc-1ef02530044b.png)

**Comment by FierceJDM** [comment]
> Review list and make sure all the descriptions are detailed enough.
Which list are you referring to in this task ?

**Comment by Starbuck5** [comment]
I'm going to close this, as pygame 2 has been out for long enough now that the ship to do this has sailed.

@FierceJDM Maybe you could handle #3083 then? If you have questions or need to work stuff out (like getting pygame building from source), you should head over to the pygame community discord, there's a contributing channel. (https://discord.gg/kD2Qq9tbKm)
