### ISSUE TITLE
SCALED + FULLSCREEN on second screen wrong size

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1169]
When using SCALED on a second screen plugged in on MacOS, some of the surface gets cut off. The parrotjoy app has this issue.

**Comment by robertpfeiffer** [comment]
Can you draw a diagram of your screen layout and resolutions? Or post a screenshot of the display configuration tool? Did you pass a display number to set_mode?

**Comment by illume** [comment]
Sorry, this was more a note to myself whilst I remembered and I didn't get back to filling in the details. I'll do a test later and try to note down more details.

**Comment by robertpfeiffer** [comment]
I think on a multi-monitor setup, we cannot use SDL_WINDOWPOS_UNDEFINED, we actually have to query the geometry of the monitors.

**Comment by galexandreg** [comment]
I tried it on my end with two different project, using different resolutions. One is using 960x540 and the other 540x540.

**960x540**(half HD, the same 16:9 aspect ratio as the external monitor)

- Almost everything works fine. FULLSCREEN works, but is scaled to a strange resolution that is not the original and not the full monitor resolution.
- SCALED works too, but some space is taken by the menu or control bar on top of the window.
- **Both together work just fine.**

**540x540**

- **FULLSCREEN dosent work**. The image is stretched is a weird way and some of it is hidden.
- SCALED works like with the other resolution.
- **Using both works just fine.**

So on my end, the only real problem is when I'm using FULLSCREEN alone with another aspect ratio.


Using the **main monitor** is a little different.
- FULLSCREEN and SCALED is also working fine.
- FULLSCREEN alone doesn't work right on the 540x540. It works with the 960x540 but scales the image at a strange "in-between" resolution, like with the external monitor.
- **SCALED alone dosent do anything.**

Pygame 2.0.0.dev3, Python 3.7.3, macOS 10.14.5
1280 x 800 (main) and 1920 x 1080 (external) monitors

**Comment by robertpfeiffer** [comment]
thank you, @galexandreg

Does SCALED work when it's just the full HD monitor?

**Comment by galexandreg** [comment]
I'm not sure to understand your question.

SCALED alone on the hd monitor works but some space is taken by the control bar at the top, so the bottom is invisible.

If you mean using ONLY the HD monitor with the Mac, unfortunately, the main one is the integrated one on my laptop so I don't think I can disable it.

**Comment by galexandreg** [comment]
Well, I guess It's possible to disable it 😄 
So, yes, SCALED works with only the HD monitor.

**Comment by robertpfeiffer** [comment]
related to #902

**Comment by illume** [comment]
I can't reproduce it anymore with the example test case.

I'll try again with parrotjoy, since that's where I first noticed the issue.

**Comment by robertpfeiffer** [comment]
I *think* we can close this. I'm not quite sure though.

**Comment by illume** [comment]
Works for me :)
