### ISSUE TITLE
SDL2: pygame.cdrom package was not found

### ISSUE THREAD

**Issue by project-owner** [pygame/pygame#1187]
When I was trying to use pygame 2.0.0.dev3 on the latest Raspbian Buster I got the following exception:
```
>>> import pygame.cdrom
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pygame.cdrom'

```
It would be very helpful to get that package back.

**Related Docs:** https://www.pygame.org/docs/ref/cdrom.html

**Comment by illume** [comment]
Note for self...

The cdrom code in the SDL1.2 tree can be found here:
https://github.com/SDL-mirror/SDL/tree/SDL-1.2/src/cdrom

**Comment by project-owner** [comment]
If you are not going to include cdrom support into Pygame2 could you provide instructions how to add/compile it for those who needs it?
Thank you!

**Comment by illume** [comment]
The cdrom code is not in SDL2 any longer. The code looks very complicated to bring into pygame.

Here are possibilities:
- hope someone to maintain the cdrom module
- find someone willing to rip out the SDL1 cdrom code, and make a new library.
- link to SDL1 for the cdrom module only. Not sure this is possible.
- try and vendor the cdrom code into pygame itself.
- A workaround would be to use pygame 1.9.x for the cdrom module

There's no nice or easy way forward as far as I can see.

**Comment by nthykier** [comment]
Personally, I am leaning towards depreciating the cdrom module and removing it in pygame2 (at least the SDL2 builds).  None of the other options seem reliable and healthy long term solutions - especially vendoring the module inside pygame means putting an extra maintenance burden on the pygame developers, who seem to be maxed already.

Given that CD-ROMs are becoming are and computers with support for them equally so, I think honestly think this is the "best" (lesser evil) way forward.

**Comment by MyreMylar** [comment]
@project-owner 

Would [this python module](https://pypi.org/project/pycdio/) work for you as a suitable replacement for the cdrom module of pygame? It is under the GPL 3.0 license which may, or may not, impact your use case, but it seems to be a fairly well supported library for cd playing with a pypi package.

**Comment by project-owner** [comment]
I have not tried that library yet. So I cannot tell if it will be easy replacement. pygame.cdrom worked on Windows and Linux without any additional libraries. pycdio needs installation of additional dependencies: libcdio, SWIG and pkg-config. Maybe I'll try that later on.

**Comment by MyreMylar** [comment]
> Maybe I'll try that later on.

Let us know if it works out. 

I glanced over the old SDL 1.2 cd rom module code and there is a _lot_ of it, different code for every platform (the OSX code in particular looks extensive). I guess there never were any cross platform standards around CDs - I can see why they wanted to ditch supporting it for SDL 2.

**Comment by rocky** [comment]
@MyreMylar that's why I wrote [libcdio](https://www.gnu.org/software/libcdio/). I think at one point I tried to interest the SDL folks to use (and contribute to) that instead of what they had &mdash; to no avail. 

SDL was not the only project that provided its own custom CD-ROM code; a number of the others did/do as well. For example [xine's cdda](https://sourceforge.net/p/xine/xine-lib/ci/default/tree/src/input/input_cdda.c) is one 3k file full of `#ifdefs` and mplayer, the last I looked a while ago, was aos in this camp. In addition to the reduced overall overhead of maintanance, there's the fact that there are additional features in the shared library approach. So libcdio can read cd disk images such as those Nero and BIN/CUE. And in contrast to cdparanoia which officially works only on GNU/Linux, libcdio's version works on all of the platforms it supports.

20 years ago I had thought if you build a better mousetrap people will use it. To some extent that's true, but the caveat is that it took 15 years for that to happen while some projects decided instead just to drop support for CD-ROMs (which I guess is a reasonable thing to do nowadays).

**Comment by Starbuck5** [comment]
To bring the discussion here from #2511 

> I don't think this should close #1187 though. Instead we should leave that open and make it clear that we'd accept PRs but no one is currently planning on working on it.

If there isn't a plan to support pygame.cdrom should we remove this issue from the 2.0 milestone?

**Comment by llindstrom** [comment]
A look at https://github.com/SDL-mirror/SDL/tree/SDL-1.2/src/cdrom suggests the SDL cdrom code is nearly stand-alone from the rest of SDL. It does not call any of the SDL audio or event routines, for instance. So changing pygame's cdrom module to use libcdio instead will not impact the rest of pygame. My only concern is the GPL 3.0 license of libcdio. Would that prevent including it as a prebuilt shared library in pygame distributions.

**Comment by Starbuck5** [comment]
No one seems interested in porting some alternative CD solution into pygame, and it seems like it would be best left to an external library anyways.

I'm going to close as not planned, barring any objections 🙂
