### ISSUE TITLE
SDL dependencies not bundled on Raspbian

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#1229]
The more I think about this, the more I think it may be intentional on Linux (most things seems to be like this), but I don't really know where to say/ask this.

I tried installing pygame2.0.0.dev3 on my RaspberryPi using the Piwheels build and it seems like the SDL isn't bundled with it like it is on Mac OS or Windows.

I already have the SDL2 itself, but I have to manually install other modules I want (like mixer and font) for everything to work.

So my question/observation is: it it normal that they are not bundled with Pygame like it is on Windows and macOS? Or is it intentional (maybe because of how easy it is to install them with the various packages managers on Linux)?

**Comment by illume** [comment]
piwheels works by using the system dependencies. The also have some binaries which are uploaded via packages. The reason is because the python 'manylinux' didn't previously support armv6 that they use. I'm not sure if manylinux2014 supports `armv6` now, or if a future version will. Additionally they include various tweaks and patches in their system packages including inside SDL compared to the SDL releases or the Debian packages. I think it's now easier for us to make our own ARM wheels, but I'm not sure if they can be Raspberian compatible, or if they are selected over the piwheels ones.

There's a [cibuildwheel](https://github.com/pygame/pygame/issues/1661) issue open about using it's tooling which can be used for making various binaries wheels, including on ARM. It's only used for the mac builds so far.

Open research questions:
- does manylinux and cibuildwheel of some sort support armv6? (manylinux2014?) needed for raspberian compatibility.
- do manylinux wheels uploaded to pypi take precidence over piwheel ones?

**Comment by MyreMylar** [comment]
Fairly certain that many linux does not support armv6. Even Arm7 support seems contentious due to lack of CI, see:

https://github.com/pypa/manylinux/issues/84

**Comment by MyreMylar** [comment]
> do manylinux wheels uploaded to pypi take precidence over piwheel ones?

Nope looks like pip on raspberry pi defaults to piwheels, see: https://github.com/pypa/manylinux/issues/84#issuecomment-323777244

**Comment by MyreMylar** [comment]
> can we upload our own wheels to piwheels? How?

It looks like piwheels do all the building and uploading themselves on raspberry Pis.

I guess the best person to ask about the last question is probably the BBC's @bennuttall since they built piwheels and presumably control the build scripts:

If you do see this Ben:

1. Can the dependencies needed by piwheel pygame(s) be installed by default on Raspberian too?
2. Does PiWheels now have distinct arm6 and arm7 wheels?
3. If Arm7 wheels now exist, does that mean we could upload two version of pygame to PiWheels, one _with_ Neon extensions for Pi3+ and one _without_ neon extensions for Pi1 (Arm6)?

**Comment by bennuttall** [comment]
👋 

>Can the dependencies needed by piwheel pygame(s) be installed by default on Raspberian too?

pygame is pre-installed in Raspbian (via apt) which obviously includes its deps. If you can get the apt version of pygame in Raspbian updated to v2 and deps are available, that could be possible. You'd need to speak to Raspberry Pi about that. I'd be happy to do an intro with the right people.

If you see the pygame project page on piwheels, you can see the apt dependencies (calculated after build): https://www.piwheels.org/project/pygame/

> Does PiWheels now have distinct arm6 and arm7 wheels?

All automated wheels are built on Pi 3 (armv7) but when renamed, they work on Pi 1 (armv6), so we provide symlinks to the armv7 files, so they're identical but work on both archs.

The only exceptions are imported files for opencv and tensorflow.

> If Arm7 wheels now exist, does that mean we could upload two version of pygame to PiWheels, one with Neon extensions for Pi3+ and one without neon extensions for Pi1 (Arm6)?

That's possible. One thing to bear in mind: Pi 1 and Zero identify to pip as "armv6l" and Pi 2, 3 and 4 identify as "armv7l". So could you guarantee the armv7 wheel will work on at least Pi 3 and 4? If not, a) you can't provide two armv7 wheels (one for Pi 3, one for Pi 4) and b) we (piwheels) won't host armv7 wheels that don't work on both Pi 3 and 4. I don't think our neon opencv/tf wheels work on Pi 2 but that's a tiny usage share. Having separate wheels is only worthwhile if there's a considerable benefit from optimisation.

It's worth noting that generally speaking, pygame wheels can be built by piwheels. There's a temporary glitch that is preventing the automation from completion (we calculate apt dependencies which takes ages and times out as there are so many for pygame) - we have a fix for it coming soon (tm).

Options in order of my preference:

1. pygame wheels are automated like everything else, same wheels for armv6/7
2. pygame wheels are built offline by me or dave (piwheels team) (like opencv)
3. pygame wheels are built by pygame team and sent to me to be uploaded (like tensorflow) - ok as long as the wheels work on Pi 1/Zero/3/4, but includes manual work, and chasing up (I still don't have any v2 tensorflow wheels 😞 )

**Comment by MyreMylar** [comment]
Thanks for responding so quickly :)

> That's possible. One thing to bear in mind: Pi 1 and Zero identify to pip as "armv6l" and Pi 2, 3 and 4 identify as "armv7l". So could you guarantee the armv7 wheel will work on at least Pi 3 and 4? If not, a) you can't provide two armv7 wheels (one for Pi 3, one for Pi 4) and b) we (piwheels) won't host armv7 wheels that don't work on both Pi 3 and 4. I don't think our neon opencv/tf wheels work on Pi 2 but that's a tiny usage share. Having separate wheels is only worthwhile if there's a considerable benefit from optimisation.

- We have only a small amount of arm neon code in pygame at the minute (in the master branch) that is disabled by default for arm6 compatibility. I've personally only tested it on Pi4 so far but it uses Arm's neon intrinsic functions so there is no reason it won't also work on Pi3. 
- Performance wise the neon code appears to speed up the particular alpha blitting process (pre-multiplied blending) by about 3 times over the straight C code version. Suggesting there might be decent performance wins there in the future.
- We are basically doing a bit of investigation on the best way to get this code out to people who might benefit from it and separate wheels for Pi1/Pi0 was brought up as potentially one of the safest ways of doing it. 
- If there is a good pipeline going from us here to people calling `pip install pygame` on pi and getting a significantly faster version for their Pi then it definitely increases the worth of us going through even more of the old pygame code only code and seeing if we can port it to SSE2 & Arm Neon.

It does sound like it is a bit of ballache on your end to support separate Arm7 wheels so I guess we'll factor that into the calculus of how to approach this topic.

**Comment by MyreMylar** [comment]
**Potential investigation work:**

- [ ] Test current pygame neon optimisations on Pi 3, so I have a firmer answer than 'should work'.

**Comment by MyreMylar** [comment]
> pygame is pre-installed in Raspbian (via apt) which obviously includes its deps. If you can get the apt version of pygame in Raspbian updated to v2 and deps are available, that could be possible. You'd need to speak to Raspberry Pi about that. I'd be happy to do an intro with the right people.

I think this is definitely worth doing for the final release of pygame 2.

**Comment by bennuttall** [comment]
Another option is to let piwheels automate builds that work for everyone, and pygame hosts their own optimised wheels somewhere, instructing users who want them to install them from elsewhere.

**Comment by ankith26** [comment]
> Test current pygame neon optimisations on Pi 3, so I have a firmer answer than 'should work'.

Can confirm that works on my pi3 running 32-bit PiOS bullseye

Okay, so I think the solution that works best for everyone, is that we should have some runtime armv6/armv7 detection code, and the armv7 intrinsics codepaths should not run on armv6. This way it's also easier for piwheels, you can continue the automated generation of armv7 wheels and their rename to armv6 wheels, and things will be fine on runtime. The optimisations are enabled by default on armv8, we have aarch64 wheels on our releases. This wheel should work on a modern pi running a 64bit OS (untested). Issue #1723 seems to be relevant to be discussing this further

Ok, seems like we drifted from the original topic of this issue 😅 but that also means this issue can be closed, because the original question about dependencies not being bundled on raspbian (now PiOS) is infact, intended and is not an issue.
