### ISSUE TITLE
A Display Problem with Pygame 1.9.5

### ISSUE THREAD

**Issue by godisreal** [pygame/pygame#1308]
Excuse me.  There is a display problem about Pygame.  Anything wrong with the following code?  I suppose not.  So the problem is related to the version of Python?  
Your suggestion is much appreciated.  

https://github.com/godisreal/group-social-force/issues/5

```
pygame.init()
screen = pygame.display.set_mode(SCREENSIZE)
pygame.display.set_caption('Modified Social Force Model')
clock = pygame.time.Clock()
...

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.MOUSEBUTTONDOWN:
            (mouseX, mouseY) = pygame.mouse.get_pos()
        # elif event.type == pygame.MOUSEBUTTONUP:

    screen.fill(BACKGROUNDCOLOR)
    ...


    pygame.display.flip()
    clock.tick(20)

```

**Comment by dlon** [comment]
Could it be related to #555?

**Comment by MyreMylar** [comment]
I expect this report is just a recent OSX version user trying to use pygame 1, but we could test the posted code just to see.

**Comment by MyreMylar** [comment]
Noticed that the posted code can't actually be tested as is, because it is abbreviated with `...`. However it's not doing anything odd at all. 

Looking at the linked issue on the other github repo I'm almost certain this is just the standard 'modern OSX doesn't work with pygame 1/SDL1' issue we get reported every other week. Don't think there is any work for pygame here, other than telling people on mac to use pygame 2 whenever they ask, so I think I'll close this for now.
