### ISSUE TITLE
pygame.Surface.get_flags() ignore FULLSCREEN in 2.0.0.dev3

### ISSUE THREAD

**Issue by humanbeast7** [pygame/pygame#1343]
### issue:
while importing code from pygame 1.9.6 to pygame 2.0.0.dev3
the visible Surface (from display.set_mode())
did not appear to notice it has a FULLSCREEN flag
### notes: 

1. that the Surface is appearing in full screen, 
    only the Surface.get_flags() do not include it
2. only the FULLSCREEN flag was tested,
    other flags might be affected as well

**Related Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_flags

**Comment by humanbeast7** [comment]
as the next release came out, i thought to clarify the issue,
so i scripted a test to see which flags affected.

### System Details:
- Windows 10
- Python 3.7.4
- Pygame 2.0.0.4dev and 1.9.6

i checked all the flags mentioned both in the display and surface docs (except the internal usage/read only ones)
### here's the test:
```
import pygame
from pygame.locals import SWSURFACE, HWSURFACE, ASYNCBLIT, ANYFORMAT, HWPALETTE, DOUBLEBUF, FULLSCREEN, OPENGL, RESIZABLE, NOFRAME, SCALED


pygame.init()
FLAGS = {SWSURFACE: 'SWSURFACE',
         HWSURFACE: 'HWSURFACE',
         ASYNCBLIT: 'ASYNCBLIT',
         ANYFORMAT: 'ANYFORMAT',
         HWPALETTE: 'HWPALETTE',
         DOUBLEBUF: 'DOUBLEBUF',
         FULLSCREEN: 'FULLSCREEN',
         OPENGL: 'OPENGL',
         RESIZABLE: 'RESIZABLE',
         NOFRAME: 'NOFRAME'
         SCALED: 'SCALED'}

for flag in FLAGS:
    l = pygame.display.list_modes(flags=flag)
    if isinstance(l, int):
        screen = pygame.display.set_mode((600, 400), flag)
    elif len(l) == 0:
        print("unable to test flag " + FLAGS[flag])
        continue
    else:
        screen = pygame.display.set_mode(l[0], flag)

    if screen.get_flags() & flag:
        print("flag " + FLAGS[flag] + " successfully retrived")
    else:
        print("get_flags ingnores " + FLAGS[flag] + " flag")

pygame.quit()
```
(SCALED not in 1.9.6, obviously)

### 1.9.6 output:
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
get_flags ingnores SWSURFACE flag
get_flags ingnores HWSURFACE flag
get_flags ingnores ASYNCBLIT flag
get_flags ingnores ANYFORMAT flag
get_flags ingnores HWPALETTE flag
get_flags ingnores DOUBLEBUF flag
flag FULLSCREEN successfully retrived
flag OPENGL successfully retrived
flag RESIZABLE successfully retrived
flag NOFRAME successfully retrived

### 2.0.0.4dev output:
pygame 2.0.0.dev4 (SDL 2.0.10, python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
get_flags ingnores SWSURFACE flag
get_flags ingnores HWSURFACE flag
get_flags ingnores ASYNCBLIT flag
get_flags ingnores ANYFORMAT flag
get_flags ingnores HWPALETTE flag
get_flags ingnores DOUBLEBUF flag
get_flags ingnores FULLSCREEN flag
get_flags ingnores OPENGL flag
get_flags ingnores RESIZABLE flag
get_flags ingnores NOFRAME flag

the first five flags might have not been even in action because of my hardware (it's not like i have a gaming gear or something) but i hardly believe that's the case.
if it is really not the case, that means that the problem is even older then pygame 2
sorry for the long message, but i couldn't find a way to insert a potato...

**Comment by illume** [comment]
Thanks for the test case @humanbeast7 :)

**Comment by robertpfeiffer** [comment]
@humanbeast7 
First, thanks for the detailed report.

> the first five flags might have not been even in action because of my hardware (it's not like i have a gaming gear or something) but i hardly believe that's the case.

HWSURFACE is for hardware with dedicated sprite memory, like the Super Nintendo (SNES doesn't run PyGame, but you get the idea). I think GP2X and Dreamcast supported SD1.2 and pygame at some point, and had HWSURFACE implemented. On modern PC hardware, you have a GPU with 3D acceleration instead of 2D acceleration and sprite memory. Dedicated sprite memory is also superseded by 3D acceleration in modern consoles and handhelds. PS4, Switch, and Android support SDL2 with OpenGL (ES) or even Vulkan. The XBox One supports SDL2 with DirectX. No *modern* platform that runs SDL2 has HWSURFACE support any more. 

@illume 

I don't think this warrants "critical". Most of the current behaviour should be *documented*, not changed for backward compatibility. If you request HWPALETTE, ASYNCBLIT, or HWSURFACE with SDL2, the display surface won't actually *be* a HWSURFACE, so this test case is *expected* to fail, even with SCALED (which has a *copy* of the surface data in HW memory, not the surface itself). If the user queries for these flags, the result should be negative, and we obviously shouldn't just copy over the flags from the call to set_mode.

RESIZEABLE, SCALED and NOFRAME are properties of the window now, not of the display surface. The only property we actually *need* is OPENGL, so we know not to draw/blit to the surface, but *in practice* that state is usually handled by pyOpenGL or modernGL. If can we can get a handle on an openGL context, then we're running with OPENGL.

This issue got me thinking about invalidated display surfaces. You can keep a reference to an invalidated display surface. What happens if you access it? What should happen?

We could track whether a surface is a display surface, and whether it has been invalidated, and if it is *the* current display surface, query the window flags. We could add two flags for internal use to the pygame surface struct and invalidate the old display surface when a new one is created. I don't know if anybody re-creates the display surface and expects the new one to be different, or the old one to still be working as a non-display surface. AFAIK, SDL2 destroys the old display surface when it creates a new one, as does pygame.

We could probably test whether a surface is the current display surface in get_flags, but I don't think we should refer to display from Surface.

I would really like to see a use case for these flags. Otherwise deprecation of get_flags() (which doesn't do anything useful any more) and a new API might be in order.

**Comment by illume** [comment]
I think the main use case is:
- "are we fullscreen?"

**Comment by nthykier** [comment]
Related, we should probably stop documenting flags such as `pygame.FULLSCREEN` under `pygame.surface.get_flags()`.  While the current phrasing might be "technically" correct it is confusing at best.

```
   .. method:: get_flags

      | :sl:`get the additional flags used for the Surface`
      | :sg:`get_flags() -> int`

      Returns a set of current Surface features. Each feature is a bit in the
      flags bitmask. Typical flags are ``HWSURFACE``, ``RLEACCEL``,
      ``SRCALPHA``, and ``SRCCOLORKEY``.

      Here is a more complete list of flags. A full list can be found in
      ``SDL_video.h``

      ::
[...]

      Available for :func:`pygame.display.set_mode()`

      ::

[...]
        FULLSCREEN     0x80000000    # Surface is a full screen display
[...]
```

My assumption when reading that would be that the return value of `get_flags` could include `pygame.FULLSCREEN` (which it does when running pygame with SDL1).

Which brings me back to: Lets remove `display`-related flags from the documentation of the `surface`-related flags.  I am happy to write a patch for it if someone can help me identify which flags are `display` and which are `surface` related flags (and the subset of the `display` flags that make sense to expose to the programmers).

**Comment by illume** [comment]
Closing this now, thanks to the PR from MyreMylar is merged. Thanks everyone. It should be in 2.0.0.dev14.
