### ISSUE TITLE
ffmpeg integration and dpi assignment to pygame.image.save 

### ISSUE THREAD

**Issue by Severian-desu-ga** [pygame/pygame#1401]
Good day,

I've recently created a game using pygame and wanted to promote it with a quick animation and screenshots. However I noticed that the function pygame.image.save did not have any dpi option to adjust the save resolution/quality. Also it would be really helpful if ffmpeg could be integrated into pygame to save the screen play as a movie output. 

Many thanks,
Severian-desu-ga

**Comment by robertpfeiffer** [comment]
This is already doable in pure python, by calling the ffmpeg binary as a subprocess and feeding pygame image data to it. The obvious requirement requirement is that you have ffmpeg already installed.

You can also use Pillow or moviepy to do it.

Video/GIF encoding takes a lot of time and RAM, and there are several different way to do it (save pngs to disk and call ffmpeg on a list of frame files, dump raw data as continuous stream, encode incrementally in a separate thread and pipe frames to ffmpeg, stop the game and call ffmpeg synchronously, call imagemagick instead of ffmpeg for GIF etcetera)

But I'd be inclined to close this issue because it already works.

**Comment by illume** [comment]
@robertpfeiffer Was there an issue already open for 'making a video of gameplay'? I vaguely remember someone (maybe you?) making one, but I can't see it now.  It would be good if there was a place where people could collaborate or talk about this topic - and we could close this issue.

The other part mentioned is setting the DPI on jpeg files. We use libjpeg for image saving currently, and I'd accept patches, but aren't interested in implementing that myself. Come to think of it... we might perhaps switch to using SDL2 code for this in the future (since I think they have these functions in there now). It's possible to convert an image to Pillow easily, so if they support it consider that.

**Comment by Severian-desu-ga** [comment]
@robertpfeiffer thank you. I actually did just that, by stitching images together using the ffmpeg binary called in a subprocess. 

@illume also many thanks! Functionality is always nice to have, especially from minimum module imports. But Pillow does seem like the best current alternative to increasing the resolution when saving screen play. Still it would be nice if it could be done internally in pygame, and your suggestion of switching to SDL2 code is promising. Looking forward if it is implemented.

Much appreciative from both of your inputs and insight.
