### ISSUE TITLE
A problem of using py2exe with pygame

### ISSUE THREAD

**Issue by godisreal** [pygame/pygame#1481]
When I use py2exe with a small program of pygame, the execuable file is successfully produced. 
However, when I run it, it returns the following error message.  What is the module named _view?
Does anyone know how to solve the problem?  Many thanks.  
```

C:\Documents and Settings\WP\Desktop\PySim\Test_py2exe\dist>simulator_WP_Doorway
.exe
simulator_WP_Doorway.exe:4: RuntimeWarning: import display: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import draw: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import image: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import pixelcopy: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import transform: No module named _view
(ImportError: No module named _view)
Traceback (most recent call last):
  File "simulator_WP_Doorway.py", line 5, in <module>
  File "pygame\draw.pyc", line 12, in <module>
  File "pygame\draw.pyc", line 10, in __load
  File "pygame\surface.pyc", line 12, in <module>
  File "pygame\surface.pyc", line 10, in __load
ImportError: No module named _view
```

**Comment by robertpfeiffer** [comment]
It used to be that you have to write
```python
import pygame
import pygame._view
pygame.init()
```
for pygame to work with py2exe.

But as fair as I know, py2exe is no longer actively maintained, and if you want to make py2exe work with new versions of Python, you have to hack it yourself. Maybe the thing I wrote still works, maybe it doesn't.

In any case, I have to close this issue, because it's not a problem with pygame itself, and not a problem we can fix.

I would recommend using PyInstaller (if you want an exe or .app bundle) or pynsist (if you want an installer, I know, naming is backwards). Pynsist is maintained by @takluyver, and can bundle most dependencies if they can be installed from PyPI.

If you use PyInstaller, I'd recommend using Python 3.7 or checking if the newest PyInstaller release supports Python 3.8, and installing the newest pygame-2.0.0-dev6 release.
