### ISSUE TITLE
AttributeError: partially initialized module 'pygame' has no attribute 'init' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Zacky2456** [pygame/pygame#1531]
**Environment**

* pip version:19.3.1
* Python version:3.8.0
* OS:Windows

I have no idea why this error is showing up but whenever i run a very simple line of code that says 

import pygame
pygame,init()

it give me the following error:

AttributeError: partially initialized module 'pygame' has no attribute 'init' (most likely due to a circular import)

![error](https://user-images.githubusercontent.com/58615455/70367695-65e12080-18c8-11ea-9b3a-7d603dfdde89.JPG)

please help me as soon as possible

**Comment by Starbuck5** [comment]
I don't think you can make a python file palled pygame.py if you want to import pygame.

**Comment by Zacky2456** [comment]
Thanks! It works!

**Comment by pumapunkuu** [comment]
Hey guys I am also having this message while I was trying to import turtle
![Ekran Resmi 2020-04-24 23 36 42](https://user-images.githubusercontent.com/56896947/80254883-a5948300-8684-11ea-970d-8c91843669fa.png)

**Comment by Starbuck5** [comment]
You can’t name your file turtle.py if it imports turtle, because it will import itself. There also can’t be a file in the same folder named turtle.py

**Comment by pumapunkuu** [comment]
Thanks mate!! I just figured out
Stay healthy ,best regards.

________________________________
Gönderen: Starbuck5 <notifications@github.com>
Gönderildi: 24 Nisan 2020 Cuma 23:43
Kime: pygame/pygame <pygame@noreply.github.com>
Bilgi: pumapunkuu <yekda94@hotmail.com>; Comment <comment@noreply.github.com>
Konu: Re: [pygame/pygame] AttributeError: partially initialized module 'pygame' has no attribute 'init' (most likely due to a circular import) (#1531)


You can’t name your file turtle.py if it imports turtle, because it will import itself. There also can’t be a file in the same folder named turtle.py

**Comment by venkyMacha** [comment]
Wow! U started with the exact same to projects. Up to the name of it. pong and then pygame. lol🤣

**Comment by sauron4er** [comment]
Hello all! I have that error too, but my names are not the same. Need your help.
So I have two apps: `edms` and `docs`.

In file `docs.models` I use this:
`import edms.models as edms`
`class Contract(models.Model):`
`    ...`
`    edms_doc = models.ForeignKey(edms.Document, related_name='edms_docs', null=True, on_delete=models.RESTRICT)` # tried to comment this - didn't help

In file `edms.models` I'm trying this:

`import docs.models as docs`
`class Doc_Contract(models.Model):`
`    ...`
`    document = models.ForeignKey(Document, related_name='documents', on_delete=models.RESTRICT)` # tried to comment this - didn't help either
`    contract = models.ForeignKey(docs.Contract, related_name='contracts', on_delete=models.RESTRICT)
`



Error occurs in file edms.models and says:
> AttributeError: partially initialized module 'docs.models' has no attribute 'Contract' (most likely due to a circular import)

I realize that this problem occurs because I import edms in docs and docs in edms. But I can't extract that Models in another file because all Models must be in file 'models'. Or don't they?

**Comment by ZackyGameDev** [comment]
I got a ghost notification here and came back to check, and now that I am here I might as well say, Wow, it's really been exactly an year now from when I was a beginner.

**Comment by yaswanth-akasam** [comment]
> Thanks! It works!



> I don't think you can make a python file palled pygame.py if you want to import 

> I don't think you can make a python file palled pygame.py if you want to import pygame.

thanku very much

**Comment by swimmableflyer** [comment]
I just had this same issue, I had to completely delete pygame.py before it would work 😀 

Thank you guys 🤣

**Comment by hoseinhoseini** [comment]
> I don't think you can make a python file called pygame.py if you want to import pygame.

I love YOU. it worked. I am Iranian , in iran when a person help us we say to him " عشقی بمولا ". it mean I so Love you

**Comment by ninjabuddy10** [comment]
I don't think you can make a python file called pygame.py if you want to import pygame.


Thank you it works

**Comment by manit-cool** [comment]
> I don't think you can make a python file called pygame.py if you want to import pygame.

dude you just saved my life XD

**Comment by Polar6M** [comment]
> AttributeError: частково ініціалізований модуль 'pygame' не має атрибута 'init' (швидше за все через циклічний імпорт). Я не розумію, чому він не працює, pls help ![Знімок екрана 2023-08-24 165556](https://user-images.githubusercontent.com/143105880/263012544-1e78ca52-6f63-4958-9272-d0e8615373bd.png)

**Comment by Polar6M** [comment]
AttributeError: partially initialized module 'pygame' has no attribute 'init' (most likely due to a circular import)
I don't why it isn't work, please help
![Знімок екрана 2023-08-24 165556](https://github.com/pygame/pygame/assets/143105880/f83147d3-b32a-4af4-9ee5-9e1a23c4f654)

**Comment by ZackyGameDev** [comment]
@Polar6M as Starbuck5 said, there can’t be a file in the same folder named `pygame.py`, because your python will import your `pygame.py` file that you created, instead of the actual `pygame` library. It looks like you have created a file named `pygame.py` in `C:\Users\natal\OneDrive\Dokumenty\Python\pygame`.

**Comment by Polar6M** [comment]
Yes, I had the same problem, thank you very much for your help.
(I am new to python)

**Comment by fasthandsfaster** [comment]
how to pass color to pygame.rect

**Comment by SyedMozahidulIslam** [comment]
![image](https://github.com/pygame/pygame/assets/116684492/4a4acee9-e89c-48b2-8b5c-13c4734a8d15)
How can I handle this?

**Comment by ninjabuddy10** [comment]
> ![image](https://private-user-images.githubusercontent.com/116684492/308585845-4a4acee9-e89c-48b2-8b5c-13c4734a8d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNTM4NDcsIm5iZiI6MTcwOTE1MzU0NywicGF0aCI6Ii8xMTY2ODQ0OTIvMzA4NTg1ODQ1LTRhNGFjZWU5LWU4OWMtNDhiMi04YjVjLTEzYzQ3MzRhOGQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQyMDUyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGEwNzgwMzgzNDhmYjYyMTVhODI2YzY0MzkzMWFkYmUyOTdjYTg5MmE0Mzc5NDhlYTExNmE0YThkYjc0ZGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gUpiDZJ7KrfwC3hYgvsO0umVeVqBg8SmFAnGR-FYA9E) How can I handle this?

it appears like you never installed pygame. it doesn't come with python just so you know

**Comment by STORM-MCCTC** [comment]
> I don't think you can make a python file called pygame.py if you want to import pygame.

i am so stupid omfg
