### ISSUE TITLE
pgzrun not found

### ISSUE THREAD

**Issue by dgolden192** [pygame/pygame#1541]
Versions:
pygame 2.dev
pgzero 1.2
python 3.8.1
Mac Catalina 10.15.2

I initially installed pygame 1.9.6 had a problem with pgzrun.  Read posts in the forum, installed pygame2 dev user.  Still no pgzrun.  Getting the following error when trying oto import pgzrun in IDLE shell

>>> import pgzrun
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    import pgzrun
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pgzrun.py", line 23, in <module>
    prepare_mod(mod)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pgzero/runner.py", line 106, in prepare_mod
    PGZeroGame.show_default_icon()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pgzero/game.py", line 93, in show_default_icon
    pygame.display.set_icon(pygame.image.load(buf))
pygame.error: File is not a Windows BMP file

What am I missing?

**Comment by illume** [comment]
Looks like pygame is compiled with no png support, or is failing to open that code for some reason.

If you're still interested in a solution please comment here again? (it was 21 days since you messaged... so probably you've either found a fix or moved on to other things by now)

**Comment by jorijnsmit** [comment]
Having same problem; `pygame.error: File is not a Windows BMP file`.

Fresh install of `pygame` using `pip install pygame` and SDL library using`brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf` from https://www.pygame.org/wiki/MacCompile. Although I have to say the instructions there are very unclear; there is too much going on there ("newest macOS" link to SO/Snow Leopard/Mountain Lion/Python2/Python3/build from source/non-Leopard only/etc.)

My configuration:
```
macOS 10.15.6
python 3.8.5
pygame 1.9.6
```

**Comment by jorijnsmit** [comment]
`pip install git+https://github.com/pygame/pygame.git` seems to have fixed it?
`pygame.image.get_extended()` previously returned `0`, now `1`. Might have been due to installing `Pillow` or other dependencies, don't have a good overview of what is required. A `requirements.txt` or just general list of dependencies would be nice to have.

**Comment by MyreMylar** [comment]
This is likely from using pygame 1.9.6 with a recent macOS. At some point macs were changed so that the SDL1 stuff pygame versions before pygame 2 was doing didn't work anymore and nobody is developing pygame 1 anymore because we are all working on pygame 2. 

This is a known ongoing issue with many (but not all) macs that will mostly vanish when there is a 'stable'/'final' version of pygame 2 released and it makes it's way through the internet. Right now we are up to version 10 of the pygame 2 release, it's a slow and steady process with pygame being dependent on a small pool of volunteers for development and in turn depending on parts of SDL2 that are not widely used - except by pygame. Plus of course, SDL development is itself dependent on a small pool of volunteers and serves projects other than pygame. 

On the plus side this has been the busiest year for pygame development in a while and pygame 2 has been used in many projects for the past two and half years despite its still-in-development state.

**Comment by jorijnsmit** [comment]
I can indeed confirm that `pip install pygame==2.0.0.dev10` solves this issue.
