### ISSUE TITLE
wrong color with 2d surfarray

### ISSUE THREAD

**Issue by BastiHz** [pygame/pygame#1563]
I'm on Linux Kubuntu 18.04 and Windows 10, pygame 2.0.0.dev6 (SDL 2.0.10, python 3.7.5). It also occurs with pygame 1.9.6.

I'm creating this issue because I first asked about this problem on reddit and user windspar [suggested that this might be a bug](https://www.reddit.com/r/pygame/comments/eqmer1/bug_in_pygamecolor_or_pygamesurfarray/fex4zfr/) .

The surfarray documentation states that I can specify colors as single integers for a 2d array. However, it does not say how the integer is calculated. Only that there is some colormap somewhere and some bit packing process (?) is involved:

> Every pixel is stored as a single integer value to represent the red, green, and blue colors. The 8-bit images use a value that looks into a colormap. Pixels with higher depth use a bit packing process to place three or four values into a single number.

After some experimenting I found out that I could use `int(pygame.Color())` to get this mysterious integer. But the conversion seems wrong. For example to get orange [255, 128, 0] I normally would write `int(pygame.Color([255, 128, 0]))`. But the surfarray becomes purple instead. The get an orange surfarray I have to write `int(pygame.Color([x, 255, 128, 0]))` with `x` being any int between 0 and 255.

Here's a small script to illustrate the problem.

```
import pygame
import numpy

window = pygame.display.set_mode((400, 400))

# color = pygame.Color(255, 128, 0)       # purple surface
# color = pygame.Color(255, 128, 0, 255)  # purple surface
color = pygame.Color(255, 255, 128, 0)    # orange surface

arr = numpy.full((400, 400), int(color))
pygame.surfarray.blit_array(window, arr)
pygame.display.flip()
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
```

**Related Docs**: https://www.pygame.org/docs/ref/surfarray.html

**Comment by BastiHz** [comment]
I just found a bug that may be the same or related: When using 2d arrays pygame.surfarray.blit_array() works as expected. But if I first want to create a surface and then blit that to the main window the color is wrong:

```
import pygame
import numpy

window = pygame.display.set_mode((400, 400))
color = pygame.Color(255, 255, 128, 0)
arr = numpy.full((400, 400), int(color))

# this works:
#pygame.surfarray.blit_array(window, arr)

# this does not:
surf = pygame.surfarray.make_surface(arr)
window.blit(surf, (0, 0))
print(surf.get_at((0, 0)))  # prints: (0, 0, 0, 255)

pygame.display.flip()
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
```

This problem does not occur when using 3d arrays.

**Comment by MightyJosip** [comment]
Thank you for your detailed bug report. I can confirm the bug is happening in current version. If you fill numpy array with int(pygame.Color(r, g, b, a)) the end result will always be color (g, b, a, 255). Possible fix would be to replace add division with 256 in line 464 of pixelcopy.c:
replace

*(imgrow + loopx) = (DST) * (SRC *)(datarow + stridex * loopx);

with

*(imgrow + loopx) = (DST) * (SRC *)(datarow + stridex * loopx) / 256;

With that I get correct color, but then some tests fail. Maybe the better solution would be to take other values in datarow (right now if you write color (red, green, blue, alpha) data in datarow list is [alpha, blue, green, red, alpha...] for Uint32 datatype or [alpha, blue, green, red, 0, 0, 0, 0, alpha...] for Uint64 (datatype depends if the red value is greater or less than 128)

**Comment by llindstrom** [comment]
This issue is not a bug. A **Color** type instance represents a generic color value similar to a tuple of four integers. It is an _unmapped_ pixel value. It differs from the actual raw memory representation of a pixel in a surface, or _mapped_ pixel value. The actual integer value of a mapped color depends on the type of surface, the computer hardware, and operating system. A 2d surfarray is an array of mapped pixel values, so is surface specific. The **Surface** type has the `map_rgb()` and `unmap_rgb()` methods to convert between a color and its representation within a surface pixel.

 Here is how this is used in the script above:
````
import pygame
import numpy

window = pygame.display.set_mode((400, 400))

# color = pygame.Color(255, 0, 128)       # purple surface
# color = pygame.Color(255, 0, 128, 255)  # purple surface
color = pygame.Color(255, 128, 0, 255)    # orange surface

arr = numpy.full((400, 400), window.map_rgb(color))
pygame.surfarray.blit_array(window, arr)
pygame.display.flip()
running = True
while running:
        for event in pygame.event.get():
                    if event.type == pygame.QUIT:
                                    running = False
````

This issue suggests the pygame documentation for Color and surfarray needs clarification. Also, that a Color can be directly converted to an integer is an undocumented feature that probably should not be possible, so is eligible for removal.

**Comment by BastiHz** [comment]
Ah, that clears it up, thank you. I did not know about `Surface.map_rgb()` and that it could be used for that. It is not mentioned in the surfarray documentation.

**Comment by llindstrom** [comment]
I will try to clarify it in the documents.

**Comment by llindstrom** [comment]
### Additions to Make to the Pygame Documentation

- **surfarray**: To the top level doc describe how 2d and 3d arrays differ in there relation surface pixels. Mention `Surface.map_rgb()` and `Surface.unmap_rgb()`.
- **pixelcopy**: To the top level doc describe role of 2d and 3d arrays. Make the description standalone from surfarray module.
- **Color**: In the top level doc explain `int(color_instance)` allows colors to be dict keys when Color itself is a mutable type. These integer keys are not mapped pixel values.
