### ISSUE TITLE
Using 'SDL_WINDOWID' does not embed pygame display correctly into another application

### ISSUE THREAD

**Issue by AleffCorrea** [pygame/pygame#1574]
Windows 10, pygame 2.0.0.dev6 (SDL 2.0.10, python 3.8.1). tkinter 8.6

What previously worked on the latest stable release of pygame (1.9.6) for embedding the pygame wrapped SDL render window into a Tkinter frame doesn't work on the prerelease version I'm using anymore. Instead of properly drawing into the frame with id set into the SDL_WINDOWID environment variable, it simply spawns another window instead.

```   root = tkinter.Tk()
    self.frame = tkinter.Frame(root, width=self.width, height=self.height)
    self.frame.grid(row=0, column=2)
    root.update()
(...)
    os.environ['SDL_WINDOWID'] = str(self.frame.winfo_id())
    if sys.platform == "win32":
      os.environ['SDL_VIDEODRIVER'] = 'windows'
    pygame.display.init()
    self.screen = pygame.display.set_mode(canvas_res)
```
**Related Docs**: https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode

**Comment by robertpfeiffer** [comment]
I'm pretty sure this is a SDL2 thing. SDL_WINDOWID is not part of SDL2 any more. We might try to make this work again, but maybe not with the old API.

**Comment by robertpfeiffer** [comment]
Functionality to do this used to exist in _sdl2, I'll link the relevant stuff for all the non-Discord people:

https://wiki.libsdl.org/SDL_GetWindowID
https://wiki.libsdl.org/SDL_GetWindowFromID
https://github.com/pygame/pygame/commit/45035cb136d85f95eae4fbc16da270aa8c72fd2f#diff-1b1808dc40ab95d48365c05261709336

**Comment by kntroh** [comment]
I'm having trouble migrating my application to pygame 2 because of this problem.
Is it possible to use `SDL_CreateWindowFrom`?
https://wiki.libsdl.org/SDL_CreateWindowFrom

**Comment by kntroh** [comment]
I tried SDL_CreateWindowFrom, and it seems to work well.
But, I don't know the right rule to convert a string to a pointer in pygame.
display.c:
```C
    char *window_handle = SDL_getenv("SDL_WINDOWID");
    (snip)
                /*open window*/
                if (window_handle) {
                    win = SDL_CreateWindowFrom(atoll(window_handle));
                }
                else {
                    win = SDL_CreateWindow(title, x, y, w_1, h_1, sdl_flags);
                }
```

**Comment by kntroh** [comment]
https://github.com/kntroh/pygame/commit/6d78c65d989960e5506a1d3aefff42d427906819
I've been working on it, but I'm stuck. I have the following problems:
 1. It works when I run the CPython interpreter with interactive mode, but it fails when I try to run automated test.
 2. It works when using tkinter with GTK, but dumps core when using wxPython (On Windows, both work).
 3.  It is untested on macOS.

It seems to require a detailed knowledge of GUI toolkits and the interpreter to solve these problems. I don't have that knowledge.

**Comment by zagbapu** [comment]
Still having this issue, replacing os.environ['SDL_WINDOWID'] with os.environ['SDL_CreateWindowFrom'] did not work for me.

**Comment by daniel-koudouna** [comment]
Has there been any progress on this? I'm trying to update a project from pygame 1 to pygame 2, and I'm having the same issue embedding into a tk frame. Alternatively, how can I use SDL 1 with the latest version to restore this functionality?

**Comment by Starbuck5** [comment]
@daniel-koudouna There has not been any progress on this.

You can use SDL 1 with pygame 2.0.3 or below, by building it on your own system with an `-sdl1` flag IIRC. But then you have to build it yourself, which can be challenging on Windows especially.

We could support this in the future with [SDL_CreateWindowFrom](https://wiki.libsdl.org/SDL_CreateWindowFrom), probably.

I spent a couple minutes trying to patch this into _sdl2.Window

video.pyx:
```
    @classmethod
    def from_foreign_window(cls, other):
        cdef Window self = cls.__new__(cls)
        os.environ['SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT'] = str(hex(other))
        cdef int data = other
        cdef SDL_Window* window = SDL_CreateWindowFrom(&data)
        self._win = window
        self._is_borrowed = 0
        SDL_SetWindowData(window, "pg_window", <PyObject*>self)
        return self
```

But it segfaults, and I don't have the time to dig deeper into it right now.

Also, since there isn't a minimal working example on this thread yet, I had to make one, so I'll post that as well.
```py
import pygame
import tkinter as tk
from tkinter import *
import os

root = tk.Tk()
embed = tk.Frame(root, width = 500, height = 500) #creates embed frame for pygame window
embed.pack(side = LEFT) #packs window to the left
buttonwin = tk.Frame(root, width = 75, height = 500)
buttonwin.pack(side = LEFT)
os.environ['SDL_WINDOWID'] = str(embed.winfo_id())
os.environ['SDL_VIDEODRIVER'] = 'windib'
screen = pygame.display.set_mode((500,500))
screen.fill(pygame.Color(255,255,0))
pygame.display.init()
pygame.display.update()

def draw():
    pygame.draw.circle(screen, (0,0,0), (250,250), 125)
    pygame.display.update()
    root.update()

button1 = Button(buttonwin,text = 'Draw',  command=draw)
button1.pack(side=LEFT)

while True:
    pygame.display.update()
    root.update()      

```

**Comment by Rabbid76** [comment]
One of the above solutions with [`SDL_CreateWindowFrom`](https://wiki.libsdl.org/SDL_CreateWindowFrom) works fine for me. I have added the following code to the "src_c/display.c" file (line 1099):

<s>`win = SDL_CreateWindow(title, x, y, w_1, h_1, sdl_flags);`</s>
```c
const char *window_handle = SDL_getenv("SDL_WINDOWID");
win = window_handle
    ? SDL_CreateWindowFrom((const void*)atoll(window_handle))
    : SDL_CreateWindow(title, x, y, w_1, h_1, sdl_flags);
```
I've created the following minimal example:

```py
import tkinter as tk
import pygame
import os, random

root = tk.Tk()
button_win = tk.Frame(root, width = 500, height = 25)
button_win.pack(side = tk.TOP)
embed_pygame = tk.Frame(root, width = 500, height = 500)
embed_pygame.pack(side = tk.TOP)

os.environ['SDL_WINDOWID'] = str(embed_pygame.winfo_id())
os.environ['SDL_VIDEODRIVER'] = 'windib'
pygame.display.init()
screen = pygame.display.set_mode()

def random_color():
    global circle_color
    circle_color = pygame.Color(0)
    circle_color.hsla = (random.randrange(360), 100, 50, 100)
random_color() 
color_button = tk.Button(button_win, text = 'random color',  command = random_color)
color_button.pack(side=tk.LEFT)

def update():
    screen.fill((255, 255, 255))
    pygame.draw.circle(screen, circle_color, (250, 250), 125)
    pygame.display.flip()
    root.update()  
    root.after(100, update)

update()
tk.mainloop()
```

Since that hasn't worked so far, can't it be included in pygame at least experimentally?

**Comment by Starbuck5** [comment]
@Rabbid76 Thanks for this, it's cool. I haven't tested it yet.

It takes a lot of bravery to go into the display.set_mode code (since it's so complicated).

Perhaps rather than supporting it the old way, it could be a new API directly in the new _sdl2.Window class.  

If you haven't heard about the Window class, it's going to be more fully featured than pygame.display, because it will support multiple active windows at a time (Made possible by SDL2). Some other cool things with it is that you can set the window opacity, and you can position the window on the screen programmatically. It has skeleton docs here: https://www.pygame.org/docs/ref/sdl2_video.html?highlight=sdl2_video#pygame._sdl2.video.Window. (And it works right now, there's an example called video.py in /examples/)

**Comment by Rabbid76** [comment]
@Starbuck5 For most people, this won't be an option. The `video` module behaves completely differently than the `display` module. The modules `draw` and` sprite` will not work as before. You cannot draw directly draw on the display surface. You cannot draw directly on the display surface. This is a completely new library, but it is no longer "pygame".

**Comment by Starbuck5** [comment]
@Rabbid76 don't worry, the pygame devs haven't gone crazy 😅. You can still do software rendering using the `Window` class. (In a more practical way after https://github.com/pygame/pygame/pull/2937 is merged). It exists because the `pygame.display` api is designed pretty clearly for a single window.

Everything else in there is for hardware accelerated rendering. Which I would like to make a bit more similar to the existing surface API before it's released. Just to be clear the hardware rendering API from SDL is completely different than the windowing API. The fact that these two experimental categories are in the same module on our end has confused people.

But I guess I'm just thinking aloud.

For now I guess it would be better to put your patch in display.c, and add the new `WindowFrom` API to _sdl2.Window later. (So someone could embed pygame in multiple tkinter windows, I guess)

**Comment by Rabbid76** [comment]
@Starbuck5 Thank you for the answer. I should mention that I haven't extensively tested my suggestion. It works on my windows system. That's it.

**Comment by Rabbid76** [comment]
I finally worked out the `_sdl2.Window` approach on my system. I added the following code to "/src_c/cython/pygame/_sdl2/video.pyx":

```pyx
import os
```

```pyx
cdef extern from "SDL.h" nogil:
    # [...]
    SDL_Window * SDL_CreateWindowFrom(const void *data)
```

```pyx
cdef class Window:
    # [...]
    
    @classmethod
    def from_foreign_window(cls, other):
        cdef Window self = cls.__new__(cls)
        os.environ['SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT'] = str(hex(other))
        cdef long long data = other
        cdef void* data_ptr = <void*>data
        cdef SDL_Window* window = SDL_CreateWindowFrom(data_ptr)
        self._win = window
        self._is_borrowed = 0
        SDL_SetWindowData(window, "pg_window", <PyObject*>self)
        return self
```

The line `os.environ['SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT'] = str(hex (other))` is not needed in my case, although the documentation for [`SDL_CreateWindowFrom`](https://wiki.libsdl.org/SDL_CreateWindowFrom) mentions it.  
I've only tested it on my Windows system with the following minimal example:

```py
import tkinter as tk
import pygame
import pygame._sdl2
import random

root = tk.Tk()
button_win = tk.Frame(root, width = 500, height = 25)
button_win.pack(side = tk.TOP)
embed_pygame = tk.Frame(root, width = 500, height = 500)
embed_pygame.pack(side = tk.TOP)

pygame.display.init()
win = pygame._sdl2.Window.from_foreign_window(embed_pygame.winfo_id())
renderer = pygame._sdl2.Renderer(win)

def random_color():
    global rect_color
    rect_color = pygame.Color(0)
    rect_color.hsla = (random.randrange(360), 100, 50, 100)
random_color() 
color_button = tk.Button(button_win, text = 'random color',  command = random_color)
color_button.pack(side=tk.LEFT)

def update():
    renderer.draw_color = (255, 255, 255, 255)
    renderer.clear()
    renderer.draw_color = rect_color
    renderer.fill_rect((150, 150, 200, 200))
    renderer.present()
    root.update()  
    root.after(100, update)

update()
tk.mainloop()
```

**Comment by Starbuck5** [comment]
@Rabbid76 I'm super impressed by these patches, these places are very deep in Pygame. And definitely not easy things to contribute to.

In terms of pull requests now, you could make pull requests off your current patches. I think it would be best to treat the display.c one and the Window one separately. So that for instance, the display.c one can be merged before the Window one is approved. We can also get testers on Linux and Mac and see what happens for them. Also there would be some loose ends to clean up, like docs and types, of course.

**Comment by Rabbid76** [comment]
@Starbuck5 
[class method "from_foreign_window" added to class "Window" #2982](https://github.com/pygame/pygame/pull/2982)
["SDL_CreateWindowFrom" in "display" module #2981](https://github.com/pygame/pygame/pull/2981)

**Comment by 46cv8** [comment]
Hey guys, I really don't know where to ask this so I appologize for asking here but I'm having a similar albeit slightly different issue. I want to get the Default SDL Window address out of pygame so that I can resize the window using pysdl2. Unfortunately I can't find anyway to get it out... It's used all throughout the code base via "pg_GetDefaultWindow". But I can't find any place that allows me to obtain the address of the object in python. The closest I found was pygame.display.get_wm_info()["display"] but this is the x11 window object and not the SDL window object. I need a opengl context with vsync, which means as far as I can tell (unless I'm mistaken) using pygame._sdl2.window isn't a simple option, without rewriting a lot of code in "display.set_mode" which sets up opengl and vsync. Any tips would be appreciated, I apologize for asking on this ticket, but it seems like people with knowledge in this area are commenting here.

**Comment by Rabbid76** [comment]
What is the status of this issue? There are merge requests, but nothing seems to have happened for a while.

**Comment by illume** [comment]
There's a SDL_WINDOWID fix merged now. Thanks @Rabbid76
