### ISSUE TITLE
AttributeError: partially initialized module 'pygame' has no attribute 'init' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Zacky2456** [pygame/pygame#1592]
So after a long time I decided to return to Pygame but immediately after attempting a code run it said: `"AttributeError: partially initialized module 'pygame' has no attribute 'init' (most likely due to a circular import)."` anyone has any idea whats wrong? also my file is not named "pygame.py".

I Have:
-Reinstalled python
-reinstalled pygame
-reset the path variables
-try updating pygame with pip

**Comment by jmliu1983** [comment]
Same issue.
OS: windows 10, 
both the following configuraton has this issue
Anaconda3(Python 3.6.2)
IDLE(Python 3.6.4)
When run "pygame.init()"in the interactive line, it works.
But when run a .py file,  following error happens:
`Traceback (most recent call last):
  File "C:\Users\84593\Desktop\pygame.py", line 1, in <module>
    import pygame
  File "C:\Users\84593\Desktop\pygame.py", line 3, in <module>
    pygame.init()
AttributeError: module 'pygame' has no attribute 'init'`

**Comment by galexandreg** [comment]
> Traceback (most recent call last): File "C:\Users\84593\Desktop\pygame.py", line 1, in <module> import pygame File "C:\Users\84593\Desktop\pygame.py", line 3, in <module> pygame.init() AttributeError: module 'pygame' has no attribute 'init'

The problem is simply that you can't use the module name (pygame) as your file name (pygame.py). Simply change it to something else and everything should work 😄

**Comment by galexandreg** [comment]
>  also my file is not named "pygame.py"

I just saw that... In your case ( @Zacky2456 ), if you are not using a file named "pygame.py", it's really hard to say without more informations about the version of python you are using, your operating system and the code you are trying to run.

**Comment by MyreMylar** [comment]
Closing this for now as we've had no response from @Zacky2456, it is not a general problem and we have no detail to investigate with.

**Comment by Zacky2456** [comment]
well, it was fixed way back, turns out that I just had a file with two
lines of code, named pygame.py which my python saw has the actually pygame,
i just deleted that and its all fine now

**Comment by Kinfe123** [comment]
Yep..If you give the file name with in pygame.py ..You could see the attribute error..

**Comment by ZackyGameDev** [comment]
the file was actually in python's root folder that's why i couldn't find it.

**Comment by zw311i** [comment]
@galexandreg can  you please give an example of changing the pygame.py as suggesting please

**Comment by galexandreg** [comment]
> @galexandreg can you please give an example of changing the pygame.py as suggesting please

Sure.
By default, when you import a module like pygame (`import pygame`), python will search for it in different places. But if you have a file named pygame.py in the same directory as the script you are running (or if the script itself is named pygame.py), python will load this file instead of pygame. That's why you can't use pygame in a script file named pygame.py. This is the same with all other python modules.

So If your pygame program is only in one file, don't name it pygame.py. If you have multiple files or modules in your program, make sure that no file is named pygame.py in the same directory, even if you don't use it.

You could get the same problem if you have a file named pygame.py in other places: https://docs.python.org/3/tutorial/modules.html?highlight=import#the-module-search-path

**Comment by memocp** [comment]
also if there is another file you made that's called pygame.py it will not work even if the file your opening is somthing else....
