### ISSUE TITLE
no graphics rendered in osx catalina

### ISSUE THREAD

**Issue by shorinji** [pygame/pygame#1594]
I have installed pygame using the pip-method (python3 -m pip install -U pygame --user)

Running the intro program with the bouncing ball. The window shows up in the right size, but it is all dark grey and nothing is rendered inside it. 
<img width="346" alt="Skärmavbild 2020-03-05 kl  13 27 07" src="https://user-images.githubusercontent.com/27412/75981569-0f927680-5ee5-11ea-9ac2-e544425e8337.png">

I have tried various display flags, but same result. pygame.display.get_init() returns True and no of the other info methods can provide me with anything indicating there is a problem.

Python version: 3.7.6
Pygame version: 1.6.9
OS: OSX Catalina 10.15.3

Be happy to submit any more info you might need!

**Comment by galexandreg** [comment]
It looks like issue #555 .

Pygame 1.6.9 isn't really compatible with the latest mac os versions. The best thing for you would probably be to try Pygame2. It's still in development, but I think it's the best version to use on mac os.

`python3 -m pip install pygame --user --pre`

The --pre option will tell pip to install the pre-release versions (Pygame 2.0.0.dev6 is the latest)
This should solve the problem.

If you can't or don't want to use Pygame2, take a look at the issue #555. It seems you will need to install python with the official installer instead of homebrew.

**Comment by shorinji** [comment]
Thanks alot for the quick reply and solution!
