### ISSUE TITLE
environ["SDL_VIDEODRIVER"] = "directx" can cause crash with pygame.display.set_mode

### ISSUE THREAD

**Issue by cmcmarrow** [pygame/pygame#1609]
When  I call `pygame.display.set_mode((window_w, window_h), RESIZABLE, 32)` for the second time it crash. I'm on win 10. But this only happends when `environ["SDL_VIDEODRIVER"] = "directx"`. 

`pygame.error: DDraw created surface with wrong pitch`

Any idea of a work around?  I would like to have directx

**Comment by cmcmarrow** [comment]
pygame==1.9.6

**Comment by MyreMylar** [comment]
I think this is unlikely to get fixed because direct draw is unsupported now as driver for SDL2. See this page:

https://wiki.libsdl.org/FAQUsingSDL

Is there a specific reason you need to use the direct draw driver and pygame 1? Just to work out if there is a different way to help with your ultimate goal.

**Comment by cmcmarrow** [comment]
I prefer directx because it burns less CPU. But I rather see pygame 2.0 come out. So I’ll see what pygame with openGL will do for me.
