### ISSUE TITLE
pygame.error: Surfaces must not be locked during blit

### ISSUE THREAD

**Issue by Coder-Osman** [pygame/pygame#1614]
When I run my threading + pygame code, sometime it will come out with a bug : pygame.error: Surfaces must not be locked during blit, but sometime it won't, I don't use PixelArray, maybe it's the problem of two different thread using the same surface? I don't know. 

`Traceback (most recent call last):
   line 1019, in <module>
    main()
 line 963, in main
    animate()
 line 815, in animate
    screen.blit(i.image, i.rect)
pygame.error: Surfaces must not be locked during blit

Process finished with exit code 1`

**Comment by robertpfeiffer** [comment]
Which versions of Python, PyGame, and SDL are you on?

**Comment by robertpfeiffer** [comment]
I don't think it can happen in more recent versions of PyGame, as we no longer release the GIL during blitting, probably for exactly this reason.

**Comment by Coder-Osman** [comment]
@robertpfeiffer 
Pygame : 1.9.6 
Python : 3.7.1 
SDL : I don't know

**Comment by robertpfeiffer** [comment]
Thanks! This is super interesting.

You're not *supposed* to do multi-threaded blitting in pygame, because it provides next to no speed-up with the GIL, but this might point towards a bug we need to fix. We didn't release the GIL in pygame 1.9.6 either, so surface.blit should have always run single-threaded without any data races!

Can you reproduce the bug semi-reliably? Does it always happen at the same line?

If so, can you install the new developer preview if pygame with `pip3 install pygame==2.0.0-dev6` and tell us if it happens there too?

Or alternatively, can you post more code or a link to a repo if it's open source?

**Comment by Coder-Osman** [comment]
@robertpfeiffer Well, I don't do multithread blitting, I blit in only one thread, but I do multithreading.
And when I changed my pygame into pygame=2.0.0-dev6 the bug looks like : 

`Traceback (most recent call last):
  File  line 1050, in <module>
    main()
  File  line 994, in main
    animate()
  File line 838, in animate
    pygame.display.flip()
pygame.error: Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface`

And the pygame.error: Surfaces must not be locked during blit bug appears mostly when there are too many missiles on the screen, and it happened for a long time with erratic intervals, and always in the same blitting line, and I put my code on github : https://github.com/Coder-Osman/Missiles.
At last, thank you for offer solutions for my bug.

**Comment by Coder-Osman** [comment]
@robertpfeiffer And also, even if I use pygame==2.0.0-dev6, the `pygame.error: Surfaces must not be locked` during blit still exist.

**Comment by illume** [comment]
Only the main thread (the start up one) should blit to the display. If you don't do this, then things may act weirdly on different platforms (and other platforms may work).

Note, you can use get_locked(), but even so you'd be racing. You could also use a lock, event or a semaphore, but they are not very performant in cpython.

It's best to structure your program so that blit calls are all done in the main thread. pygame and python don't work well having a separate thread for each sprite. See the aliens and chimp examples for how to do pygame.sprite based games without threads.

I don't think there's anything we can fix. Please feel free to ask on reddit/stackoverflow or our discord channel for more help.
