### ISSUE TITLE
Add unit test: threads.tmap()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1768]
This function needs a unit test finishing.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/threads_test.py#L131-L143
**Docs:** None.
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_py/threads/__init__.py#L238-L310

**Comment by cruxicheiros** [comment]
Hi, this is my first issue on this project so please let me know if I do something wrong in terms of etiquette.

I decided to look at this one because I thought I could see a lot of untested functionality in tmap and had an idea of how to go about testing it. I started by writing a unit test to see that the `stop_on_error` flag worked as expected when set to `False`. However, it seems like using it causes an issue in the function `tmap` where it expects to be able to access a `result` property on the FuncResult objects that doesn't exist when the function called an exception.

**The modification**
https://github.com/pygame/pygame/compare/master...cruxicheiros:update-test-tmap?expand=1

**The traceback**
```
Error
Traceback (most recent call last):
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/clark/Dev/pygame/pygame/test/threads_test.py", line 136, in test_tmap
    tmapped2 = list(tmap(always_excepts, data2, stop_on_error=False))
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/site-packages/pygame/threads/__init__.py", line 308, in <lambda>
    return map(lambda x:x.result, results)
AttributeError: 'FuncResult' object has no attribute 'result'


Assertion failed

Assertion failed


Ran 1 test in 0.036s

FAILED (errors=1)
```

**Proposals for fixing it**
Here are some options:

- If the FuncResult has no result, add a None to the final list in its place
-- Seems the most logical to me
- If the FuncResult has no result, don't add anything to the list
-- Would break expectations of the map function producing the same sized list as its input

Any suggestions for next moves? Thanks.

**Comment by MightyJosip** [comment]
Thanks for your effort. You can freely make pull request (it will be easier to compare) and there we can see what can be done.
