### ISSUE TITLE
Add unit test: surface.get_losses()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1805]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L1028-L1040
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_losses
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L2747-L2894

**Comment by Reminisque** [comment]
May I work on this issue?

**Comment by MyreMylar** [comment]
Absolutely.

**Comment by Reminisque** [comment]
I've looked through the documentation for the function and the associated SDL objects such as `SDL_Surface` and `SDL_PixelFormat`, but I'm not entirely clear how everything works. 

From what I could understand of the docs on masks, shifts, and losses the values in mask are for getting the bits for a specific color component (R or G or B or A) from a pixel's color value with length equal to the depth passed to the `pygame.Surface` object it belongs to, the values in shifts are the number of bits to the right of the corresponding component, and losses is the number of left shifts needed to make the component 8-bit after using the mask to isolate the bits and shifts to bring those bits all the way to the right. Also each of these are already set when creating a new instance of `pygame.Surface` depending on the depth set. 

I noticed that after playing around with the `set_masks` and `set_shifts` the losses do not change. What happens if someone changes the mask and shift values for one of the color components so that it ends up having a length larger than 8 bits after being isolated, shifted to the right, and shifted to the left? I also found that for an 8-bit depth, the masks show that the number of bits assigned is in a 2-3-2-0 configuration which only adds up to 7 bits and only 2 bits are used for red. I only just started learning more about color depth since starting this issue, so I am not sure if this is intentional since I read on wikipedia that its normally 3-3-2 for RGB.

Are there any other functions for `pygame.Surface` that I would have to consider beisdes those metnioned above? I'm thinking I might need some cases regarding alpha, but would it only be through me setting the alpha masks when creating the surface and not through `set_alpha`? It didn't change masks, shifts, or losses after setting it with the set function.

I am currently not clear on all the test cases I need to cover. For the different color depths is it same to assume that I will get the same losses provided to me all the time? For example I got (3, 3, 3, 0) for 15-bit where each color component except alpha is 5 bits.
