### ISSUE TITLE
setup.py lint

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1896]
How about we have a command to run all the lint tools?

- black
- pylint
- clang-format

**Comment by MyreMylar** [comment]
I think this is a good idea - once we have the number of linter errors down to a mangeable number (or preferably zero). I suspect if we turned it on now it would be a terrifying flood of hundreds, at least I'm sure pylint would do that. I think black auto formats, and I have no idea what clang-format does.

 Do all the linters agree with each other or will they get into linter fights? :O

**Comment by illume** [comment]
> once we have the number of linter errors down to a mangeable number (or preferably zero). I suspect if we turned it on now it would be a terrifying flood of hundreds, at least I'm sure pylint would do that

We could start off with a list of lint-clean files that `setup.py lint` can check. Adding more files as they are cleaned.

>  I think black auto formats, and I have no idea what clang-format does.

Yeah, clang-format auto formats C/C++ similar to black for python.

I was thinking of some sort of pre-commit command - similar to a `make check`. To make it easier to run all the different things. Probably should add `setup.py docs` to this to make sure header files are generated. I think you can chain distutils commands so `setup.py docs lint test` could perhaps work.

> Do all the linters agree with each other or will they get into linter fights? :O
black and pylint agree at least

**Comment by Pierre-Sassoulas** [comment]
Hello, 

Can I be assigned to this ? I would add a `pre-commit` configuration, like the one for pylint here:
https://github.com/PyCQA/pylint/blob/master/.pre-commit-config.yaml

Then with
```
pip3 install pre-commit
pre-commit install
```
pre-commit hooks are added to your local git repository and are executed on `git commit`. I could also update the travis job.

**Comment by Pierre-Sassoulas** [comment]
@MyreMylar there is some configuration to do so the linter do not enter a linter war. Main thing to consider is the number of character per line. (Look like yours is 79, right ?)

**Comment by illume** [comment]
Hello @Pierre-Sassoulas,

thanks for starting on this.  I don't think this issue has had enough discussion for implementation. Is it possible you could detail your thoughts on some of the choices you've made?


A few notes, and some background...

This issue was about a `setup.py lint` command using the tools we had selected (black, pylint, clang-format). The main benefit is that we build with other commands through the setup.py.

It would be good to have no new files added to the root of the repo. If we can remove files, great! We have a setup.cfg and a builconfig/ folder for config. The goal is to optimize for new developers and a config file soup is not wanted. There is already a tox setup, but I'm not sure that's a good idea. pygame is being used as a code base for teaching.

We need discussion and a consensus agreement made with other pygame developers first, and a more detailed plan for other tools. Do we create issues for each file, or area of file? It can be a good learning opportunity, so maybe we should leave some issues for 'good first issues'?

Small PRs with incremental changes are best. Lint fixes should be kept to a single file or module at most in a single commit. Otherwise it can be very hard to read when searching through history. Lint tools are great at finding code smells, so it's good to take more time to consider the area around problematic code.

Applying autofixers to non python/c files can be dangerous in the pygame codebase. Especially to files types that they know nothing about, and where a space at the end of a line can actually mean something.

A pre-commit hook should probably come last. Not sure if it's a good idea yet. It would be good if it can be done without requiring a pip install. A pre-commit hook can possibly create too much friction for new developers, and even existing developers. So the 'check' commands need to be very good before using it as a pre-commit hook.

**Comment by Pierre-Sassoulas** [comment]
Thank you for the detailed context ! 

Regarding black, it would change a lot of code in pygame. (Two files even reveal a bug in black), so I thought doing it at once would greatly reduce diffs during future merge requests. There is also a way to remove formatting commit from git blame output (https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt)

For isort, its because it can sort import automatically and this is what is used by pylint to check the order (but pylint do not autofix), it can go well with black.

Mypy is great for checking type hints, which pylint does not and will never do (because mypy exists).

Flake8 is also great and have a lot less noise or false positive than pylint. I think it's a good first step before pylint

Autoflake remove unused import and variable automatically which is great, but it would breaks `src_py/locals.py` so it needs some configuration first.

Regarding the setup.py I did not manage to launch it yet, but do you want the `setup.py lint` to install linters ? Or is it expected that pygame's devs install it themselves ?

**Comment by illume** [comment]
Some more random thoughts...


> Regarding the setup.py I did not manage to launch it yet, but do you want the setup.py lint to install linters ? Or is it expected that pygame's devs install it themselves ?

It could install linters automatically... that could be nice. It should probably ask the user first though, since it's potentially destructive to do.

Instead, we could also just have section in our developer guide with install instructions. The lint command could print this link if a tool is missing.


# pre-commit
I'm not sure about '[pre-commit](https://pre-commit.com/)' the tool.

- it is a python packaged tool, which is nice (pip installable and packaged in quite a few package managers).
- The root config file is a problem for the pygame repo. It doesn't look like it's possible to move the pre-commit configuration to the setup.cfg file or the buildconfig/ folder.
- it works with multiple language tools.
- It's a package manager. It's unclear to me where and how it installs things. I imagine other developers would be concerned with this too.
- Downloading things from repos without versioning always worries me, because reproducing is harder.


# groups of people and workflows to consider

Some main groups of developers.
- people new to python and programming
- people developing python only, but fluent in python world tools.
- people from other language backgrounds mainly C/C++/etc on different platforms, maybe a bit of python knowledge.
- C and python programmers, who are regular pygame contributors.
- we have contributors on most systems. Mostly on Windows and Linux(every distro there is) are more common, but some very esoteric ones including RiscOS, people on Android devices, and FreeBSD/OpenBSD and weird embedded systems.
- some people like installing everything with a certain package manager if possible, from Debian to homebrew and avoid tools like pip and virtualenv.

## some potential

- Doing a python change, shouldn't require installing C/C++/other lint tools.
- Doing a C change, shouldn't require installing python tools necessarily.
- Perhaps... If there are no C changes, it shouldn't run C linters.
- Perhaps... If there are no python changes, it shouldn't run python linters.


# Standard work flows?

It would be nice to support standard python development workflows if possible.
Someone coming into pygame from other python/C projects should feel comfy.

There's many common approaches to python package development at the moment unfortunately.
Maybe supporting setuptools, and tox is ok.


## setup.py test running linters?

`setup.py lint` is non-standard.
`setup.py test` is semi-common. Could it also run linters?

How about `setup.py build` running linters?


## tox?

How does [tox](https://tox.readthedocs.io/en/latest/) fit into all this?
Some python projects use tox for linting too, but it's not ubiquitos.

Do we support tox at all? Do we include the linters in our tox config?
It does support testing on multiple python environments with one command.

For newbies, it's just a weirdly named extra tool.


## setup.py develop and requirements.dev.txt

How do we specify development requirements? Especially for linting?

We have an open issue with [setup.py develop](https://github.com/pygame/pygame/issues/2057) being broken for pygame (I guess it still is). I'm not sure setuptools supports `develop` for extensions.


# autoformatters and fixers?

When should these be run? As a separate command, or before or during running of the lint command?

**Comment by Pierre-Sassoulas** [comment]
Regarding pre-commit installation:
- python's tool are installed in a virtualenv specific to pre-commit (do not affect the user installation at all and is cross-platform)
- some tool need to be installed system wide to work (clang-format because it's not a python tool, and pylint because it needs to be able to import other libs, which does not work well with pre-commit strict isolation)

So it would be possible to install tools automatically for all platform for some python tools, but not for clang-format and pylint. I think telling the user to install it themselves would be more reasonable.

It is possible to create our own pre-commit configuration in order to not depend on something online. I suppose the `pyproject.toml` would be the place most suited for this in order to have a single configuration file, but I never used it myself, I don't know if all the tools are ready to have their option there yet.

Tox can propose multiple jobs, `tox -e lint` could define the requirements it needs to run, for example. I think this is more intuitive than `setup.py lint` too.

> When should these be run? 

> Doing a python change, shouldn't require installing C/C++/other lint tools.

pre-commit run them on each `git commit` (as a pre-commit hook) on the staged file and them only, and run tools only if their target files were modified (for example pylint will run only on the python files that were staged with `git add`, only if there are some). I think a continuous integration check is necessary because installing pre-commit  locally is not enforceable

**Comment by illume** [comment]
Sorry for taking so long to get back to this.

> I think telling the user to install it themselves would be more reasonable.

Indeed. 

One problem can be different versions of lint/formatting tools doing things slightly differently.
We already have this problem with sphinx and cython, where different versions give different results.

If a clang-tidy, pylint, black or whatever is not there... it would be better to not fail. This way newbies and casual hackers will not be held up trying to figure out how to install things.


> It is possible to create our own pre-commit configuration in order to not depend on something online. 

Good point.

One reason I was hesitant of pre-commit is the extra config file (well extra two). So I asked about using a separate folder or config in setup.cfg here https://github.com/pre-commit/pre-commit/issues/1733 The issue was closed immediately, so I think setup.cfg is out... but `--config` was mentioned. So, I guess a wrapper or a fork could be made that would look at our config file location. I didn't look into if environment variables are supported for --config too.

But hey... we'll be removing a .travis.yml file soon. So there's a spot open ;)

**Comment by Pierre-Sassoulas** [comment]
I made some tests, we can hack the `.travis.yml` in conjunction to `pre-commit install --config .travis.yml` (unexpected arguments are ignored). But I think it actually defeat the purpose, maybe more files with simpler thing inside it are actually more beginner friendly ? The current setup.py is just one file but I would not consider it a resource to learn about python packaging for a beginner :)

**Comment by Pierre-Sassoulas** [comment]
I upgraded [the merge request](https://github.com/pygame/pygame/pull/2285) with a simple lint function in setup.py and the tools that are possible to add in the setup.cfg (isort, black, clang-format, pylint).  We can't add flake8 because they do not support setup.cfg. I did not apply the autofix of the linters yet in order for the MR to stay readable.
