### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by petike779** [pygame/pygame#1948]
Hi all
I am playing around with this nice project:
AmrMohamed-95/radar-simulation
Using an ultrasonic sensor and a servo to plot objects around.

I solved the cv2 and ALSA errors on my Pi4 (I had my sound card turned off with another project)
Now my problem is that program starts, doing 0-180 degrees rotation, turning back and around half way stops and exits the program. I see that on the scope is drawed what is sensed but program exits with this message:
dictionary changed size during iteration
Some advice please?
Thank you

**Comment by MyreMylar** [comment]
This isn't a pygame issue.

The problem is the code you are using deletes an item from the dictionary while it is looping through it. You can see the error here:

https://github.com/AmrMohamed-95/radar-simulation/blob/1ec326db3e233b712ab3add8855244e2d78bc0e0/src/display.py#L78-L106

the `del` on the last line.

You could instead store the names of the objects to delete and remove them from the dictionary later.
