### ISSUE TITLE
Test updating sprite.py to use OrderedDict instead of regular dict 

### ISSUE THREAD

**Issue by YariKartoshe4ka** [pygame/pygame#1951]
For testing, i wrote some code:
```python
import pygame

class Sprite(pygame.sprite.Sprite):
    def __init__(self, id):
        super(Sprite, self).__init__()
        self.id = id

group = pygame.sprite.Group()

group.add(Sprite(1))
group.add(Sprite(2))
group.add(Sprite(3))

for sprite in group.sprites():
    print('{0} | {1}'.format(sprite.id, sprite))
```
If python 3 runs this code, we will see:
```
1 | <Sprite sprite(in 1 groups)>
2 | <Sprite sprite(in 1 groups)>
3 | <Sprite sprite(in 1 groups)>
```
Which means that the sprites were added in order, but if this code run python 2, we'll see a different
```
2 | <Sprite sprite(in 1 groups)>
1 | <Sprite sprite(in 1 groups)>
3 | <Sprite sprite(in 1 groups)>
```
Why is this happening, and can it be fixed?
Python-3.6.9 | Python-2.7.17
Pygame 2.0.0-dev10

----------------------------------

TODO

- [ ] see if unit tests run changing the `self.spritedict = {}` and other parts inside src_py/sprite.py works.
- [ ] benchmark results from examples/testsprite.py (with different options... see source)
- [ ] run a few games that use sprite to see if there are breakages.
- [ ] consider only importing collections.OrderedDict for cpython 2.7.

**Comment by MightyJosip** [comment]
This is because sprites are stored in dictionary so I can't guarantee the order (https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/src_py/sprite.py#L301). You can also see this in docs (https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.Group). I don't think anything can be done with it, but I will leave this open for now in case someone else wants to share thoughts about it

**Comment by MyreMylar** [comment]
Specifically you will only notice this difference when using python 3.7+ as that was when python changed the basic dictionary to behave like an OrderedDict. See:

https://docs.python.org/3/library/collections.html#ordereddict-objects

It looks like OrderedDict's only exist from 3.1 onwards so if you want to keep supporting python 2 you can't rely on the order of objects in a dictionary/dictionary-like in your code.

I suppose we could consider (when pygame drops python 2 support) changing all Dictionaries to be OrderedDicts to make them consistent in older versions of Python 3; but it looks like OrderedDicts have other performance impacting differences from the standard dict as well.

Still when Python 4 has been out for a decade and we can drop python 3 support I suspect ordering in dictionaries will be a standard feature and we can revisit this.

**Comment by illume** [comment]
Reopening because OrderedDicts are in python 2.7, so let's investigate this a bit more?

Some research...

- collections.OrderedDict is new in python 2.7 and python 3.1 (see https://docs.python.org/2/library/collections.html the latest python docs are wrong, and the 2.7 docs don't mention others).
- we don't support python 3.0
- pypy's python 2 and python 3.x implementations have ordering by default on dicts.
- people distributing apps can come across python 2, or choose it for compatibility or speed.
- In some ways Groups are most like sets, but sets are not ordered in python unfortunately.

The main benefit would be for python 2.7, so for me it's less of a priority.

I guess we just need to test if it makes any negative impact changing to ordered dict?

- [ ] see if unit tests run changing the `self.spritedict = {}`.
- [ ] benchmark results from examples/testsprite.py (with different options... see source)
- [ ] run a few games that use sprite to see if there are breakages.
- [ ] consider only importing collections.OrderedDict for cpython 2.7.

**Comment by YariKartoshe4ka** [comment]
I wrote [some test game](https://github.com/YariKartoshe4ka/issue_1951). If you run it on python3, and press play button, everything will be ok, but if you run it on python2, asteroid`s generator will be crashed.

**Comment by illume** [comment]
There was some benchmarking and discussion in https://github.com/pygame/pygame/pull/2336

The performance hit was too much to enable it by default. 

As a workaround, it should be possible to make a subclass which uses an ordered dict.
