### ISSUE TITLE
pygame.midi.midi_to_ansi_note() gives completely incorrect octave values

### ISSUE THREAD

**Issue by Sawyer-Scott-Stahl** [pygame/pygame#1993]
import pygame.midi as pgm
for i in range(21, 109):
    print(pgm.midi_to_ansi_note(i))

The octave is supposed to change at C, but here its completely inconsistent when the octave changes. You go from D0 to D#1, and it keeps being wrong (and inconsistently wrong) the whole way down the line.

**Comment by galexandreg** [comment]
Hi
This problem was fixed in Pygame 2.0.0.dev8 ( #1561 )

If it's possible for you, I suggest you try the development version of Pygame2. Even if it's a development version, it's usually just as stable and has a LOT of bug fixes. It also works a lot better on some platforms.

You can install it by using `--pre` when installing using pip : `python3 -m pip install pygame --pre`

**Comment by MyreMylar** [comment]
Let us know if that works for you @Sawyer-Scott-Stahl then we can close this issue.

**Comment by MyreMylar** [comment]
No response, but we know this is fixed. This has been reported three times now.
