### ISSUE TITLE
pygame.display.set_icon does not work on GNOME for pygame 1.9.6

### ISSUE THREAD

**Issue by dafrito** [pygame/pygame#2007]
System:
Fedora 32, Linux 5.7.7-200.fc32.x86_64, SDL 1.2.15, pygame 1.9.6

STR:
1. Install pygame 1.9.6 (current default on Fedora packages)
2. python -m pygame.examples.aliens

Expected result:
Icon appears in taskbar, alt-tab, activities

Actual result:
Icon is blank in these areas

I ran `pip install pygame==2.0.0.dev10` and the icon showed up as expected.

Also, using pygame 1.9.6, if I ran Xfce, the icon also showed up as expected. But GNOME, GNOME Classic, and GNOME on Xorg did not work.

**Comment by MyreMylar** [comment]
Sounds like this will be fixed when pygame 2 is released. 

I recommend no action.

**Comment by illume** [comment]
Yeah, probably good to close this one.

You could submit the issue to libsdl.org bug tracker or the distribution
bug tracker if you really want it fixed in the distribution SDL 1.2.x. But
it’s probably going to be hard to get that version fixed. They do often
accept patches, but don’t do any releases.

**Comment by gegentan** [comment]
Same on pygame 2.5.2
