### ISSUE TITLE
Circles render incorrectly

### ISSUE THREAD

**Issue by redstonerodent** [pygame/pygame#2016]
The diagonal portions of circles, drawn with `pygame.draw.circle`, are slightly too far from the center.

Minimal working example: this draws a circle centered at (x,y) with radius r in two ways. First, in white, using `pygame.draw.circle`. Second, in green, by checking for each pixel whether it's within distance r of the center.

```
import pygame
from pygame import gfxdraw

x,y = 0, -4000
r = 4500

surf = pygame.display.set_mode((1000,1000))

pygame.draw.circle(surf, (255,255,255), (x,y), r, 2)

for i in range(1000):
	for j in range(1000):
		if (x-i)**2+(y-j)**2 < r**2:
			gfxdraw.pixel(surf, i, j, (0,255,0))

pygame.image.save(surf, 'img.png')
```
This generates the following image:

![img](https://user-images.githubusercontent.com/7309415/87499984-7bba7f00-c629-11ea-946e-27eab0830cf3.png)

At the bottom, the two circles coincide. At the right side, the green circle (from checking each pixel) is noticeably smaller than the white pixel (from `pygame.draw.circle`).

**Comment by MightyJosip** [comment]
Hi. You are probably using the old pygame version. There were some improvements to the circle drawing algorithm so in 2.0.0.dev10 you get the following output (I just swapped the order of the drawn circles)
![img2](https://user-images.githubusercontent.com/29337110/87520138-d633f980-c682-11ea-9662-1a95a7778abe.png)
There is a slight difference between this 2 circles, but this is basically the best you can get (because checking 1000x1000 pixels in your example would take way too long). So the choice was either you get the perfect circle and low fps, or almost perfect circle that is drawn really fast. Because we are the library mostly used for games we decided for the second approach. And when I was writing the code for `pygame.draw.circle()` this was the best algorithm I could find in terms of speed.

**Comment by Starbuck5** [comment]
It looks like this issue has been resolved (well enough) in dev10, so I'll close it.
