### ISSUE TITLE
pygame import interferes with signal.alarm

### ISSUE THREAD

**Issue by combs** [pygame/pygame#2017]
Here's something interesting. Under some circumstances (second start after a crash, say), pygame.display.set_mode will hang indefinitely. So I have some wrapper code that uses `signal.alarm` to catch this and send a `KeyboardInterrupt` which kicks it off again. [lots more about this problem here.](https://stackoverflow.com/questions/17035699/pygame-requires-keyboard-interrupt-to-init-display) This issue is about something related but different:

At some point, something inside pygame seems to have started interfering with `signal.alarm`. If you run this sample code:

```
import signal, time
signal.alarm(10)
i = 0
while True:
    print(i, "seconds passed")
    i += 1
    time.sleep(1)

```

all is well and it quits after 10 seconds on the following environments:

```
Linux hostname 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
>>> pygame.__version__
'1.9.3'
-
Linux hostname 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
pygame 1.9.4.post1
```

But if you `import pygame` before requesting `signal.alarm`, it never fires and continues marching on eternally:

```
import signal, time
import pygame
signal.alarm(10)
i = 0
while True:
    print(i, "seconds passed")
    i += 1
    time.sleep(1)

```

```
>>> while True:
...     print(i, "seconds passed")
...     i += 1
...     time.sleep(1)
... 
0 seconds passed
1 seconds passed
2 seconds passed
3 seconds passed
4 seconds passed
5 seconds passed
6 seconds passed
7 seconds passed
8 seconds passed
9 seconds passed
10 seconds passed
11 seconds passed
12 seconds passed

```

Doesn't seem to matter which order the import occurs.

I also see the problem in Cythonized .pyx modules. python2 does it too.

Doesn't need to have `pygame.display.init()` or anything called in order to trigger this, the import itself suffices.

I don't know exactly when this began to occur, but it was sometime after April 2018.

**Comment by MyreMylar** [comment]
Looks like SDL_SetTimer() is incompatible with `signal.alarm/SIGALRM` according to the SDL docs, so I'd guess it is related either to that - or some change to SDL/pygame's use of multi-threading which also upsets SIGALARM.

Could you use something like the `Timer` class from `threading` ?

```
import threading, time
import pygame


def interrupt(state):
    state.running = False
    raise KeyboardInterrupt


class Status:
    def __init__(self):
        self.running = True


status = Status()
timer = threading.Timer(3, interrupt, [status])
timer.start()

i = 0
while status.running:
    print(i, "seconds passed")
    i += 1
    time.sleep(1)
```

I can't easily investigate this any further myself as `signal.alarm` is a unix/linux only thing. Nor am I an expert on multi-threading problems by any means, and I don't understand your use case in depth. But as general advice working around SDL & threading problems is an easier road to hoe than trying to tackle them head on.

**Comment by combs** [comment]
Thank you!

That plus a .cancel() is a reasonable fix for my purposes. (the idea is to have a "dead man's switch" around the set_mode call, which hangs indefinitely on *ix under some circumstances.) 

I gave it a dig and can't seem to see where the SDL timer initialization is occurring in pygame. `pygame.init()` (`pg_init` in `base.c`) does use `SDL_INIT_TIMER` flag when firing up SDL, but that shouldn't happen on import, right?

**Comment by MyreMylar** [comment]
Hmm, think I have found the bit of code here:

https://github.com/pygame/pygame/blob/d79cd7de2f36c477c3eae6704ca3a2f33961d57d/src_c/base.c#L2026-L2039

This function is called on import of pygame and seems to intentionally disable SIGALRM - which seems pretty conclusive. It seems to have been kicking around in the pygame codebase for a long time so I have no idea what bug it was originally for, or if anyone still uses Solaris for anything.

**Comment by combs** [comment]
Wild--Thank you. What do you think, should I leave this open or close it?

**Comment by MyreMylar** [comment]
I think we can leave it open for now, I was hoping someone who has been around pygame dev longer than me might remember what this bit of code was added for; and that may still happen.

Without the help of ancient pygame lore the other path towards working on this would be something like:

1. Comment out this section of pygame's code and rebuild the library on linux to see if it makes signal.alarm() work again - no point changing anything if this is not the fix.

2. Find someone with Solaris OS who is prepared to test pygame with this block of code removed and see if it still breaks pygame on solaris in some obvious way.

3. If it does, evaluate whether it is better to have Solaris support or to support signal.alarm() - which is probably a tough call as signal.alarm() appears to be a linux only feature of python anyway and it doesn't provide essential functionality, though it is in the python standard library and on the other hand I don't think Solaris is a particularly widely used operating system today, though clearly someone liked it enough at some point to add this block of code.

4. If it doesn't break Solaris we can remove it and be done with it.

5. If it breaks Solaris and we decide to keep Solaris support then nothing changes. Perhaps we should document somewhere that signal.alarm() doesn't work with pygame but I suspect it is one of those bits of documentation that is unlikely to save people time. Maybe this thread will work better when it gets indexed by search engines. This is probably the most likely outcome anyway because I can't currently imagine there being enough interest or resources to actually work on a small, low impact issue like this. But people do like to prove me wrong when I make guesses like this.

6. If it breaks Solaris but we decide to drop Solaris support and support signal.alarm() instead then it will get deleted and we should probably add a small note somewhere that Solaris support has been dropped.

**Comment by robertpfeiffer** [comment]
Isn't this related to the old parachute?

https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlinit.html
https://wiki.libsdl.org/SDL_Init
https://wiki.libsdl.org/MigrationGuide

**Comment by MyreMylar** [comment]
> Isn't this related to the old parachute?
> 
> https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlinit.html https://wiki.libsdl.org/SDL_Init https://wiki.libsdl.org/MigrationGuide

Seems plausible. I think we should try commenting this block of code out in a near future release and see if we get any complaints. 

I doubt many people are still using Solaris & pygame anyway, it seems to be very dead as a desktop OS (posts about it being dead floating around in 2012) and is being phased out on the minority of remaining servers in the 2030s. 

I mean it could still come back but probably a think to worry about at that point.
