### ISSUE TITLE
Nuitka error

### ISSUE THREAD

**Issue by Ben-Faessler** [pygame/pygame#2031]
I try to compile pygame2.0.0dev10 with nuitka but this give me a error:
`Nuitka-Plugins:INFO: implicit-imports: Implicit module 'pygame.event.Event' suggested by 'pygame.mixer' not found.`
Can i fix this?

**Comment by MyreMylar** [comment]
Only just heard of nuitka today - I can tell you that `pygame.event.Event` is not a python module but a class within the python event module.

Have you tried asking on the nuitka github instead? they might have a better understanding of the error messages it produces. It would be astounding to me if any kind of general automatic compiler worked with pygame first time.

**Comment by Starbuck5** [comment]
I'm going to close this, since I believe things around this have advanced in the last year.

I compiled a test program with pygame and nuitka a few months ago (on 2.0.1) and didn't have this problem.

Also, I see people raising completely unrelated pygame + nuitka issues / enhancements with a google search, suggesting that people aren't tripping on this hurdle anymore.
