### ISSUE TITLE
Fullscreen in 2.0.0.dev12 Not Working on XUbuntu 20.04 with GeForce MX250

### ISSUE THREAD

**Issue by jwvhewitt** [pygame/pygame#2118]
I cannot get fullscreen mode to work on my XUbuntu 20.04 laptop with a GeForce MX250 graphics card.

* When starting in fullscreen mode, I get a black screen that I cannot alt-tab out of. The program seems to be running but it does not seem to be getting any input from the mouse or keyboard.

* When switching to fullscreen mode from a window, the display disappears and often the window button disappears from the task bar. As above the program seems to keep running but does not seem to receive any input from the mouse or keyboard. If the window button is visible, it is sometimes possible to press it and get a black screen as above.

I discovered this problem when testing 2.0.0.dev12 with GearHead Caramel ([https://github.com/jwvhewitt/gearhead-caramel](https://github.com/jwvhewitt/gearhead-caramel)). The example program setmodescale.py and other demos have the same issues. The programs run correctly on my wife's Windows desktop computer, so it's probably something about this laptop which is causing the problem.

Edit: This problem only appears to happen when the SCALED flag is used. Example programs that don't use SCALED run properly.

**Comment by galexandreg** [comment]
Does it work with older pygame2 versions (like dev10) ?

If it doesn't, it really looks like it could be an issue with the SDL and your config...
You could try to use another driver when using SCALED to see if it works. It's probably using opengl by default on linux (you can see the current driver in the output of setmodescale.py or with `pygame.display._get_renderer_info()`). 

Try changing it to "software" (or something else available on your system) to see if it works.
You can change it with the `SDL_RENDER_DRIVER` environment variable (something like `os.environ["SDL_RENDER_DRIVER"] = "software"`).
https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER

**Comment by jwvhewitt** [comment]
The problem does not occur if I compile 2.0.0.dev12 from source.

**Comment by illume** [comment]
Thanks. blubberquark confirmed on their system too.

- no relevant patches are made to the Ubuntu SDL 2.0.12
- I'm wondering if the manylinux (based on old centos) has some sort of X11 ABI/API incompatibility here. Or even libc I guess.
- It could also be some incompatible Ubuntu X11 patches, but I haven't checked this.

Probably the next step would be to try compiling with manylinux2014 to see if that solves the issue.

**Comment by fjpena** [comment]
I can confirm this is also happening on Fedora 32, running SDL 2.0.12. If I build from source, fullscreen works as expected, but it fails if I use the wheel.

**Comment by mcpalmer1980** [comment]
This seems very similar to a problem that has been bugging me as of late. Flyboy used to toggle to and from fullscreen perfectly fine but it suddenly exhibited the described by @jwvhewitt. I was running Ubuntu 19.10, and thought this problem stemmed from a system update. I installed 20.04 and live tested 20.10 and had the same problem. Never thought it was an issue with the wheels. 

Although I haven't tried building pygame on my main system, the PyInstaller binary version of Flyboy that I built using Steam Runtime + python3.5 + pygame2.0dev1 works just fine.

**Comment by mcpalmer1980** [comment]
built dev1 on Ubuntu 20.04 today and it exhibits this problem no matter my GPU driver (intel, nvidia, nouveau). Works when built on stream rt though.

**Comment by onpon4** [comment]
I'm not sure if this is related, but I think it might be, so I'll report my findings here:

After fixing a compatibility bug, I've noticed that while it otherwise works with Pygame 2 just fine, my [Seclusion Game Engine](https://github.com/python-sge/sge) (which uses Pygame as a backend) seems unable to switch to fullscreen properly. Having scoured my own code, I think this is a result not of another compatibility bug, but rather some sort of broken behavior in `pygame.display.set_mode`. This is on Debian 10 "Buster", using Pygame 2.0.0 straight from pip, with the Debian-supplied version of Python 3 (which is 3.7.3) and SDL2 (which is 2.0.12). Since it might matter, I should also mention that I'm using GNOME with X11 (rather than the default Wayland). Tested with [Pacewar](https://github.com/pacewar/pacewar) and [Hexoshi](https://github.com/hexoshi/hexoshi); Pacewar makes a better test subject since it switches fullscreen just by pressing F11. I also looked for a test candidate in the Pygame examples direectory and found aliens.py to be a pretty decent test case, though I got slightly different results from that (more on that later).

For reference, this is the code the SGE uses to switch both to and from fullscreen:

https://gist.github.com/onpon4/a8c26560d03f24ae5fee8fd4761b1a1a

It's effectively just a call of pygame.display.set_mode, with some extra fluff mostly to handle how the SGE wants the fullscreen display to be sized. You can see that it ultimately passes the flags: `pygame.FULLSCREEN | pygame.HWSURFACE | pygame.DOUBLEBUF` if going to fullscreen, and it passes the flags: `pygame.HWSURFACE | pygame.DOUBLEBUF` (possibly adding `pygame.RESIZABLE` depending on certain settings) if going to windowed.

The result I always get with this, and for me this is regardless of when fullscreen was initiated, is that the contents of the window seem to disappear (showing me my GNOME desktop). The game proceeds to lock my mouse cursor in the center (which it is supposed to do; this is an intentional behavior of the SGE under the conditions present when in fullscreen mode), so it seems to sort of "think" that it's in fullscreen even though it's displaying nothing. The game also sometimes does and sometimes doesn't receive key presses and mouse input. If it doesn't receive the presses, the window behind it (always the terminal window for me, since that's how I launch these games) receives them. So for example, pressing F11 again in Pacewar caused the terminal to go into fullscreen mode (since that's the keyboard shortcut for fullscreen mode in my terminal emulator), and somewhat frustratingly navigating Hexoshi's menus to quit (going by sound, since I can't see anything) could lead to pressing up followed by Enter on the terminal (launching Hexoshi again). Weirdly, if I clicked the mouse buttons while the games were in fullscreen mode, the entire screen would turn black and I would occasionally see flickers of what should have been persistently displayed. Behavior with input was still the same in that state, however.

In the case of the aliens.py example, I instead saw my display seemingly turn off entirely for some reason. The same problem I was having with inputs occurred in an identical fashion, however. I'm not sure why the visual results of switching to fullscreen in aliens.py was different than for SGE games; my best guess is maybe it has to do with the presence or absence of cursor locking, but that's just a wild guess.

I think it worth mentioning that I also do work on two games that are written in C and use SDL2 directly and have never had any problems with fullscreen in either of those games on this operating system (those being [Naev](https://github.com/naev/naev) and [Project: Starfighter](https://github.com/pr-starfighter/starfighter). Just to be sure, I tested Project: Starfighter again briefly just now and confirmed that fullscreen switching there works without issue. This of course doesn't necessarily mean this bug can't have its roots in some sort of weirdness specific to Debian's SDL 2.0.12, but just thought I'd mention that.

I would also like to mention that only passing on the `pygame.FULLSCREEN` flag as an experiment didn't seem to change results at all in SGE games (and of course, aliens.py doesn't use `pygame.HWSURFACE` or `pygame.DOUBLEBUF` to begin with).

Anyway, this issue I'm experiencing is similar enough to what's described above that I think it *might* be the same issue. If it's unrelated, though, then I'd be happy to open a new issue for it.

🕵️

**Comment by mcpalmer1980** [comment]
I know this was posted elsewhere but I don't see it here. Replacing the libsdl2.o file in the pygame directory with your system lib will fix this problem. The lib installed with pip3 install pygame --user is overly large and fails to enter fullscreen. Not sure why but I have confirmed this simple fix with multiple linux users.

**Comment by onpon4** [comment]
I don't really understand what you mean by "replacing the libsdl2.o file", but compiling from source also does the trick. If the problem is that Pygame is shipping too new of a version of SDL, would the solution perhaps be to include an older SDL in the wheels?

🕵️

**Comment by illume** [comment]
It's definitely some issue with the manylinux pygame build of SDL. 

I made a few changes to the manylinux build for the upcoming 2.0.14 SDL release here: https://github.com/pygame/pygame/issues/2393 but none of them fixed it yet. But hey, at least that build gets pulseaudio working again :)

It's possible we might need to make builds of X on there, or maybe there's some sort of dependency we can install or configure option to get working properly. The buildconfig/manylinux-build/README.rst documentation covers the build fairly well if anyone wants to hack on it.

**Comment by Nikorasu** [comment]
I'm on Linux Mint, and I seem to be having a similar problem, reproducible on a couple different computers, with different entirely GPUs.
However, I am NOT using SCALED mode, just simply pygame.FULLSCREEN

When I launch my project, I get a solid black full-screen, with the mouse visible.. Then when I quit, for like 1 frame before it closes, I can see my project's sprites get drawn to the screen.. Everything works perfectly fine in RESIZABLE mode, and I can't get other Example projects working in Fullscreen either.

**Comment by illume** [comment]
Hoping that this 2.0.3.dev6 pre-release fixes it.
```bash
python3 -m pip install pygame==2.0.3.dev6
```

Is anyone able to test it?

**Comment by robertpfeiffer** [comment]
> Hoping that this 2.0.3.dev6 pre-release fixes it.
> 
> ```shell
> python3 -m pip install pygame==2.0.3.dev6
> ```
> 
> Is anyone able to test it?

I can test on my old crappy Laptop that overheats and has a different Nvidia graphics card. I think I'll first try to reproduce the bug again with the old 2.0.0.dev12 wheel from PyPI, just in case Nvidia accidentally wrote a good driver and I somehow installed it via apt-get dist-upgrade.

**Comment by fjpena** [comment]
> Hoping that this 2.0.3.dev6 pre-release fixes it.
> 
> ```shell
> python3 -m pip install pygame==2.0.3.dev6
> ```
> 
> Is anyone able to test it?

I have tested 2.0.3 and 2.0.3.dev6, and both work fine with fullscreen for me. 2.0.2 still shows the behavior described in the bug.

My test environment was Fedora 34 on Wayland, Intel integrated GPU.

**Comment by ankith26** [comment]
Nice, seems like this is fixed :)
