### ISSUE TITLE
Debian python3-pygame package

### ISSUE THREAD

**Issue by illume** [pygame/pygame#221]
Originally reported by: **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**

----------------------------------------

This issue is to track a python 3 package for Debian, Ubuntu, and Raspbian.

* depends on 1.9.2 release coming out.
* get in contact with listed maintainers. Maybe get help from Raspbian community.
* there's already a launchpad PPA (https://code.launchpad.net/~pygame/)
* create a debian/ubuntu/raspbian issue to track.
* check python 3.4 support.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/221

**Comment by PanderMusubi** [comment]
PLease see https://bugs.launchpad.net/ubuntu/+source/pygame/+bug/1314725 and rename this issue here in GitHub to 1.9.3

**Comment by takluyver** [comment]
I've taken the version number out of the issue title, so that if we make another release before someone updates the Debian packages, we don't have to keep retitling this issue.

It looks like Vincent, who made packages in Debian's experimental repo, is not working on it at the moment. If you're keen to see the new version uploaded, you could get in touch with the Debian Python Modules Team. But be warned, I was on their mailing list until a couple of years ago, and at the time it was the most grumpy and bureaucratic team I've ever tried to work with. I left because the effort required was out of all proportion to what I could get done. Hopefully things have improved since then, but tread carefully.

**Comment by illume** [comment]
The issue is closed in Ubuntu. https://bugs.launchpad.net/ubuntu/+source/pygame/+bug/1314725
Looks like pygame 1.9.3 is packaged in "Cosmic proposed".

Also in Debian 'python3-pygame' is packaged here: https://packages.debian.org/search?keywords=python3-pygame

Closing this issue. Thanks to the Debian maintainers :)
