### ISSUE TITLE
pygame2 Rect.colliderect() for zero-width rects does not detect collision

### ISSUE THREAD

**Issue by gummbum** [pygame/pygame#2246]
**Environment:**

- Operating system: Windows 10
- Python version: 3.7.4
- SDL version: 2.0.12
- PyGame version: 2.0.0.dev22 (pygame legacy version 1.9.6)
- Relevant hardware: NA

**Current behavior:**

For the following zero-width rects, collision is not detected in pygame2. pygame1 does detect the collision:
```
r1 = pygame.Rect(50, 0, 0, 50)
r2 = pygame.Rect(0, 25, 50, 0)
```

**Expected behavior:**

pygame2 should detect this collision as pygame1 does.

**Screenshots**

NA

**Steps to reproduce:**

1. Run the sample code in pygame1.
2. Move the mouse in the window so that the rects collide, and observe the window caption reports a collision.
3. Run the sample code in pygame2.
4. Move the mouse in the window so that the rects collide, and observe the window caption does not report a collision.

**Test code**

```
import pygame
from pygame.locals import *
pygame.init()
clock = pygame.time.Clock()
screen = pygame.display.set_mode((400, 100))
r1 = pygame.Rect(50, 0, 0, 50)
r2 = pygame.Rect(0, 25, 50, 0)
collision_last = None
collision_new = None
while 1:
    clock.tick(30)

    for e in pygame.event.get():
        if e.type == KEYDOWN:
            quit()
        elif e.type == MOUSEMOTION:
            r1.topleft = e.pos

    collision_new = r1.colliderect(r2)
    if collision_new != collision_last:
        pygame.display.set_caption('rects collided={}'.format(collision_new))
        collision_last = collision_new

    screen.fill((0, 0, 0))
    pygame.draw.rect(screen, pygame.Color('red'), r1, 1)
    pygame.draw.rect(screen, pygame.Color('green'), r2, 1)
    pygame.display.flip()
```

**Stack trace/error output/other error logs**

NA

**Comment by zoldalma999** [comment]
Its because of this:
https://github.com/pygame/pygame/blob/master/src_c/rect.c#L350-L355
It looks like it was removed deliberately

**Comment by Starbuck5** [comment]
Commenting to link issue #1197

**Comment by illume** [comment]
Thanks for the bug report. Remembering this, rect only sometimes collided with zero sized rect. Since it wasn't consistent, it was considered a bug, and we went with "Something that doesn't exist can't collide... os zero sized rects should not collide".

@gummbum Maybe our thinking is wrong, or we missed something... if you have a case for why these rects should in fact collide, please say?

**Comment by gummbum** [comment]
Thanks for your thoughts, René. Here is a use case to consider.

For a diagonal line one can calculate a rect and its box will collide 
with another line. The rect collision test is very efficient; then you 
can do the more expensive test line vs other (this test is in pure 
Python). But when the line is perfectly vertical or horizontal then its 
rect is zero width; one would need a corner case for this, to calculate 
a rect of width=1.

I know that geometrically a rect of zero width is a line, and a rect of 
zero width and height is a point. This suggests to me that either they 
should not be allowed in pygame, or they should behave like every other 
rect.

**Comment by MightyJosip** [comment]
> I know that geometrically a rect of zero width is a line, and a rect of
zero width and height is a point. This suggests to me that either they
should not be allowed in pygame, or they should behave like every other
rect.

The rect that has the `width == 1` is the line (same can be said about the `height == 1`). If it has both `width == 1` and `height == 1` than it is the point.

Something that has the `width == 0` is the empty space, something that doesn't even exist (as basically everything in this universe have its size) and because it is nothing/empty space it doesn't collide with anything

**Comment by gummbum** [comment]
But as a game library I'm not concerned with geometry as much as I am 
with algorithm. I have a spatial hash that requires rects. A line that 
is zero width still needs a rect. If rects of zero width do not collide 
with any other rects, then this becomes an issue with the library that 
needs to be worked around.

**Comment by MyreMylar** [comment]
Rects, lines and points used in pygame are in pixel space where the minimum width and height are 1 pixel.

A perfectly straight line from `pygame.draw.line()` that is visible always has a width or height of 1 because drawing is done in pixel space. The containing rect returned from draw.line() reflects that.

I think if you want geometric style points, lines and rects that can have 0 width and height then you can easily build them yourself.

**Comment by ChrisJefferson** [comment]
If (as it appears) there is no use(?) for Rects which have height or width == 0, should they be banned (so print warning, or assert?)

**Comment by gummbum** [comment]
I dunno who is making this decision. I would not have reported the bug 
if I thought zero width rects had no use. If you ban then you'll break 
any code that resizes rects that happen to transition to or through zero 
width. And it would break any algorithms that don't care if a rect is 
zero width. You'll saddle pygame coders with insuring rect width, and 
try-catching these runtime errors. Not a wise move in my opinion.

**Comment by gummbum** [comment]
And here is another anomaly you'll bind upon pygame coders if zero-width 
rects do not ever collide.

Two identical rects will never collide if their width is zero, even 
though they occupy the same exact space. Two lines in the same exact 
space do intersect in geometry. The lines and the rects are 
geometrically identical.

**Comment by illume** [comment]
> Two identical rects will never collide if their width is zero, even
though they occupy the same exact space. Two lines in the same exact
space do intersect in geometry. The lines and the rects are
geometrically identical.

Pretty convincing argument.

**Comment by MyreMylar** [comment]
But in pygame lines always have a minimum width of 1 not 0.

**Comment by MightyJosip** [comment]
> Two identical rects will never collide if their width is zero, even though they occupy the same exact space.

If they have width == 0 (or height) they don't occupy any space, so they can't occupy the same exact space (or all of them occupy the same space depending if you want to call every empty space equal)

> Two lines in the same exact space do intersect in geometry.

Let's take random lines that intersects (for example this 2 lines)
![image](https://user-images.githubusercontent.com/29337110/97808232-04573c80-1c66-11eb-9a16-fbaf72f70bdf.png)
Why do they intersect? The red line goes through the point (2, 3). The blue line goes through the point (2, 3). Therefore both lines go through the point (2, 3) -> lines have the point of intersection -> lines do intersect (or collide if you want to call it that way).

If you intersect you HAVE to have at least one (or more) point of intersection. Now back to rect with `width == 0`. They don't contain any point. Their "list_of_points" is empty. And because of that it is impossible that they have point of intersection with something, because they don't even have point in the first place

> The lines and the rects are geometrically identical.

Generally, I wouldn't agree with this. Rect (or any other quadrilateral) is the AREA (or just the bounding box of the area) between 4 lines. Line is something that has no area. Back to my rect point to define the rect you have to define 4 lines is consists of. If you could make the rect that has width==0 that would mean that one pair of parallel sides would need to be the same line. But than you could define that "area" with only 3 lines (since 2 out of 4 are the same). But then (even if it would be any kind of polygon) it would be triangle. But it is not triangle (because for something to be triange it would need to have 3 NON-COLLINEAR points (and it doesn't have it). TLDR: in geometry there is the big distinction between line and any kind of polygon (rect being one of them).

**Comment by gummbum** [comment]
A line has width in pygame because a pixel has width.

**Comment by MightyJosip** [comment]
> A line has width in pygame because a pixel has width.

Yes and that width is 1

**Comment by gummbum** [comment]
In geometry you wouldn't call a "rect with zero width" a rect, you'd 
call it a line. Lines have zero width, just as points have zero width. 
Yet they still exist in space, two lines and/or points can intersect. To 
say a zero-width rect (a line) does not intersect with another when it 
obviously does is illogical.

The lines and the "zero-width rects" (which we can say only because it 
is a pygame.Rect) are geometrically identical: they occupy the same 
exact space. The two lines intersect on all their points. The two rects, 
however, do not intersect because that's how pygame calculates it.

Ultimately I'm seeing a need to support rect collisions for this corner 
case. If we do not, it will create subtle problems for coders.

**Comment by MightyJosip** [comment]
> To say a zero-width rect (a line) does not intersect with another when it obviously does is illogical.

But it doesn't obviously intersect (at least I don't see where does it intersect). If we go to your first example can you explain where does this 2 rects intersect (what is their point of intersection)
```
r1 = pygame.Rect(50, 0, 0, 50)
r2 = pygame.Rect(0, 25, 50, 0)
```
> The lines and the "zero-width rects" (which we can say only because it is a pygame.Rect) are geometrically identical

The lines and the 1 width pygame.Rects are geometrically identical because pygame.Rect is made specifically to support the rasterization of the screen.

> Ultimately I'm seeing a need to support rect collisions for this corner case.

Yes we do support that corner case on the way defined in the docs by following: `A Rect with a 0 size will not collide when using collision detection methods (e.g. collidepoint(), colliderect(), etc.).` Reasoning for that implementation is the following: `The area covered by a Rect does not include the right- and bottom-most edge of pixels. If one Rect's bottom border is another Rect's top border (i.e., rect1.bottom=rect2.top), the two meet exactly on the screen but do not overlap, and rect1.colliderect(rect2) returns false.`

So even if you consider 2 rects to be identical, because one rect top is == to another rect bottom they don't collide. Changing that rule would have multiple other consequences. Sadly in my opinion you would have to work around that rule.

**Comment by gummbum** [comment]
(Resending. Sorry for the duplicate Josip, thought I sent it to the list.)

So basically you're arguing that a zero-width rect doesn't exist in 
pygame. It quite literally has no use and no value, other than to let 
you set its width to zero without raising a fuss.

I'm not satisfied by "Changing that rule would have multiple other 
consequences". It's easy and cheap to generalize.

René wrote:

        Two identical rects will never collide if their width is zero, even
        though they occupy the same exact space. Two lines in the same exact
        space do intersect in geometry. The lines and the rects are
        geometrically identical.

    Pretty convincing argument.

Seems to have been ignored.

I'm losing patience with this philosophical debate. It's a functional 
issue. Pick the solution that incurs the least cost to coders.

**Comment by MyreMylar** [comment]
I'm in favour of leaving it as it is now. I don't think there is any great harm in letting people define rects with 0 width and 0 height, but I don't think, conceptually they should collide with anything or be visible because everything in pygame is built around the pixel, with a width and height of 1 as the atomic unit.

There is probable harm in stopping these types of rects from being made as no doubt lots of people already have and are depending on the existing behaviour. Likewise, making them suddenly start colliding could cause bugs if people are currently assuming that 0 width and 0 height rects are a simple way to make sprites that can be positioned but don't collide (for example).

So, yes my vote is that we change nothing here. I currently don't see a reason why any algorithm could not be built around the assumption that 1x1 is the minimum size of a collidable thing.

**Comment by ChrisJefferson** [comment]
@MyreMylar any code which is "depending on existing behaviour" is probably pygame1 code, where (a) 0-width is allowed, and (b) they collide. Banning them will make that code crash yes, but at the moment that code is silently breaking (this happened to me too, while porting some code across).

Seeing as pygame2 is about a week old, if you want to keep the code of "lots of people" going, then colliding is surely the right thing to do?

**Comment by MightyJosip** [comment]
> any code which is "depending on existing behaviour" is probably pygame1 code

They why in the pygame1 this two rects didn't collide 
```
r1 = pygame.Rect(1, 1, 0, 10)
r2 = pygame.Rect(1, 1, 10, 10)
print(r1.colliderect(r2))
```
Answer is, collision results of the rects with either width==0 or height==0 was the result of bug. Now to fix those inconsistencies something had to be changed. Since the docs (from way before any of the pygame 2 versions define the following behaviour, oldest I could find is from 2016) define the following lines: https://github.com/pygame/pygame/blame/eecbb2b2c1fdf27d3ba2ebc8e3df8ae39763e01c/docs/reST/ref/rect.rst#L65-L68, we decided that the expected behaviour of rect collision when rect has width or height == 0 is that they DON'T collide (because if the rect has the width 0 that means the following:
```
r1 = pygame.Rect(1, 1, 0, 10)
print(r1.left, r1.right)  # Output: 1 1
```
and by docs that right 1 is NOT included in "The area covered by a Rect", and that means that they don't collide.

Maybe this whole conversation turned into "philosophical debate", yes "fixing" this would be trivial, but to fix it we need to know WHY should
```
r1 = pygame.Rect(50, 0, 0, 50)
r2 = pygame.Rect(0, 25, 50, 0)
```
collide. And the answer would need to be something else that is not.
a) Because it used to be that way (yes it was, but this was wrong result (according to the docs))
b) I need it for my program (because as MyreMylar said: "I currently don't see a reason why any algorithm could not be built around the assumption that 1x1 is the minimum size of a collidable thing.").
HINT: good reason would be to find a single pixel that satisfies this (https://github.com/pygame/pygame/blame/eecbb2b2c1fdf27d3ba2ebc8e3df8ae39763e01c/docs/reST/ref/rect.rst#L65-L68) that both `pygame.Rect(50, 0, 0, 50)` and `pygame.Rect(0, 25, 50, 0)` contains.

**Comment by MyreMylar** [comment]
@ChrisJefferson sorry to hear you had problems porting, we've been trying to minimise that as much as possible.

I think MightyJosip explained why whatever was going on in pygame 1 with 0 width or 0 height rects wasn't as simple as they had functional collision. It sounds like they sometimes collided and sometimes did not in an inconsistent and contra-documented fashion.

Your point about this changing silently is well taken though, I'm just not sure if a warning that fires off when you try to call collide on a zero width/zero height rect wouldn't annoy more people. Though I guess we could try it and see if it generates a flood of complaints.
