### ISSUE TITLE
Remove everything test/util/ as these scripts are no longer used.

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#2289]
Since it's been a long time since we last added a new python module this script has stopped working, functions it imported no longer exist in the code base and until recently it didn't even run in python 3.

There is documentation for it in README.TXT so it shouldn't be too impossible to reverse engineer how it worked from the existing code and the expected output.

**Comment by illume** [comment]
I think we should remove it? It was made to generate the test place holders waaaaaaay back in 2008 or so, and is not needed any more since we have test place holders (and now actual tests for many of them).

Perhaps it could be useful for other python libraries, but even then it would be best to live in a separate package IMHO.

**Comment by MyreMylar** [comment]
OK, that was my initial instinct too, but then some wisp of conservatism kicked in and I thought maybe we might find a use for it :)

**Comment by MyreMylar** [comment]
Updated the title.

**Comment by ankith26** [comment]
Well, so it’s just deleting 4 files right, let me make a PR to close this issue
