### ISSUE TITLE
Issue with rendering fonts when trying to port over my game to pygame 2

### ISSUE THREAD

**Issue by Luckyseer** [pygame/pygame#2298]
I tried porting over my game to pygame 2 and faced a few issues. Most notably, the fonts are not rendering properly for some reason in a few places and for some reason the alpha values of some of the loaded images are not applied properly.
It works as expected on pygame 1.9.6
**Environment:**

- **Operating system** Windows 10
- **Python version** 3.7.4
- **SDL version** 2.0.12
- **PyGame version** 2.0.0

**Current behavior:**

When trying to render the font, it shows up as a blocks of characters like so:

![pygbug1](https://user-images.githubusercontent.com/36114443/97832519-04544c80-1cf9-11eb-89ca-87058e1037b3.JPG)

**Expected behavior:**
This is how it should look like(pygame 1.9.6)

![pygbug2](https://user-images.githubusercontent.com/36114443/97832525-0ae2c400-1cf9-11eb-94c2-d5b87a83abf7.JPG)

**Test code**

You can find the game at: https://github.com/Luckyseer/The-Arena

In there you can run "data/uitester.py" to see the bug in action.

Please note: I know that the code is terrible, this was a game that I originally made while in Highschool, I fixed it up in a lot of places but it's still pretty bad.

**Comment by Starbuck5** [comment]
Hi, thank you for the bug report,

This issue was noticed by someone a couple days ago, and it is fixed in the main branch (just not in the latest release).
I think this was the commit that fixed it: https://github.com/pygame/pygame/pull/2269

I tested "data/uitester.py" on a locally built copy of pygame, and all the text was visible.

This will be fixed in the 2.0.1 release.
