### ISSUE TITLE
Support for ARM macs

### ISSUE THREAD

**Issue by justinkterry** [pygame/pygame#2306]
Macs are transitioning to to ARM in full over the next 2 years, ARM dev kits are already out, and Apples rumored to release the first ARM macs next week. What's the plan here?

**Comment by MyreMylar** [comment]
Sounds like good news as it will make it a lot easier to test pygame on
Arm. It already works generally in Arm as that what Raspberry Pi uses.
However nobody's main Dev machine is a Pi.

**Comment by illume** [comment]
Apple is supporting x64 for the transition, so pygame should keep working with that. pygame doesn't rely on OpenGL or other deprecated APIs as far as I know, so it should be pretty simple from that aspect. For the next 2 years, pygame should run on new ARM Apple hardware without much or any extra work.

Because of this, I'll close this issue. It should theoretically work. If it doesn't someone will post an new issue I assume :)

Note, our dependencies can already compile with mac ARM with conan. There's no python package standard for arm wheels yet, so that's going to be needed first... and a python/distutils build for it too. pygame has also been compiled on iOS, so that's very close to what the Mac will be. With distutils moving into setuptools, I expect that it's not going to be a risk of holding things up for ARM binaries.

I doubt there is someone who wants to work on ARM binaries right now though. There's not really any other active Mac/Apple developers for pygame at the moment... but maybe someone will surf by. There's no hardware available to me or anyone else that I know of, so it's not something anyone will be able to work on yet. PRs welcome of course!
