### ISSUE TITLE
Incorrect handling of pressed keys

### ISSUE THREAD

**Issue by illume** [pygame/pygame#235]
Originally reported by: **Anonymous**

----------------------------------------

```
#!python

[...]
pygame.key.set_repeat(1,1)
while running:
    for event in pygame.event.get():
        keys = pygame.key.get_pressed()
        if keys[K_c]:
            [...]
        if keys[K_v]:
            [...]
        if keys[K_m]:
            [...]
        if keys[K_COMMA]:
            [...]
    [...]
[...]
```
pygame incorrectly handles multiple keys pressed at a time. For example, take the example above and mess with the keys. What you'll notice is that when there is a group of keys pressed, when you release one of them, all remaining pressed keys will become in an unpressed state until another key is pressed.
Using pygame 1.9.2, python 2.7.9 x86, known to occur on Linux and Windows.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/235

**Comment by illume** [comment]
Hi,

thanks @KennedyRichard 

This is related to keyboards not working well when pressing multiple keys.
https://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses

It seems pygame/SDL could perhaps handle this case better when using key.get_pressed.

**Comment by KennedyRichard** [comment]
No problem. I also forgot to mention that some keys doesn't have this problem. For instance, if you use pygame.K_LSHIFT instead of pygame.K_SPACE suddenly everything works as expected.
For many problems with the underlying technology there's usually a good alternative which works. I'm just saying this to encourage people to keep trying once they find a problem.
Developing in Python, provided you follow good practices and software development principles, pays off really good, specially for applications so complex like games.

**Comment by galexandreg** [comment]
I opened an issue https://github.com/pygame/pygame/issues/689 with the same problem a few days ago. (I don't know why my search didn't find this one first...)
According to the comments, it looks like SDL2/Pygame2 will fix the problem.

**Comment by galexandreg** [comment]
This would need testing, but a comment on Reddit (https://www.reddit.com/r/pygame/comments/ad5hla/strange_problem_in_my_game/edgr2km) suggests that it may actually not be a Pygame or SDL issue, but a hardware issue.
https://en.wikipedia.org/wiki/Rollover_(key)
