### ISSUE TITLE
[Feature Request]Haptic/ForceFeedback support?

### ISSUE THREAD

**Issue by LeeNX** [pygame/pygame#2402]
I was wondering (really hoping), if somebody had taken a look at SDL2 support for Haptic Feedback https://wiki.libsdl.org/CategoryForceFeedback and if there might be support in pyGame 2 yet?  
  
I have PS3 and PS4 DualShock controllers and can test on Raspberry PI and OSX, if anybody has anything to play with.

**Comment by MyreMylar** [comment]
If I remember correctly you can enable force feedback using a specific
driver with a hint to SDL, but I believe the driver has some compatibility
issues which is why it isn't enabled by default. You may be able to set the
hint for SDL via the normal environment variables route (os.environ - see
the pygame module docs). But I'm not sure how you trigger rumbles from that
point.

**Comment by LeeNX** [comment]
Thanks @MyreMylar for the feedback. Just downloaded, compiled and test ```SDL2.0.14``` to test. Messing around on my Mac and a PS4 DS Controller, found that https://www.libsdl.org/tmp/SDL/test/testgamecontroller.c can be compiled and run without any other options and get all bits working, both rumbles included over BlueTooth. This must be using HIDAPI as OSX does not have a ForceFeedBack system, but that is all a different story.  
  
I am really interested in a ```possible/hopeful/wishful``` python library making Haptic easier to use like ```pyGame2```.

**Comment by robertpfeiffer** [comment]
cf #2423
