### ISSUE TITLE
Add 'str' to freetype's _ColorValue 

### ISSUE THREAD

**Issue by queueseven** [pygame/pygame#2461]
When I use mypy as my linter and I want to render some text with the freetype module like this (note the string value for `fgcolor`)

    font.render_to(surface, (x, y), mystring, fgcolor='white', size=120) 

mypy gives me the following error

> Argument "fgcolor" to "render_to" of "Font" has incompatible type "str"; expected "Union[Color, Tuple[int, int, int], List[int], int, None]"mypy(error)

Obviously using a string as color works (finally!), which is nice, but the error message is wrong in this case.

In freetype.pyi and a lot of other files there's the line

    _ColorValue = Union[Color, Tuple[int, int, int], List[int], int]

I guess `str` should be added there? 🤷‍♂️

**Comment by MyreMylar** [comment]
Investigated this, it looks like the type hint is indeed wrong for the font and freetype modules, but likely matching the C code for the other modules `.pyi` files without at `str` in their `_ColorType`. 

I added a simple PR to fix the issue with freetype and font, but it may be that a more complete fix would update the colour input parameter conversion C code for the mask, display, gfxdraw, pixelarray and transform modules so that they can also accept a string colour value.
