### ISSUE TITLE
Docs: first two parameters of Surface.blit are listed in wrong order

### ISSUE THREAD

**Issue by arganoid** [pygame/pygame#2483]
[(https://www.pygame.org/docs/ref/surface.html#pygame.Surface.blit)]

blit is listed with source before dest:
`blit(source, dest, ...`

dest should come before source, as confirmed by the actual behavior, and by the following sentence in the docs: "Draws a source Surface onto this Surface"

**Comment by ankith26** [comment]
The docs are right actually. Maybe you got a bit confused. The dest that is referred in the docs is actually the coordinates where you want to blit. And this is the docs for the surface object, so the object is the destination surface, the first argument to blit is the source surface and second argument is a x, y coordinate tuple.

The sample usage for blit is
```py
dest_surf.blit(src_surf, (10, 10))
```

Closing this issue because the docs are correct.

**Comment by arganoid** [comment]
I misread the docs as I initially interpreted "source" as a renamed self. One way to make it unambiguous would be to rename "dest" to "dest_pos".
