### ISSUE TITLE
Flappy bird tutorial crashes Gnome on Debian testing

### ISSUE THREAD

**Issue by rduivenvoorde** [pygame/pygame#2487]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Debian Testing (bullseye)
- **Python version** (e.g. 3.7.9, 3.8.5) : Python 3.9.1+
- **SDL version** (e.g. SDL 2.0.12): ?
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 1.9.6
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): Running Gnome 

**Current behavior:**

Running the Flappy bird tutorial:
Youtube: https://www.youtube.com/watch?v=UZg49z76cLw
Code: https://github.com/clear-code-projects/FlappyBird_Python

It makes my whole window manager crash after a while, looking at memory or cpu, nothing is wrong, but all of a sudden (while doing a little 'playing', even when just 15 minutes in tutorial: boom!

**Expected behavior:**

Not crashing X/Wayland

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Run Debian Wayland
2. Start coding, OR just run `python3 flappy_update.py` from the github dir mentioned above
3. After a while: CRASH black screen... 

**Stack trace/error output/other error logs**

Not sure if it is relevant, from dmesg:

```
[  816.962819] gnome-shell[3180]: segfault at 4 ip 00007fd7aa3c603d sp 00007ffc4fc9ba00 error 4 in libgobject-2.0.so.0.6600.6[7fd7aa39f000+2f000]

```

**Comment by rduivenvoorde** [comment]
Mmm, confirmed ( by myself :-) ) on a second laptop running bullseye/sid...

And both in GNOME and in X I get segfaults

```
[ 1322.120133] gnome-shell[1363]: segfault at 30 ip 00007f8b954f103d sp 00007fff5cd8bf70 error 4 in libgobject-2.0.so.0.6600.6 (deleted)[7f8b954ca000+2f000]
[ 1322.120152] Code: 8b 1c d8 48 85 db 0f 84 11 ff ff ff e9 01 ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 48 83 ec 08 48 85 ff 0f 84 93 00 00 00 <48> 8b 07 48 85 c0 0f 84 af 00 00 00 48 8b 00 48 3d fc 03 00 00 77
[ 1322.288260] rfkill: input handler enabled
[ 1327.882281] rfkill: input handler disabled
[ 1351.243228] rfkill: input handler enabled
[ 1358.876172] rfkill: input handler disabled
[ 1538.128927] gnome-shell[23629]: segfault at 400000190 ip 00007fa252b7a03d sp 00007ffcc57aa0e0 error 4 in libgobject-2.0.so.0.6600.6[7fa252b53000+2f000]
[ 1538.128987] Code: 8b 1c d8 48 85 db 0f 84 11 ff ff ff e9 01 ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 48 83 ec 08 48 85 ff 0f 84 93 00 00 00 <48> 8b 07 48 85 c0 0f 84 af 00 00 00 48 8b 00 48 3d fc 03 00 00 77
[ 1543.998834] python3[24161]: segfault at 7f55107a97b0 ip 00007f55107a97b0 sp 00007fff9ad13218 error 15
[ 1543.998847] Code: 00 00 e0 76 90 00 00 00 00 00 e0 76 90 00 00 00 00 00 e0 57 8f 00 00 00 00 00 e0 76 90 00 00 00 00 00 00 00 00 00 00 00 00 00 <01> 00 00 00 00 00 00 00 a0 f9 8f 00 00 00 00 00 12 00 00 00 00 00
```

$ gnome-shell --version
GNOME Shell 3.38.3

**Comment by rduivenvoorde** [comment]
Mmm, confirmed ( by myself :-) ) on a second laptop running bullseye/sid...

And both in GNOME and in X I get segfaults, when running X I get the following in dmesg:

```
[ 1322.120133] gnome-shell[1363]: segfault at 30 ip 00007f8b954f103d sp 00007fff5cd8bf70 error 4 in libgobject-2.0.so.0.6600.6 (deleted)[7f8b954ca000+2f000]
[ 1322.120152] Code: 8b 1c d8 48 85 db 0f 84 11 ff ff ff e9 01 ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 48 83 ec 08 48 85 ff 0f 84 93 00 00 00 <48> 8b 07 48 85 c0 0f 84 af 00 00 00 48 8b 00 48 3d fc 03 00 00 77
[ 1322.288260] rfkill: input handler enabled
[ 1327.882281] rfkill: input handler disabled
[ 1351.243228] rfkill: input handler enabled
[ 1358.876172] rfkill: input handler disabled
[ 1538.128927] gnome-shell[23629]: segfault at 400000190 ip 00007fa252b7a03d sp 00007ffcc57aa0e0 error 4 in libgobject-2.0.so.0.6600.6[7fa252b53000+2f000]
[ 1538.128987] Code: 8b 1c d8 48 85 db 0f 84 11 ff ff ff e9 01 ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 48 83 ec 08 48 85 ff 0f 84 93 00 00 00 <48> 8b 07 48 85 c0 0f 84 af 00 00 00 48 8b 00 48 3d fc 03 00 00 77
[ 1543.998834] python3[24161]: segfault at 7f55107a97b0 ip 00007f55107a97b0 sp 00007fff9ad13218 error 15
[ 1543.998847] Code: 00 00 e0 76 90 00 00 00 00 00 e0 76 90 00 00 00 00 00 e0 57 8f 00 00 00 00 00 e0 76 90 00 00 00 00 00 00 00 00 00 00 00 00 00 <01> 00 00 00 00 00 00 00 a0 f9 8f 00 00 00 00 00 12 00 00 00 00 00
```

$ gnome-shell --version
GNOME Shell 3.38.3

**Comment by zoldalma999** [comment]
Python 3.9 and pygame 1.9.6 seems like a weird combination as I don't think pygame 1.9 supports that version. Are you sure those are correct? If so can you try it using pygame 2.0.1?

**Comment by rduivenvoorde** [comment]
> Python 3.9 and pygame 1.9.6 seems like a weird combination as I don't think pygame 1.9 supports that version. Are you sure those are correct? If so can you try it using pygame 2.0.1?

Yep, installing 2.0.1 in a virtual env, I can *NOT* get wayland or X to crash. 

1.9.6 is shipped with Debian, so I started coding with that, noted the crash and then started to 'play' the demo.

**Comment by rduivenvoorde** [comment]
> Which flappy bird tutorial?

See intro of bug: youtube link is tutorial, github link is accompanying code (to be used to reproduce crash: "python3 flappy.py")

> What happens with X with a normal window manager like sawfish/metacity?

I'm no window manager guru:
- Wayland/Gnome crashes hard (after some time): black screen
- X crashes only the application (X keeps running only app is killed)

> Does this happen when you install pygame via pip?

- I installed 2.0.1 via PIP: no crash
- I used 1.9.6 via packagemanager

> Does this happen when you install pygame from source?

Dunno

> And the inevitable follow-up questions:
> Did you file a bug with debian?

Yes, just did, will post url here later

> Did you file a bug with gnome-shell?

Nope, not yet.

**Comment by robertpfeiffer** [comment]
I hate doing this, but your problem does not sound like a bug in PyGame. It's a bug in gnome-shell. Even if the Python process were to segfault because of a programming bug in PyGame, it should not crash the whole GUI session or window manager. It should just close the PyGame window and make the Python process exit un-cleanly. That goes for both Wayland and X11.

There has been a lot of politically charged debate about the switch from X11 to Wayland in recent weeks, so I'll tread as lightly as I can: The way Wayland works (without a display server) ensures pretty much by design that all your windows are lost when your window manager crashes. In X11, if the window manager crashes, you can re-start it, but Wayland avoids overhead by having the Wayland protocol implemented in a library and making the ~~window manager~~compositor process do all the rendering. In this architecture, if the gnome-shell process cannot recover gracefully from exceptions without crashing, you lose your session and all windows. You can consider this a design flaw in Wayland, or a broken promise in gnome-shell. Wayland compositors are supposed to try extra hard not to crash because of this.

Additionally, 1.9.6 is an old version of PyGame, and we cannot and will not continue developing it, because it is based on SDL1.2, which is also not developed any more. You can complain to the Debian people, but I don't want this to develop into another xscreensaver situation (https://www.jwz.org/blog/2016/04/i-would-like-debian-to-stop-shipping-xscreensaver/). It is very unfortunate for beginners if PyGame, which is the basis for many learn-to-code tutorials, causes gnome-shell to crash on Debian testing, but there is nothing we can do about it, apart from waiting for Debian to adopt a newer version of PyGame, and waiting for gnome-shell to fix that segfault.

PyGame 1.9.6 and SDL 1.2 were not developed with Wayland in mind. If you create a window with PyGame 1.9.6 inside a Wayland session, it will use the X11 protocol, and create a window via the Xwayland compatibility layer. If you use Pygame 2.0, it will use the native Wayland implementation from SDL2.

Just like PyGame 1.9 and SDL1.2 are not developed any more, X11 is not developed any more, and the X11 developers have moved on to working on Wayland stuff. I'm not disparaging or judging them for abandoning a "stable" code base for similar reasons.

To re-iterate:
- This is not a bug in Python 1.9.6
- Debian is behind upstream PyGame (because PyGame 2.0 was released last October, and Debian just doesn't move that fast)
- This is probably not even a bug in Wayland itself, either (unless you manage to reproduce it on Weston)
- This is probably a bug in gnome-shell, as it happens on both X11 and Wayland with gnome-shell
- Bugs in gnome-shell hit extra hard on wayland.

You should probably file a bug against gnome-shell on Debian or upstream. If you do, it's probably a good idea to post whatever you posted here, plus information about your GPU and graphics drivers. Wayland compositors and compositing X11 window managers can be really finnicky about graphics cards and drivers. Be as specific as possible about the version of your drivers, especially if you are using closed-source graphics drivers.

In case a member of the Debian Python team is reading this: Don't be a stranger! Also I am sorry I sent somebody to file a bug report against your pygame package instead of gnome-shell.

**Comment by rduivenvoorde** [comment]
@robertpfeiffer thanks for your thorough answer!

It's clear to me. Debian is currently in soft-freeze if I am correct, so I doubt they will upgrade pygame (while I think they should)...
As said I've created an issue, but think that Debian will ship as is.

I'm also not sure if I should create a Gnome issue, as I can not reproduce it in newer versions, and I'm not sure if it is worth (testing/debugging) energy with an old pygame version... (I'm rather deep into the QGIS community and we have exact this kind of resource problems)...

Anyway, thanks for the answer!
