### ISSUE TITLE
mixer.find_channel() documentation is wrong

### ISSUE THREAD

**Issue by queueseven** [pygame/pygame#2489]
`mixer.find_channel()`'s [documentation](https://www.pygame.org/docs/ref/mixer.html#pygame.mixer.find_channel) says there's a keyword argumend called `force`:

    find_channel(force=False) -> Channel

but it's actually not keyword argument:

```
❯ python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 2.0.1 (SDL 2.0.14, Python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.init()
(7, 0)
>>> pygame.mixer.find_channel(force=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: find_channel() takes no keyword arguments
>>> pygame.mixer.find_channel(False)
<Channel object at 0x0000018435277A10>
>>>
```

**Comment by MyreMylar** [comment]
The above PR should make force into a keyword argument. I noticed while writing a test for this function (the mixer module is currently the largest one remaining without tests for many functions), that the documentation for this function is wrong as it implies that `set_reserved()` affects `find_channel()` - it doesn't, since all we are doing is wrapping some SDL Mixer functions that don't have that functionality. Right now `find_channel()` will find reserved channels, but it won't find busy channels (unless you use force).
