### ISSUE TITLE
Fatal Python error: (pygame parachute) when calling pygame.mixer.pre_init with a device name.

### ISSUE THREAD

**Issue by csarami** [pygame/pygame#2493]
**Environment:**
I am on macOS Mojave and installed the latest version of PyGame. I am running the code in the native Mac terminal.

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** MacOS Mojave.
- **Python version** 3.7.6

When I run the following code to change the output device with a device name as follows:

```
import pygame
import pygame._sdl2 as sdl2
pygame.init()
num = sdl2.get_num_audio_devices(0)
names = [str(sdl2.get_audio_device_name(i, 0), encoding="utf-8") for i in range(num)]
dev_name = names[0] # device number 
pygame.mixer.pre_init(devicename= dev_name)
```
It returns the following error with the mac error message to quit python as in the screenshot below. I tried this with the string literals such as:  "Sennheiser USB headset" or b'"Sennheiser USB headset" which are values returned from list "names" in above code. All of them return the same error as below.

![image](https://user-images.githubusercontent.com/11630582/108458278-5a1a1980-7242-11eb-96af-13f9dcb8ce8c.png)

Any help would be much appreciated.

**Comment by Starbuck5** [comment]
1.) I wasted so much time debugging this not realizing that running something from the command line wouldn't play sound because it stops all the pygame stuff quicker than my IDE ...

2.) csarami, I got you!

```
import pygame
import pygame._sdl2 as sdl2

pygame.init()
num = sdl2.get_num_audio_devices(0)
names = [str(sdl2.get_audio_device_name(i, 0), encoding="utf-8") for i in range(num)]
dev_name = names[1] # device number 

print(dev_name)
pygame.quit()

#pygame.mixer.pre_init(devicename= dev_name)
pygame.mixer.init(devicename = dev_name)
pygame.init()


s = pygame.mixer.Sound("pygame/examples/data/car_door.wav")

s.play()

screen = pygame.display.set_mode((200,200))

clock = pygame.time.Clock()
while True:
    clock.tick()

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit

    if pygame.time.get_ticks() > 500:
        pygame.quit()
        raise SystemExit
```

The event loop stuff at the bottom just makes it work when executed from the command line. If you want it to look headless add `pygame.HIDDEN` to set_mode.

Here's what happens:
- `pygame.init()` calls `pygame.mixer.init()` automatically.
- However, you need pygame to be initialized to get the audio devices.
- Solve this by initializing pygame, and then quitting.
- You can reinitialize with the device names in hand, and directly initialize the mixer with your setting.
- Play sound.
- Profit!

**Comment by csarami** [comment]
Thank you very much @Starbuck5 ! It works like a charm!
