### ISSUE TITLE
Unable to open PNG file on Raspberry Pi

### ISSUE THREAD

**Issue by matt-hu** [pygame/pygame#2503]
**Environment:**

- **Operating system**:  Linux(Debian - Raspberry Pi OS 32bit)
- **Python version**: 3.7.3
- **SDL version**: SDL 2.0.9
- **PyGame version**: 2.0.1
- **Relevant hardware**: Raspberry Pi 3B+

**Current behavior:**

When I run some code that loads in a PNG image on the raspberry pi, it doesn't work (complains about it not being a Windows BMP file). This is not the case when I run the code on my laptop (x86_64) in both Linux(Linux Mint 20.1) and Windows 10.

It may be something I don't know about or to do with the OS, but I'm not really sure...

**Expected behavior:**

The images are loaded just like on other platforms

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Run the test code below
2. Use a PNG file, any will do (below is one I have verified to cause the error)
![image](https://user-images.githubusercontent.com/70395217/109417445-a3453880-79bb-11eb-81eb-4aec59f6585c.png)

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.init()
pygame.image.load('image.png')
```

**Stack trace/error output/other error logs**

```
Traceback (most recent call last):
File "imageloadtest.py", line 3, in <module>
    pygame.image.load('image.png')
pygame.error: File is not a Windows BMP file
```

**Comment by galexandreg** [comment]
I'm going to guess you compiled Pygame yourself?
Does it work if you use the build on pywheels? (pip on RaspberryPi OS should use Piwheels by default)
If so, you probably compiled without libpng and libjpeg. They are optional for pygame, but you need them if you want to use the extended image formats.

**Comment by matt-hu** [comment]
No, I used pip to install pygame...

**Comment by galexandreg** [comment]
Ah... I think I understand the problem. The pygame2 wheel is probably looking for some libraries that are not currently installed on your system. It works on Windows because they are bundled with pygame...

Do you have libsdl2-image-2.0-0 installed? If not, that's probably the problem. The SDL1 version is included by default in RaspberryPi OS (and used by the included pygame version), but you need to install it yourself for pygame2 (SDL2).
`apt-get install libsdl2-image-2.0-0` should fix the problem.

I'm not sure, but you might need to do the same for audio and font support (`libsdl2-ttf-2.0-0` and `libsdl2-mixer-2.0-0`)

**Comment by matt-hu** [comment]
@galexandreg Thank you so much! That has fixed it completely!
