### ISSUE TITLE
Implement SDL_ComposeCustomBlendMode

### ISSUE THREAD

**Issue by queueseven** [pygame/pygame#2522]
Would be nice to have SDL_ComposeCustomBlendMode supported :-)

See https://gist.github.com/queueseven/842d0091efe2d5d6640e6149b32facf4

**Comment by galexandreg** [comment]
I guess it's a good idea too. I'm not familiar with it, but it looks like it's fairly new in the SDL and only available for hardware accelerated renderers (not available for software renderers), so I'm not sure what  would be the best way to support it in pygame. Since pygame is sort of at a higher level of abstraction than the SDL itself, i'm not sure how I feel about having different supported features on different platforms, and I don't know how much the team want the new sdl2 things to be compatible with the old stuff in the end...
But I don't see why it shouldn't be available somewhere anyway for people who want it.

I think it would also be a good idea to make the SDL_BlendFactors and SDL_BlendOperations constants available from pygame (like the blendmodes already are with pygame.BLENDMODE_NONE, BLEND, ADD and MOD.

You can make a pr and see what the others (who probably know more about that stuff than me) think about it 😉.

**Comment by queueseven** [comment]
> I guess it's a good idea too. I'm not familiar with it, but it looks like it's fairly new in the SDL and only available for hardware accelerated renderers (not available for software renderers), so I'm not sure what would be the best way to support it in pygame. Since pygame is sort of at a higher level of abstraction than the SDL itself, i'm not sure how I feel about having different supported features on different platforms, and I don't know how much the team want the new sdl2 things to be compatible with the old stuff in the end...
> But I don't see why it shouldn't be available somewhere anyway for people who want it.
> 
> I think it would also be a good idea to make the SDL_BlendFactors and SDL_BlendOperations constants available from pygame (like the blendmodes already are with pygame.BLENDMODE_NONE, BLEND, ADD and MOD.
> 
> You can make a pr and see what the others (who probably know more about that stuff than me) think about it 😉.

I'm not sure how to add constants the right way; there seem to be multiple macros, which one to use? Also, should I add the cython generated code to the PR? 🤷‍♂️

**Comment by galexandreg** [comment]
I must say i'm not sure either... perhaps it's better if they are only available in _sdl2 anyway since they can't be used anywhere else. As you said, this _sdl2 stuff is experimental and I don't think there is a real plan yet. I would only make them available in the _sdl2 module... but perhaps others will have better ideas later.

For the cython stuff, yes, you should add the .c generated files to the pr.
