### ISSUE TITLE
I don't know how to upload an image using pygame in Pycharm . !!!

### ISSUE THREAD

**Issue by python-begginer1401** [pygame/pygame#2541]
<img width="804" alt="Screen Shot 2021-03-29 at 6 48 14 PM" src="https://user-images.gi
<img width="804" alt="Screen Shot 2021-03-29 at 6 48 14 PM" src="https://user-images.githubusercontent.com/81578279/112863387-791c8e80-90bf-11eb-9e16-fe3323a91abc.png">
thubusercontent.com/81578279/112863277-5db18380-90bf-11eb-9eb9-199fc51fecdb.png">

**Comment by galexandreg** [comment]
Two ideas:
-Is the background-night image is in the same directory as the program?
-Perhaps you forgot about the extension in the file name (.png, .gif or anything...) in `pygame.image.load("background-night")`

But in the end, this is an issue tracker for pygame itself, not a place to get help using it, so I will close the issue. Your problem is probably one of the two things I said anyway. 🙂

I'm not sure where it's the best for you to go to get help... I know there are a few unofficial programming/pygame discord servers. You could also try the pygame subreddit. https://www.reddit.com/r/pygame/
