### ISSUE TITLE
pygame.Font.textToPoints functionality 

### ISSUE THREAD

**Issue by Ari24-cb24** [pygame/pygame#2562]
**Description**

So p5js got a really cool function called "textToPoints" in the Font Object (see https://p5js.org/reference/#/p5.Font/textToPoints). This function allows to get the positions of the boundary of a specific font drawen on the screen. Daniel Shiffman already experimented with that function around (https://www.youtube.com/watch?v=4hA7G3gup-4&list=PLRqwX-V7Uu6ZiZxtDDRCi6uhfTH4FilpH&index=77&t=360s&ab_channel=TheCodingTrain) and I think this would be a pretty cool functionality to have in pygame. Pygame is in is in my opinion the p5 what javascript has but in python.

**Comment by Starbuck5** [comment]
Hey, sorry no one ever responded. I remember reading this when you posted it.

You've probably forgotten about this issue by know, so you'll get a weird notification from this :smile:

I'm going to close this issue because, although it would be cool, no one has expressed interest in working on it, and I know it would be quite hard to do, as this functionality is not provided by our backend font rendering library.
