### ISSUE TITLE
pygame wheel for raspberian stretch on piwheels not working

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2595]
See issue https://github.com/piwheels/packages/issues/208

Anyone have a pi and able to help?

**Comment by ankith26** [comment]
Maybe I can test this, I'd have to do a fresh reinstall, because I do not have stretch on any of my Pis

**Comment by bennuttall** [comment]
Stretch doesn't run on the Pi 4 - so use a Pi 3, and not aarch64. I can give you access to a cloud Pi if it helps.

**Comment by ankith26** [comment]
Yes, a cloud pi would be really helpful. I do not have a spare SD card, and my Pi's are all loaded with buster, and ATM I cannot get stretch on them. This issue does not replicate on buster, I've tested that already a while back

**Comment by illume** [comment]
Seems like this has been fixed on the piwheels side somehow.

Related to NFS and the korean file names somehow (I think?).

**Comment by ankith26** [comment]
I think that we should be removing the korean docs (or atleast moving it to a seperate place, rather than pygame source)

Mainly because I don't think the korean docs are that widely used, that they need to be in the source of pygame. Also, there are some weird issues that crop up with it, like this raspi build issue for instance, and also, while I was locally building pygame with pypy2 windows and pip (pypy2), it started throwing of errors and refused to compile (pip complaining about unknown characters)

**Comment by carlosperate** [comment]
Would it be enough to exclude the directory in a manifest file or setup.py?

**Comment by ankith26** [comment]
So IG this issue can be closed, the latest pygame version `pygame==2.0.3` has piwheels wheels on PiOS stretch (with python 3.5)
And we are probably dropping 3.5 support in the next pygame version
