### ISSUE TITLE
pygame.FULLSCREEN does not trigger exclusive fullscreen on Windows.

### ISSUE THREAD

**Issue by carstenschwede** [pygame/pygame#2626]
Using `pygame.FULLSCREEN` as a flag for `.set_mode()` opens a borderless window at screen dimension, but does not trigger exclusive fullscreen necessary to unlock high framerate and circumvent DMW.

**Comment by robertpfeiffer** [comment]
This is intentional. Hardware fullscreen is almost always the wrong choice. It's not the 90s any more. Most users want to record games with OBS and to be able to alt-tab out of their games.

Is this you? https://www.reddit.com/r/pygame/comments/o135wt/unable_to_start_pygame_in_exclusive_fullscreen_as/

I don't know what you mean by "unlock high framerate", but I'd suggest for your use case, you probably want to write DirectX or OpenGL directly, and use a language other than Python - probably C or C++ with SDL2 - because there is no platform-independent _and portable_ way to do what you want on top of PyGame anyway, and Python has a lot of overhead that will eat into your framerate more the higher your framerate is. 

I don't know if you want to use G-Sync or FreeSync or adaptive VSync or triple buffering or to disable VSync and run at 1000FPS. The interpretation that makes the most sense is that your monitor runs at 120Hz, but your window manager runs at 60FPS.

Any fine-grained API for frame rate and VSync is hard to write in a portable way, and would run the risk of making games written in PyGame less portable between operating systems or even GPU vendors.

Please explain your use case and what exactly you are trying to do.

**Comment by carstenschwede** [comment]
Goal was to measure the lowest possible input lag across platforms. A cross-platform gaming library seemed to be a good fit and I hoped it was sympathetic to achieving lowest possible input lag across platforms. With VSYNC turned off, the same PyGame has 16ms higher input lag on Windows (vs Mac), because the fullscreen mode is not exclusive and Windows DWM will perform triple buffering.

I had hoped it's just a different flag to open PyGame in exclusive fullscreen. If this is indeed not easily achievable I'll follow your recommendation and go with direct C++/OpenGL.

Do you happen to know if there is any "injection" type method/tool to have an existing (borderless fullscreen window) binary use "exclusive fullscreen" instead?

**Comment by robertpfeiffer** [comment]
So you're measuring gamepad driver latency across operating systems on the same hardware?

I know there is a flag to bypass compositing on X11 even in windowed mode, but that is kind of hacky. In any case, the vsync parameter should be meaningless (whether it is on or off) if you are just pushing pixels in software, without flags like OPENGL or SCALED that involve the GPU.

As of right now, if you change the physical screen resolution, you might trigger a code path that bypasses the window manager. Something like `pygame.display.set_mode((800,600), pygame.FULLSCREEN)` might do the trick. I normally recommend against this exactly _because_ it bypasses the window manager.

**Comment by carstenschwede** [comment]
Currently I am only considering Windows and Mac (no X11) and I am interested in end-to-end latency (so not only software but the whole input-to-display pipeline). Disabling VSYNC reduces latency as the software is not forced to wait to render the next frame and if your panel scanout is synced to your cable scanout you can achieve latencies lower than one display refresh cycle. With framerates higher than the display refresh rate you can have multiple frames in the same picture (tearing) where lower parts of the screen have lower latencies.

This works as expected on Mac. But on Windows this only works for "exclusive fullscreen" applications, regular fullscreen is a "borderless fullscreen sized window" for which Windows will keep DWM enabled. DWM forces "triple buffering" which may wait as long as one refresh cycle before presenting the latest frame. This means no tearing but also worse "worst case" latencies and no lower latencies for bottom parts of the image.

As I wrote in the initial post `.set_mode((width,height),pygame.FULLSCREEN)` does not trigger exclusive fullscreen. I am not sure what you meant by "changing physical screen resolution" but using `width` and `height` values that differ from the actual physical screen resolution does not produce a different result.

**Comment by robertpfeiffer** [comment]
> using width and height values that differ from the actual physical screen resolution does not produce a different result.

It does on some platforms, and that's bad for end users. It's almost always the wrong choice, which is why pygame 2.0 has a way to scale up the window in software.

> Enabling "exclusive fullscreen" for PyGame on Windows would reduce worst case latencies by roughly one frame (16.6ms on 60Hz display) and best case latency to almost zero

That's a very misleading statement. You want to disable "every frame is perfect" guarantee of the windows and wayland frame buffers so you can get torn frames. The 16.6 milliseconds apply only to those frames that are on the threshold. Triple buffering does not add response times of one frame, it unlocks the frame rate and allows your game to run as fast as it can!

I originally thought the problem was you have a HRR display connected to a system running at 60Hz refresh rate is Desktop mode. I know it's possible to change the display refresh rate in-game in a platform-specific way. I know some gaming laptops are configured to run the desktop at 60Hz to save battery, even though their displays support higher refresh rates.

Until there is a portable way to query monitor refresh rates and blocking/buffering behaviour, there is nothing we can add to pygame to make this easier without making the experience worse for most users.

I suggest you write your benchmark directly in C with SDL2 (https://wiki.libsdl.org/SDL_SetWindowFullscreen) and OpenGL.

**Comment by carstenschwede** [comment]
>> Enabling "exclusive fullscreen" for PyGame on Windows would reduce **worst case** latencies by roughly one frame (16.6ms on 60Hz display) and best case latency to almost zero

> That's a very misleading statement. Triple buffering does not add response times of one frame...

I agree that this would be misleading on its own, which is why I did not claim that. My point was that the **worst case** latency of (VSYNC OFF + Exclusive Fullscreen) is roughly one frame lower than the worst case latency of (Regular Fullscreen / VSYNC ON / Triple Buffering). It is impossible to have worst-case latencies lower than one refresh cycle in VSYNC ON (Triple Buffering does not change that) but it is possible with VSYNC OFF. The difference is (as you noted) tearing at higher framerates.

But I am totally fine with you having VSYNC ON as your baseline and saying that you prioritise non-tearing over low-latency.  👍

> I suggest you write your benchmark directly in C with SDL2

Thanks for your time, will do!
