### ISSUE TITLE
Wrong architecture on Apple M1  (no suitable image found)

### ISSUE THREAD

**Issue by emign** [pygame/pygame#2628]
I want to run a simple example py application.
Python: 3.9.5 universal binary
Pygame: 2.0.1 via pip
macOS Big Sur 11.3
Apple M1 MacBook Air and Apple Mac mini M1

```
(base) user@MacBook-Air-von-User ~ % python3.9 -m pygame.examples.aliens
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/pygame/__init__.py", line 81, in <module>
    from pygame.base import * # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ImportError: dlopen(/Users/user/Library/Python/3.9/lib/python/site-packages/pygame/base.cpython-39-darwin.so, 2): no suitable image found.  Did find:
  /Users/user/Library/Python/3.9/lib/python/site-packages/pygame/base.cpython-39-darwin.so: mach-o, but wrong architecture
  /Users/user/Library/Python/3.9/lib/python/site-packages/pygame/base.cpython-39-darwin.so: mach-o, but wrong architecture
(base) user@MacBook-Air-von-Nicolai ~ % 
```

**Comment by Starbuck5** [comment]
This sounds to me like you're using python running natively on ARM, because you have a universal binary, but it doesn't work with pygame compiled for a x86 system. (As pygame from pip would be)

Perhaps compiling from source natively would fix the problem for you. There are instructions for that here: https://www.pygame.org/wiki/MacCompile?parent=

Alternatively, I bet running an x86 version of python would have your Mac use the rosetta 2 emulator, which would enable pre compiled pygame to work. But the first solution would be more elegant.
