### ISSUE TITLE
Remove dead links on pygame website

### ISSUE THREAD

**Issue by PotatoWatch** [pygame/pygame#2632]
Most of the games have dead links

**Comment by Grimmys** [comment]
What do you mean by games with dead links? 

You mean the projects that can be found on this page: [https://www.pygame.org/tags/all](https://www.pygame.org/tags/all)?

Unfortunately they have been made by users, it's not like if they were official games sponsored by pygame. 
In my opinion, we can't remove game with dead links because first there are way to many, and next I think it's not cool too remove users' entries only because of that. They are free to update their entries whenever they want.

**Comment by PotatoWatch** [comment]
Okay then.
