### ISSUE TITLE
Use Sequence instead of List for read-only parameters

### ISSUE THREAD

**Issue by vnmabus** [pygame/pygame#2680]
The following definition used to initialize Surface should be made more flexible, allowing `Sequence[float]` instead of `List[float]`.
https://github.com/pygame/pygame/blob/cbf4c674f568b5a17e13b0a697b43503936a883f/buildconfig/pygame-stubs/surface.pyi#L28
Note that as `List[float]` is invariant instead of covariant, the current implementation does not even allow to pass a `List[int]`!!

**Comment by Starbuck5** [comment]
Speaking of Surface type things, Surfaces can be constructed with floats, but if the argument is wrong it asks for ints.

```
>>> pygame.Surface(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: size needs to be (int width, int height)
```

See: https://github.com/pygame/pygame/blob/main/src_c/surface.c#L614-L626

**Comment by vnmabus** [comment]
A list of integer does not typecheck, as `List` is not covariant.

**Comment by Starbuck5** [comment]
> A list of integer does not typecheck, as List is not covariant.

Ok, I understand I think. A quick check of the typing docs doesn't pop up that Sequence would be covariant, where List wouldn't be. But I don't really fully understand, since I first heard about covariance 20 mins ago 😅. 

Anyways, I think it would be cool if you made the changes you want to do, and also fix that Surface thing I pointed out. Changing the Surface will require building from source to test your change, these are our help pages: https://www.pygame.org/wiki/Compilation. Can I assign you to these 3 issues?

**Comment by MyreMylar** [comment]
Short answer, mypy treats the float type as equivalent to int or float always. This is the 'numeric tower' and also includes the 'complex' type - which accepts complex, float and int.

Longer answer:

https://stackoverflow.com/questions/50928592/mypy-type-hint-unionfloat-int-is-there-a-number-type

**Comment by MyreMylar** [comment]
After looking at it I think every instance of `Union[Tuple[float, float], List[float, float]]` can be safely changed to `Sequence[float, float]`. It means the same thing.

**Comment by vnmabus** [comment]
> Short answer, mypy treats the float type as equivalent to int or float always. This is the 'numeric tower' and also includes the 'complex' type - which accepts complex, float and int.
> 
> Longer answer:
> 
> https://stackoverflow.com/questions/50928592/mypy-type-hint-unionfloat-int-is-there-a-number-type

I knew that, but note that as `List` is mutable, it is not covariant, so that `List[int]` is NOT a subtype of `List[Union[int, float]]` or the equivalent `List[float]`.

**Comment by vnmabus** [comment]
> After looking at it I think every instance of `Union[Tuple[float, float], List[float, float]]` can be safely changed to `Sequence[float, float]`. It means the same thing.

Note that using `Sequence` one is not supposed to modify it (which is the usual case anyway). Also `Sequence` and `List` only have a type argument, not two.

**Comment by MyreMylar** [comment]
Ah right, I forget that Lists aren't supposed to have a set length. So I suppose we should still keep a Union then because the two item tuple is useful for setting expectations for this argument. So:

`_Coordinate = Union[Tuple[float, float], Sequence[float], Vector2]`

As an aside, I'm not sure the mutability rules of lists will have much impact here after reading up on the trouble you can get into with that, purely because both float and int are immutable basic types which seems like it would limit those dangers. i.e. while a list of custom class `B(A)` is not the same as a list of custom class `A()` and an `A` might not have methods that a `B` does - a list of `float` is basically the same as a list of `int` for pretty much every operation I can think of. But who knows.

**Comment by vnmabus** [comment]
I just tried to say that if you type it as a list of floats Mypy wouldn't let you pass a list of integers, as lists are invariant (that was how I found the bug in the first place). Sequences are fine, as they are covariant.
