### ISSUE TITLE
Fix type hint of get_pressed() in mouse.pyi

### ISSUE THREAD

**Issue by shingo-kagami** [pygame/pygame#2684]
Since the parameter `num_buttons` of `pygame.mouse.get_pressed` is optional with the default value 3, the correct type hint for it would be something like `int = 3` or `typing.Optional[int]`.

https://github.com/pygame/pygame/blob/34acc0edff5ce6dee6126d6cf07113ac5547fb37/buildconfig/pygame-stubs/mouse.pyi#L6

**Comment by Starbuck5** [comment]
It actually shouldn't be `Optional`, see #2678. `Optional` is shorthand for `Union[None, stuff]` rather than for a default argument. Confusing naming by the typing folks, though.

`int = 3` would work great though.

Since it's a simple fix I'm assigning you to the issue, because if you can point out the exact line you can also fix it. But of course if you don't want to I'll unassign you. 😄
