### ISSUE TITLE
SDL2 video ideas

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2691]
I've been keeping these close to my chest for a while, but I have some ideas for the _sdl2.video system.

Listed somewhat in order of **radicalness**:

- Give Textures and Images a get_width(), get_height(), and get_size() like surfaces
- get rid of read only attributes, they aren’t the easiest to document, and are potentially confusing
- Construct a Texture from a surface through the Texture constructor
- Rename renderer.present() to .flip() / .update()
- Add Window.get_surface() / make normal rendering possible with multiple Windows
- Change renderer.fill_rect to impersonate Surface.fill
- Change renderer draw methods to take a color directly, rather than the current “c like” set color flag then draw system.
- pygame.draw compatibility (Is this a good time for SDL_RenderGeometry, coming in 2.0.18?)
- Eliminate Image objects, add Texture.subtexture
- Add compatibility for drawing surfaces onto Renderer, by making a streaming Texture the size of the Renderer, and putting surface data into there before drawing it onto the Renderer. Some things are always going to be Surfaces, and this saves people the trouble of adding a conversion step for dynamic surfaces like Text rendered every frame.
- pygame.transform compatibility (transform.flip() could set flipX, flipY flags, for instance)

**Comment by mcpalmer1980** [comment]
• get_width()/height() is fine and important to fit the pygame design, but I prefer variables over function calls, and performance might be better
    • I like your idea about the texture constructor, but I have gotten used to calling Texture.from_surface()
    • Both renderer.present() and renderer.update() make sense to me, but not renderer.flip(). 
    • Windows should definitely have a get_surface() and get_renderer() method, as well as get_textures() : []
    • I'd like both Color objects and tuples as color values for renderer.draw() and everywhere else colors are passed.
    • Surface drawing into a renderer is an important feature, especially for newbies and those translating to sdl2.video. I create a streaming texture for my window, which makes screen transitions and window size scaling much easier. If a default streaming buffer is created (optionally or mandatory) it should be accessible and documented for users to play with themselves. My texture buffer is set to the render resolution though, not the window size, that way my game logic renders to a locked render size and the video backend handles the scaling to whatever the window size happens to be
    • I don’t use the same buffer for text because my font renderer is plenty fast enough and allows for interesting per character effects. I think a new font compatible class should be created that renders characters from texture memory.
    • Not sure what you meant about transform compatibility. I like setting flip and rotation flags during texture drawing.
    • I disagree with removing Images. I think Images and Textures should be interchangeable and offer the same feature set. But Textures should always represent actual textures in memory and images should always represent a portion of an existing texture. This perspective comes from someone who never used subsurfaces (I blitted rect regions because I didn’t know about them).

Two things I want in the next pygame revision.
    • Rect.scale(scalar, optional scalar_height)
    • FloatRect with a get_int_rect() method

**Comment by Mega-JC** [comment]
I've been looking into `pygame._sdl2.video` since 2020, and although it is mostly usable, there is still a lot of room for improvement.

> - Give Textures and Images a get_width(), get_height(), and get_size() like surfaces

Agreed, sticking to getter and setter functions would help with making the API more similar to surfaces ergonomics-wise.

> - get rid of read only attributes, they aren’t the easiest to document, and are potentially confusing

+1

> - Construct a Texture from a surface through the Texture constructor

I'm not too sure about this, since surfaces and textures are quite different even if they both hold image data (and it's worth communicating that difference to users). In addition, the `SDL_CreateTextureFromSurface` function used in the module would block other texture access targets like `target` or `streaming` (see https://www.pygame.org/docs/ref/sdl2_video.html#pygame._sdl2.video.Texture and https://wiki.libsdl.org/SDL2/SDL_CreateTextureFromSurface) from being set in the constructor, thereby leading to confusion.
I think `Texture.from_surface()` is the better option here.

> - Rename renderer.present() to .flip() / .update() 

This makes sense to improve familiarity, but maybe we should only add `.update()`. Keeping `.present()` would be good too,  as that helps with those familiar with SDL2.

> - Add Window.get_surface() / make normal rendering possible with multiple Windows

This would be a great feature, but it would be nice if we could somehow expose `Window` objects in `pygame.display` for Surface rendering instead, as mixing these two ways of managing displays/windows could be confusing.
Maybe as `pygame.display.create_window()`, as a more flexible alternative to `set_mode` that also creates new windows. In order to know which window to update when using `pygame.display`, `pygame.display.flip_window(my_window)` and `.update_window(my_window)` could be added.

> - Change renderer.fill_rect to impersonate Surface.fill

Makes sense.

> - Change renderer draw methods to take a color directly, rather than the current “c like” set color flag then draw system.

+1

> - pygame.draw compatibility (Is this a good time for SDL_RenderGeometry, coming in 2.0.18?)

This is possible, but could take a while given the size of `pygame.draw`. Since 2.0.18 has been out for a while, I think exposing `SDL_RenderGeometry` on the renderer at the beginning would be good idea before doing this, as Avaxar started doing in #3006 .

Honestly though, given the fact that this is a new API and that `pygame.draw` is already pretty complex (I still remember there being plans to merge `pygame.gfxdraw` into `pygame.draw`!), I think it would be easier to start from scratch inside another module, something like `pygame.texdraw`, as a drawing module only aimed at textures. Since the implementation could use `SDL_RenderGeometry` under the hood, it wouldn't be too difficult to implement an API similar to `pygame.draw`, where shapes are approximated using triangle fans and drawn with `SDL_RenderGeometry`. We could even go further and provide things like `angle` and `shear` to the drawing functions, since we'd be working with 2d points. Rendering polygon shapes could be implemented as well, if we find a good triangulation algorithm.

- Eliminate Image objects, add Texture.subtexture

This makes sense, as the name "image" currently being used for `Image` objects is not very accurate, since they don't actually hold image data on their own.

> - Add compatibility for drawing surfaces onto Renderer, by making a streaming Texture the size of the Renderer, and putting surface data into there before drawing it onto the Renderer. Some things are always going to be Surfaces, and this saves people the trouble of adding a conversion step for dynamic surfaces like Text rendered every frame.

This could be done, especially since `Renderer.blit` already exists, however it will be slower than using textures for drawing things as well as working with surfaces and a normal display surface directly (RAM to VRAM data transfer generally isn't fast, unlike RAM to RAM data transfer with normal surface rendering), which should be communicated to users accordingly. 

As an alternative, we should probably encourage the use of character maps instead (textures with grayscale font glyphs, a very common way of drawing text when doing GPU rendering), with some examples?

> - pygame.transform compatibility (transform.flip() could set flipX, flipY flags, for instance)

I'm not sure this could work, since almost all functions in `pygame.transform` return surfaces.

**Comment by Mega-JC** [comment]
Another idea I'd like to suggest is to remove `Texture.get_rect`, as I've seen the method confuse way too many beginners when using `pygame.Surface`. It's a `Rect` creation shorthand confusingly named as a getter, which implies that `Surface`/`Texture` objects already have some kind of `Rect` as a position.

Since it's nonetheless a useful shorthand, I'd suggest using a different name if it should be kept, such as `.as_rect()`.
