### ISSUE TITLE
Can i use pygame in a closed-source paid game?

### ISSUE THREAD

**Issue by MayuSakurai** [pygame/pygame#2716]
Can I use py game in a closed source paid game?

**Comment by ankith26** [comment]
Well first of all, pygame issue trackers are for posting issues pertaining to pygame itself, and not for discussions/asking other questions. But I can answer your question ;)

Keep in mind that I am no lawyer, nor qualified enough to give 100% accurate legal advice, so whatever I say, is only to the best of my knowlegde so take it with a grain of salt (hire a lawyer if your game is big, and you need legal assistance!)

Pygame is distributed under the [LGPL](https://github.com/pygame/pygame/blob/main/docs/LGPL.txt) license. 
The TL;DR of the license is that when you are making copies of pygame itself, you are supposed to ship your library under the same or equivalent license, so basically, you cannot make a closed source copy of the pygame library itself. Here, any changes made to the library itself must be explicitly stated.

However, if you are just using pygame as a dependency to make your closed source game (which I assume is the case), then you can use pygame freely.

Also when your game goes wrong (maybe due to a bug in your code, or a bug in pygame itself), you cannot hold pygame authors as responsible and take legal action against them for any damage that might happen.
