### ISSUE TITLE
Is there a problem / misunderstanding with `Vector.angle_to()`

### ISSUE THREAD

**Issue by Muxelmann** [pygame/pygame#2729]
According to the docs [angle_to()](https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2.angle_to) returns the angle between self and the given vector. But the underlying C code ([link](https://github.com/pygame/pygame/blob/6eb04ef9fcb6dd37aaaa303c2c16daac70ddec8b/src_c/math.c#L2168)) suggests that the angle _between_ two vectors is actually calculated:

```c
angle = atan2(other_coords[1], other_coords[0]) - atan2(self->coords[1], self->coords[0]);
```

Because the function's name suggests calculating the angle _to_ not _between_ two vectors, it may be worth renaming the function, e.g. into a `angle_between()` function, and changing the code of `angle_to()`, e.g. akin to the following calculation:

```c
angle = atan2(other_coords[1] - self->coords[1], other_coords[0] - self->coords[0]);
```

I took the liberty of setting up a pull request here: #2728; but am unsure if the indexing is correct (i.e. if `atan2()` takes (x, y) or (y, x) as indicated by the array access), and if the intention / naming of `angle_to()` was chosen to mean something different in the first place. That said, maybe I am just not used to the convention; in which case, just ignore this issue and the pull request.

**Comment by Starbuck5** [comment]
I don't actually have it in me to check this out right now, but I didn't want to leave you hanging.

Even if it is truly unconditionally wrong, which I doubt, we can't change the behavior that existing games rely upon.

The resolution to this could be a clarification of the docs instead. Maybe we could have some sort of diagram describing what different vector methods do? Since it's quite easy to get confused on them. I frequently do.

Also, you've got pygame compiling well on your M1? I recently spent some time editing the guide for compiling on Macs, and it would be cool if you took a look. https://www.pygame.org/wiki/MacCompile.

**Comment by Muxelmann** [comment]
That makes sense, I didn't consider that people may be relying on the code already, true. When I get around to it, I'll have a look at adding a graph to the docs, explaining what `angle_to()` currently calculates. Maybe adding new functionality as an `angle_to_vector()` function may be the way to go. That way, there should not be any change in / conflict with existing codebase.

I'll also have a look at building pygame for M1 and let you know my milage.

**Comment by bkwabiad** [comment]
I believe the function is denoted is actually. The angle_to() function gives the directed angle between two vectors by computing the angle between vector 2 and the x axis and the original vector and the x axis and subtracts correctly (vector 2 is other, vector 1 is self). 
The equation given above angle = atan2(other_coords[1] - self->coords[1], other_coords[0] - self->coords[0]); would technically give the angle between the difference of these two vectors and the x axis. Arctan applied to these parameters considers the opposite and adjacent sides of a right triangle constructed between the positive x axis and the vector after simple subtraction of vector components. 
I do think however it would be good to have a small diagram and explanation denoting the behavior of this function. If @Muxelmann is not working on this issue at the moment, I could take some time to change the documentation to have clarification for the behavior of this function?

**Comment by donlorenzo** [comment]
Hi there,

I am the original author of the pygame.math module. Sorry for my long absence.
I can confirm that what @bkwabiad wrote in his comment, is the intent of this function and I believe the implementation is (almost) correct.
I did not call the method `angle_between` because it is supposed to be the _directed_ angle _from_ self _to_ the given vector (as @bkwabiad correctly mentioned).

The function should
 * Return the angle (in degrees) between self and the given vector so that when you call `v3 = v1.rotate(v1.angle_to(v2))` then `v3` should point in the same direction as `v2`.
 * The returned angle should be in the semi-open range `]-180, 180]`, i.e. it should be the smallest either clockwise or counter-clockwise rotation.

The current implementation ensures the first point but not the second. This becomes evident when the shortest angle would cross the -y axis (this is where `atan2` has a discontinuity). e.g. `Vector2(0, 1).angle_to(Vector(-1, -epsilon))` would return `-270` instead of `90`.
I am not 100% sure whether we could change the implementation to also ensure the second point or whether that would break someones code.
