### ISSUE TITLE
while loop freezes when i move the window

### ISSUE THREAD

**Issue by kusleikar** [pygame/pygame#2760]
to reproduce simply increment a number when you inside a while loop and move the window. 

import sys
import pygame

pygame.init()

screen = pygame.display.set_mode((800,400))
clock = pygame.time.Clock()

x = 1
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
    print(x)
    pygame.display.update()
    clock.tick(60)
    x += 1

**Comment by MyreMylar** [comment]
Hello,

This happens on Windows largely because of decisions made by Microsoft about what should happen when you are moving a window (i.e. applications operations should be paused until you stop moving the window). Basically windows pauses a programs main thread (the one that handles OS messages) while you are moving the window.

I'm not sure if there is anything we could do to adjust it at the python level as most workarounds I've seen for SDL (the C library underlying pygame) involve using multiple threads in a way that almost certainly wouldn't work well performance wise with python's GIL (the global interpreter lock that makes switching execution frequently between threads both running python code very slow). Anyway, whatever the possibility of it any fix would definitely not be simple.

In my opinion it is better for users to treat it as a fact of life on the windows platform and handle it in your programs. The simplest workaround for most common game application bugs is just to constrain your time delta values to a range of normal operation so that it doesn't grow hugely when the application is paused by the windows messaging system.

**Comment by kusleikar** [comment]
I did manage to fix the problem by running a thread and handling the window using ctypes.windll to keep an active message loop running. But, there is an option in SDL,  https://wiki.libsdl.org/SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP . So I was wondering if that can be enabled when compiling the source under a windows platform. I also made a search to find this in this repository and you guys don't seem to have that anywhere.

**Comment by MyreMylar** [comment]
Did you try:

```
import os
os.environ['SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP'] = "0"
```
?

Obviously we wouldn't want to activate this by default.

**Comment by BozakJay** [comment]
> I did, but what worked for me was passing the window handle that you get when you call get_wm_info() to effectively create a message loop for the current window.

can you share your solution? I'm stuck with the same issue.

**Comment by kusleikar** [comment]
Implement the message loop for your window handle in python using ctypes. Again, this is not something you should be doing that's why I moved to Qt, but pyglet is another alternative you could use if you understand classes intuitively. Or just install Linux, simple fix.

**Comment by BozakJay** [comment]
thanks for the reply, I think I'll try Pyglet before Qt.

**Comment by kusleikar** [comment]
Here's a start up script that you can use.

import pyglet
from pyglet.gl import *
from random import randint


class MainWindow(pyglet.window.Window):
    def __init__(self):
        super(MainWindow, self).__init__(width=800, height=600, resizable=True, vsync=True)


    def on_draw(self):

        glClear(GL_COLOR_BUFFER_BIT)
        glLoadIdentity()
        glBegin(GL_TRIANGLES)
        glVertex2f(0, 0)
        glVertex2f(self.width, 0)
        glVertex2f(self.width, self.height)
        glEnd()

    def on_resize(self,width, height):
        glViewport(0, 0, width, height)
        glMatrixMode(GL_PROJECTION)
        glLoadIdentity()
        glOrtho(0, width, 0, height, -1, 1)
        glMatrixMode(GL_MODELVIEW)

    def on_key_press(self, symbol, modifiers):
        print(symbol, modifiers)

    def on_mouse_press(self, x, y, button, modifiers):
        print(x, y, button, modifiers)


main_window = MainWindow()

pyglet.app.run()

**Comment by Starbuck5** [comment]
There is an SDL issue open about this, which shows people have been discussing this since the beginning of time (or 2013 at least). https://github.com/libsdl-org/SDL/issues/1059

It looks like some sort of optional solution might come soon though, which is cool.

But in the current state of the world, this is a "can't fix" on our end, so I'm going to close this issue.
