### ISSUE TITLE
cannot open the display window

### ISSUE THREAD

**Issue by illume** [pygame/pygame#283]
Originally reported by: **Anonymous**

----------------------------------------

I am using python3.4+pygame1.9.2a. It worked fine before. But the pygame stop working, whenever I used pygame.display.set_mode((300,200)). The pygame window won't pop up and python is not responding. Anyone can help me on this?

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/283

**Comment by MyreMylar** [comment]
Python 3.4 has now reached End of Life, see: https://www.python.org/downloads/release/python-340/. Pygame has changed a lot since this report. 

This is not a general issue with set_mode() and there are no other details to work with - I suspect the anonymous reporter has also moved on with their life in the intervening five years. 

I suspect we should just close this.

**Comment by nthykier** [comment]
I am also for closing this bug given the circumstances.

**Comment by MyreMylar** [comment]
Closing it then.
