### ISSUE TITLE
Pygame causes GIL error when smooth scaling alpha surfaces

### ISSUE THREAD

**Issue by quasar098** [pygame/pygame#2889]
**Environment:**

- **Operating system**: Windows
- **Python version**: 3.9.1
- **SDL version**: 2.0.14
- **PyGame version**: 2.0.1
- **Relevant hardware**: Graphics card is a GTX 1660 SUPER

**Current behavior:**

An error is sometimes raised when trying to smooth scale a transparent object (SRCALPHA flag)

**Expected behavior:**

This should not happen
also this only happens with alpha surfaces for some reasons

**Screenshots**

![image](https://user-images.githubusercontent.com/70716985/144763310-476e520a-5032-4528-88c6-b5245ee56250.png)
![image](https://user-images.githubusercontent.com/70716985/144763333-1467148f-a7ee-4822-b8ed-b9eb1d205a93.png)
caused by line 67

**Steps to reproduce:**

1. Make a surface with SRC
2. Use Smooth scale
3. It crashes occasionally

Other details:
Process finished with exit code -1073740791 (0xC0000409)

**Comment by ankith26** [comment]
Thanks for the bug report! Can you please post a minimal code example (in text) that reproduces this issue?

**Comment by robertpfeiffer** [comment]
Is this just what a segfault looks like with the GIL released, or is this an actual threading problem?

**Comment by MyreMylar** [comment]
Might be related to old issues with threading and smooth scaling seen here:

https://github.com/pygame/pygame/issues/1515

As some GIL changes were made.

I wonder if the small sizes of the surfaces used here are helping cause a race condition. i.e. something is finishing before it would normally because the surface is so small and the GIL is still released (after the changes mentioned in the PR above perhaps?) 

To the OP @quasar098 - it looks like you are doing something similar to what I was back in 2019 and I found then that the `transform.rotozoom` function was more stable while achieving the same result, so perhaps try that and see if your issue is resolved.

**Comment by quasar098** [comment]
i can try to use rotozoom 
thanks for looking into to it

**Comment by ankith26** [comment]
I still cant reproduce the original issue even though I am doing stuff similar to the code in the screenshot. Can you please paste (in text) another minimal reproducer of the problem?

**Comment by yoyoberenguer** [comment]
Did you try to set the smoothscale backend to generic ? to see if this helps

**Comment by quasar098** [comment]
I was reading some docs and read something about it once.
I ended up just using rotozoom and it seemed to not throw any errors
