### ISSUE TITLE
confused when i use sprites in group then kill() and reset other sprites position 

### ISSUE THREAD

**Issue by yviscool** [pygame/pygame#2902]
```python
import pygame

pygame.init()

clock = pygame.time.Clock()

screen = pygame.display.set_mode((500, 500))

run = True

class Fish(pygame.sprite.Sprite):

	def __init__(self, x, y, g):

		super().__init__()

		self.image = pygame.image.load('card_jalapeno.png')

		self.rect = self.image.get_rect()

		self.rect.center = (x, y)

		self.clicked = False

		self.g = g

		self.keys = None


	def reset(self):

		for i in self.g:

			i.rect.x -= 100


	def update(self):

		if not self.clicked:

			pos = pygame.mouse.get_pos()

			if self.rect.collidepoint(pos) and pygame.mouse.get_pressed()[0]  :

				self.clicked = True

				self.kill()
				self.reset()


g = pygame.sprite.Group()


aa = Fish(100, 200, g)
bb = Fish(200, 200, g)

g.add(aa)
g.add(bb)

while run:

	clock.tick(30)

	screen.fill('white')
	g.draw(screen)
	g.update()

	for event in pygame.event.get():

		if event.type == pygame.QUIT:
			run = False

		if event.type == pygame.MOUSEBUTTONDOWN:
			print(pygame.mouse.get_pressed())


	pygame.display.update()

pygame.quit()

```
here is the picture

![card_jalapeno](https://user-images.githubusercontent.com/20163909/145665100-d159d4f0-7edf-4aa2-84f9-6226fc7f5bab.png)

when i run this code,  i click the first card and then reset other cards , but all cards were killed.  whats the matter?
How can i solve this problem

**Comment by MyreMylar** [comment]
Looks like you are moving your second card into the first cards position instantly here:

```
i.rect.x -= 100
```

So the second card will also be detected as collided in the next update loop unless you manage to release the mouse button in a few milliseconds. I might suggest instead activating your code on a single `MOUSEBUTTONUP` event rather than in an update  loop for every card, but there are lots of ways to solve this issue.

In general this github is for bugs/improvements to the pygame library, not for coding issues. Please try the pygame discord or reddit for general pygame usage help.
