### ISSUE TITLE
Add an option to ignore dependencies with pip?

### ISSUE THREAD

**Issue by leha-code** [pygame/pygame#2917]
**Description**

Hello, I am planning to use pygame in Termux, and since portmidi is not yet in termux, pygame fails to build from pip. I would like to have an option to ignore dependencies not from source, from pip. If this is not possible, just close this issue.

**Comment by Starbuck5** [comment]
It might be possible, but it would be work to support it, and it seems like not many people would use it.

We don't even have a programmatic way to do that in setup.py set up. And to add it we would probably have to modularize out all pygame optional dependencies across all OSes and buildconfig scripts, which would be a lot of work.

The way to do this is to setup.py install to generate the SETUP file, then edit SETUP manually, commenting out the pypm line. Then install.

I've built pygame without portmidi many times on Mac, which worked fine (just didn't have pygame.midi ofc). I'm surprised it doesn't do that on Linux? **This seems like the best probable resolution for the issue. If Linux buildconfig crashes without portmidi, we could just make it not.**

Why do you want to do it from pip rather than from source?

**Comment by ankith26** [comment]
First of all, the wheels (binaries) that pygame releases provide are bundled with all dependencies. And if there is a platform you are building pygame on, that does not have prebuilt wheels (in this case android), the pip installer proceeds to compile pygame from source on install. In this case, you need pygame dependencies installed. Like Starbuck pointed above, you need to comment out parts of the `Setup` file to indicate which bits of pygame you don't want to compile due to missing dependencies.

There isn't much we can do on pygames end, apart from maybe writing some more buildconfig hacks to declare  `pygame.midi` an "optional" module so it does not error on compile time if dependencies are missing, and instead skips the submodule

**Comment by ankith26** [comment]
Closing issue because the task of having pypm conditionally compile based on portmidi availability is already a part of #473
