### ISSUE TITLE
What is the definition for the multiple channels? Any device to recommend?

### ISSUE THREAD

**Issue by funcode2** [pygame/pygame#2918]
Normally, I use the stereo audio device sound card or audio adaptors for testing. It has 2 audio channels. As pygame supports multiple channels, (by default, 8), I wonder what kind of sound card have you tested? Did you try "Terratec DMX 6FIRE USB Sound card"? I hope to find a device that can support using channel 0, 1, 2, 3. Currently, on the stereo device, Channel 0, 2, 4, ... go to the left speaker; Channel 1, 3, 5, ... go to the right speaker. Is it the expected behavior?

**Comment by ankith26** [comment]
Hello! This is a place to be posting issues of pygame itself, and not the best place to ask such questions because we contributors generally don't have enough experience on the loads of different hardwares out there, so we cannot provide a good answer. Your best bet would be asking this on other internet forums, perhaps reddit, SO or if your hardware has a dedicated forums page that would be the best place to ask this kind of question :)

**Comment by MyreMylar** [comment]
@funcode2 looking at the hardware specs it looks like a 6 channel audio card.

Did you initialise pygame mixer with 6 channels? The default is 2 not 8:

https://www.pygame.org/docs/ref/mixer.html#pygame.mixer.init

```python
pygame.mixer.init(channels=6)
```

If that doesn't work I have no idea, almost all of the audio stuff is passed straight over to SDL Mixer.

**Comment by funcode2** [comment]
@ankith26 The purpose of this question is to verify the function by using any suitable hardware. I actually ordered a hardware. I can update the test result after I finish the test.
@MyreMylar Thanks for your response. I will give an update later.

**Comment by funcode2** [comment]
I received my USB audio device (devicename="Speakers (USB Sound Device)"). Which supports 6 channels. I can test the individual channel successfully by using the provided windows app. I don't have luck to make it work with pygame. I have a question regarding of the mechanism to set the multiple channels (4) up.
This is what I did to make the 2 channels working:

pygame.mixer.pre_init(channels=2, devicename="Speakers (USB Sound Device)")
pygame.mixer.init()
m = pygame.mixer.Sound('.\\1.wav')
n = pygame.mixer.Sound('.\\2.wav')
pygame.mixer.Channel(0).play(m)
pygame.mixer.Channel(0).set_volume(0.0, 1.0)
pygame.mixer.Channel(1).play(n)
pygame.mixer.Channel(1).set_volume(1.0, 0.0)

To try out the 4 channels, I can do something like below. But I get stucked on how to specify the set_volume for Channel(2) and Channel(3)? In my test, there is no separation on the channels. All mixed together.
pygame.mixer.pre_init(channels=4, devicename="Speakers (USB Sound Device)")
pygame.mixer.init()
m = pygame.mixer.Sound('.\\1.wav')
n = pygame.mixer.Sound('.\\2.wav')
p = pygame.mixer.Sound('.\\3.wav')
q = pygame.mixer.Sound('.\\4.wav')
pygame.mixer.Channel(0).play(m)
pygame.mixer.Channel(0).set_volume(0.0, 1.0)
pygame.mixer.Channel(1).play(n)
pygame.mixer.Channel(1).set_volume(1.0, 0.0)
pygame.mixer.Channel(2).play(p)
pygame.mixer.Channel(2).set_volume(0.0, 1.0) #?
pygame.mixer.Channel(3).play(q)
pygame.mixer.Channel(3).set_volume(1.0, 0.0) #?

Thanks if you can share some idea.

**Comment by MyreMylar** [comment]
Looked into this a bit today. The short answer is that there has always been a distinction in SDL between 'mixing channels' and 'hardware channels'. Basically there are always 8 mixing channels and, in the original version of SDL mixer - either 1 (mono) or 2 (stereo) audio channels.

Then in 2004 someone added a patch that added the 4 & 6 hardware channels options to SDL mixer - BUT as far as I can tell only for the alsa audio driver on linux?

This is the original patch for SDL that added the 4 & 6 channel options for init mixer:

https://github.com/libsdl-org/SDL_mixer/commit/2bcd3188c27cafe3a7f12a7548d58e4c233d2fc0

```
Since the  only  SDL output  driver  that  knows  about  surround sound is the Alsa driver,
you'll want to choose it, using:

     export SDL_AUDIODRIVER=alsa
```
So that might be a hard stop for your use case.

Anyway assuming you have linux and have set the alsa driver - you can see from further down the patch comment it says:

```
The two "left" and "right" arguments to Mix_SetPanning,   for  the
case of 4 or 6 channels,  no longer simply control the volumes of
the left and right channels. Now the "left" argument is converted
to an angle and Mix_SetPosition is called,  and the "right" argu-
ment is ignored.
```

Also see this diagram from the comments:
```
/*
         *  An angle that's due north does not attenuate the center channel.
         *  An angle in the first quadrant, 0-90, does not attenuate the RF.
         *
         *   ...so, we split our angle circle into 8 ...
	 *
	 *             CE
	 *             0
	 *     LF      |         RF
	 *             |
	 *  270<-------|----------->90
	 *             |
	 *     LR      |         RR
	 *            180
	 *   
         */
```

And this chunk of the SDL mixer code:

```
if (channels > 2) {
    	/* left = 255 =>  angle = -90;  left = 0 => angle = +89 */ - This seems backwards to me
    	int angle = (int)left;
    	angle = 127 - angle;
	angle = -angle;
    	angle = angle * 90 / 128; /* Make it larger for more effect? */
	return( Mix_SetPosition(channel, angle, 0) );
    }
```

So to pass that through to SDL_mixer from pygame you'd have to call to do something like:

```
channel_1.set_volume(1.0, 0.0) # right hand side
channel_1.set_volume(0.0, 0.0) # left hand side
channel_1.set_volume(0.5, 0.0) # front centre
```

I don't think it's possible to get all the way back to 180 with the panning functions used by `.set_volume()`, likely intentionally as they are supposed to mimic stereo panning on a greater than 2 channel setup.

Anyway, I tested using the mixer in this way on my windows 5.1 speaker and sound card setup and it didn't seem to give me any surround sound. I'm not sure it is usable to do surround sound with SDL_mixer on windows, but perhaps somebody else knows better like @Wohlstand.

**Comment by Wohlstand** [comment]
If you do use an older version of Mixer, it has the bug at stereo mode that makes the position is always at the same side and doesn't go between left and right. I fixed some, and that should work. The position change here works for only changing the volume of channels, but it doesn't filter them to simulate distortions that happen at human ears. If you use multichannel hardware, SetPosition should change the volumes of all channels to set the proper location of the sound source. Unfortunately, I hadn't proper multichannel hardware to verify the thing in work.

**Comment by funcode2** [comment]
@MyreMylar @Wohlstand Thank you guys so much for working on this.
If you like to give it a try on the hardware, I can share what I am using. It is around $25. I am not representing any of the hardware vendors. I just work on my own project. (VAlinks USB 2.0 External Sound Card 6 Channel 5.1 Surround Optical S/PDIF Audio Sound Card Adapter for PC Laptop Recording Compatible with Windows 10/8 / 7/ XP)
