### ISSUE TITLE
Assertion at pulsecore/queue.c:81 causes abort.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#293]
Originally reported by: **Earlo Pollari (Bitbucket: [Earlo](https://bitbucket.org/Earlo), GitHub: [Earlo](https://github.com/Earlo))**

----------------------------------------

Not entirely sure if this is Pygame related problem, or do I have something wrong with my c libraries. But I keep getting the following error at consistently inconsistent intervals while running my pygame (for python3) programs.

Been trying to figure it out the cause for this in several occasions for the past year with no real results.

*Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push(). Aborting.*

I am not using any audio in my project.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/293

**Comment by MyreMylar** [comment]
This is the second old SDL1 bug mentioning the pulsecore library. suspect it had a few issues back in the day.

I've never seen anything like this on windows using python 3 and various versions of pygame, there is no more detail to go on in the report. I suspect it should be closed for now since it is four years old with no follow up. Can always reopen if more reports crop up.

**Comment by LordBaryhobal** [comment]
I have the exact same problem though I am using audio in my project (python 2.7, pygame 1.9.1). It also happens at random intervals

**Comment by MyreMylar** [comment]
Python 2 is now end of life and pygame 1.9.1 is several years old. 

The only path to fixing these problems is to first upgrade your versions to something more recent and see if you still get them. I would first try python 3.7 and pygame 1.9.6 as those are stable and much more recent.

**Comment by Supadog** [comment]
I have the same problem. Using pygame 1.9.6 (with audio playing) and python 3.7 on a Raspberry Pi 4 (OS: Linux raspberrypi 5.4.79-v7l+). It's annoying as hell because it just happens in random places/times and crashes the game.

**Comment by ankith26** [comment]
Maybe you could try updating to pygame 2.0.1 and see if the bug persists. Since pygame 2 uses SDL2, maybe this bug has already been fixed

**Comment by Supadog** [comment]
pygame 2 doesn't come with RPi OS (apt-get) by default just yet. I'd have to recompile from sources, etc. There sholdn't be any problems with dependencies, etc. if I choose to this, should there?

**Comment by ankith26** [comment]
This command should do the trick on RPi OS (buster)
```
sudo apt install libasyncns0 libflac8 libfluidsynth1 libice6 libjack0 libjbig0 libmodplug1 libmpg123-0 libogg0 libopus0 libopusfile0 libportmidi0 libpulse0 libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libsm6 libsndfile1 libsndio7.0 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3 libwayland-client0 libwayland-cursor0 libwayland-egl1 libwebp6 libx11-xcb1 libxcursor1 libxfixes3 libxi6 libxinerama1 libxkbcommon0 libxrandr2 libxrender1 libxss1 libxtst6 libxxf86vm1
sudo pip3 install pygame==2.0.1
```
You could omit the sudo on the pip install command if you want a user installation. The apt command just installes some dependencies (it is very likely you will already have most of them, but that command is going to also install SDL stuff.

**Comment by Supadog** [comment]
Thanks. Just ran those commands. All good but python3 is still using pygame 1.9.6. Would you know how I can get it to use pygame 2?

**Comment by ankith26** [comment]
Hmm. Maybe you have a user installation of pygame 1.9.6 that overshadows python 2.0.0
Maybe try,
pip3 uninstall pygame==1.9.6
sudo pip3 uninstall pygame==1.9.6

**Comment by Supadog** [comment]
Ah yes, i had a user installation of pygame! Great. It's up and running.

I stumbled upon a pygame.init() error after installation:
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40

The fix for this (in case anyone else was to stumble upon this thread) is described here: 
https://www.raspberrypi.org/forums/viewtopic.php?t=136974
(the first part of the solution solves the issue, i.e. just editing /usr/share/alsa/alsa.conf will suffice. 

Hopefully this will all solve the random crashes. It should theoretically... Thanks!
