### ISSUE TITLE
What happen if you do .convert() to a Font object?

### ISSUE THREAD

**Issue by ShinkaiHuang** [pygame/pygame#2994]
Hi, I notice that if I do .convert() to a Font object before blit it to the screen, the corresponding text will become just squares on the screen. Why is that or, what happened? (See the first line bellow for a converted example)
![image](https://user-images.githubusercontent.com/94778851/150147797-be9cb43d-71f0-4a1e-ab7f-eb302bce3024.png)

**Comment by ankith26** [comment]
Hi! Github issues is a place to post issues related to pygame itself, and not issues in your code. You can ask for code help on various other forums on the internet, like reddit, Stack Overflow, discord and other such places :) 
But I will try to solve your issue here this time

According to the [Font](https://www.pygame.org/docs/ref/font.html#pygame.font.Font) docs, there is no such thing as `.convert()` method for fonts, so you are probably confusing a `Font` object for a `Surface` object, which has a `convert` method. `Font.render` renders text into a `Surface` object which you can then `blit` directly on your main window. Calling `convert` on a `Surface` strips the Surface of its transparency, which is why you see white boxes. The fix for this issue is to not call `convert` at all, or use `convert_alpha` in its place, which will retain transparency
