### ISSUE TITLE
Performance of draw.polygon vs gfxdraw.filled_polygon

### ISSUE THREAD

**Issue by arganoid** [pygame/pygame#3019]
On my machine I find that drawing a 960x480 polygon with draw.polygon takes about 6ms, while drawing it with gfxdraw.filled_polygon takes a tenth of the time. Does anyone know why there is such a difference - and is there some reason why draw.polygon could not be brought up to the same speed?

Looking at the code I see that draw.polygon draws line by line, while gfxdraw.filled_polygon calls filledPolygonRGBA from the SDL_GFX library.

**Comment by Starbuck5** [comment]
Hey @arganoid this was probably just fixed in #3141 

If you're still interested in testing, you can download a wheel from our continuous integration to test this locally.

It's a bit hard to describe how that would work.

If you're on windows: Go here, https://ci.appveyor.com/project/pygame/pygame/builds/43246331, pick out whichever python / (32/64 bit) you use, click on the run, go to the "artifact" tag, download and pip install [wheel filename].

If you're on Mac: Go here, https://github.com/pygame/pygame/actions/runs/2171769274, download the pygame wheels file at the bottom, pick out whichever wheel is right for you, pip install [wheel filename].

If you're on Linux: Go here, https://github.com/pygame/pygame/actions/runs/2171769272, download the pygame wheels monstrosity of a file, pick out whichever wheel is right for you, pip install [wheel filename].

I can't test your use because you didn't provide any testing code. But I'm pretty close to just assuming that this issue is fixed, maybe I'll leave this open a week or two just in case and close then.
