### ISSUE TITLE
Why can't I sign in with my Gmail email?

### ISSUE THREAD

**Issue by RixInGithub** [pygame/pygame#3030]
Well, I can't signup or login with my email:

> adas.jankus@gmail.com

Well, since you are not thiefs or something, I revealed my email

But, I want to know here, why can't I sign up with it. I will wait for a confirmation email from whatever.

[**HAVE TO REMOVE THIS**]

**Comment by gresm** [comment]
Where you can't signup / login with your email?

**Comment by MightyJosip** [comment]
Hello!

Thank you for your bug report in the Issues section of Pygame GitHub organization. After a long investigation where top experts for Pygame have gathered and discussed this problem we can confirm this has been fixed in the most recent Pygame version 🎉 

You need to install Pygame with`python3 -m pip install pygame==2.1.2`

**Comment by Starbuck5** [comment]
Be nice MightyJosip.

@RixInGithub Presumably you're referring to pygame.org. Registration has been disabled for a while because of spam getting posted, we're aware of the problem. Hopefully it can be enabled again in the future.

**Comment by RixInGithub** [comment]
> Be nice MightyJosip.
> 
> @RixInGithub Presumably you're referring to pygame.org. Registration has been disabled for a while because of spam getting posted, we're aware of the problem. Hopefully it can be enabled again in the future.

Oh dang 👎🏻
