### ISSUE TITLE
translating docs

### ISSUE THREAD

**Issue by ghost** [pygame/pygame#3046]
Hi

I want to translate the pygame docs to Dutch language.
Is there anybody who can tell me how to do this?

I don't know anything about github, ...
If I put everything in a LibreOffice text document and put it here so somebody can copy paste it to put online, is that ok?

**Comment by pygamedev** [comment]
I was also wondering if there could be made a way to download the whole docs in PDF format(for English).
I use offline laptop and then can't read the docs


Thx

**Comment by Starbuck5** [comment]
> I was also wondering if there could be made a way to download the whole docs in PDF format(for English).
I use offline laptop and then can't read the docs

`python -m pygame.docs` launches a local copy of the docs, recently added in 2.1.2.

**Comment by pygamedev** [comment]
Thx this works

But you don't say how translating should be made?
Is there already a version with another language?

**Comment by Grimmys** [comment]
I think we already had discussions about translating docs recently and the outcome was that - at least for now - translations should not be part of the core documentation, i.e. you can build on your own (and host it) the dutch version but that's it. 

Main reasons were:
- why decide to add like you said for example Dutch translation and not french, Spanish, Chinese, or Japanese ones? 
Hard to choose a small bunch of languages and justify this specific choice. 
- translations would be a pain to keep up to date. Let's say we added three different translations. Each time we would make a subtle change in the documentation, we will have to find three volunteers each speaking a different language to update the translations too. Big constraint, you see?

(PS: others, don't hesitate to correct me if I said something wrong)

**Comment by dr0id** [comment]
Since the pygame documentation is build with sphinx I would guess it probably would work as for sphinx:

https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

But AFAIK the documentation isn't in any other language other then English. 
So my advise: learn English. It will help you in many other ways (especially when coding). 

But I  still totally understand that there might be many reasons to have it in another language too. But as pointed out already by others in an opensource project with volunteers only I think the benefit vs the effort needed to get it right is too small. I might be wrong though.

**Comment by Starbuck5** [comment]
My key concern is keeping them up to date. Maybe we'll revisit this later, but I'll close it for now.
