### ISSUE TITLE
Debian pygame package should remove unused font dependencies

### ISSUE THREAD

**Issue by illume** [pygame/pygame#305]
Originally reported by: **PanderMusubi (Bitbucket: [PanderMusubi](https://bitbucket.org/PanderMusubi), GitHub: [PanderMusubi](https://github.com/PanderMusubi))**

----------------------------------------

Minimalise font dependencies in terms of:

* no font .deb package dependencies in the pygame .deb
* no usage of absolute font file paths
* use font config where possible
* when absolutely necessary shipping font files only in the source code for testing purposes, not in the final build
* when absolutely necessary refering to TTF files, also look for OTF files when those files are not present as graceful degradation
* et cetera

See also:

* https://bitbucket.org/pygame/pygame/issues/306/separate-build-and-install-package
* https://bitbucket.org/pygame/pygame/issues/107/pygame-192-release

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/305

**Comment by MyreMylar** [comment]
I feel like the conclusion of this report is that nothing needs to change in the pygame project. There is one font in the codebase:  `freesansbold.ttf` which is the default pygame font.

How does one follow up with .deb maintainers? What would we tell them if we had a list of their email addresses?

**Comment by MyreMylar** [comment]
**To do to close:**

- [ ] Verify that debian is no longer bundling unnecessary fonts with pygame package. Not sure exactly where to follow this up.

**Comment by nthykier** [comment]
@MyreMylar: AFAICT, the Debian maintainers are "unvendoring" the font file provided by pygame upstream.  This is based on the following logic:

 * The Debian pygame package depend exactly on one font-package, `fonts-freefont-ttf`.
 * The build scripts for the Debian pygame package has scripts to replace the embedded `freesansbold.ttf` file with a file with a similar name (see https://salsa.debian.org/python-team/modules/pygame/-/blob/master/debian/rules#L5).
 * This pattern follows a tradition of Debian tracking and trying to remove duplicated font files: https://lintian.debian.org/tags/duplicate-font-file.html

In other words, I think this is "business as usual" and not a real problem.

(I think the original issue was about us using fontconfig to find a similar font instead of embedding one, which is a different problem than the Debian package providing our embedded font from a separate package)

**Comment by illume** [comment]
Yeah, I'll close this.
