### ISSUE TITLE
Make Surface serializable.

### ISSUE THREAD

**Issue by NicolasMICAUX** [pygame/pygame#3054]
**Description**
Pygame Surface are not seralizable (with pickle for example) as of now.
This is an issue in the context of multiprocessing (with Ray for example), as it uses serialization to transfer objects in the shared memory.
It seems this little change to the class Surface might solve the issue : [https://stackoverflow.com/a/59614766](https://stackoverflow.com/a/59614766).

**Comment by blankRiot96** [comment]
I have faced this issue too, but to be honest, you shouldn't be in a position where you are serializing `pygame.Surface` data. If you are trying to store classes that have surface attributes, my solution was to make a list and append only the constructor arguments, then actually make the objects in the game itself. 

I primarily faced this issue while attempting to make a level editor, but then I switched to the Tiled Map Editor, and loaded the .tmx file with pytmx which contained image data in the layers 

Also I believe if this *were* to be added, you wouldn't be able to save converted surfaces anyways, I'm not sure

I have faced this issue too, and I think it's better to have it than to not, it could be useful depending on the situation

**Comment by dr0id** [comment]
Since pygame provides the tools needed to serialize a surface, I would vote to close this issue. The example on stackoverflow is simple enough to be copied.

**Comment by NicolasMICAUX** [comment]
Ok, thank you for your answers. I tried the methods given on stackoverflow, and it kind of works, it is only a bit more complex than initially expected. I hope it won't break with updates in Ray.
Thx for taking time to answer me.

**Comment by flodri** [comment]
I' trying to improve pygame.Surface compatibility with other libs/functions.
Deepcopy was just a exemple of what would work directly if surface where serializable, the og issue with ray is another, to take your exemple, making Surface serializable would make Sprite suport deepcopy automaticaly.
Of course we could implement the dunder method __deepcopy__ too but that was not my point.
What I'm saying is  making Surface serializable would make a lot of stuff just work, and it's easy.
> Pickling surfaces is a pretty unwise idea in general.
True, but it's not like you can forbid the user from doing so if they want to, even as it curently is. Keeping surface un-serializable just because you can abuse pickle a bit more easily otherwise, seems a bit over the top to me. I think a note in the doc about that is enough.
