### ISSUE TITLE
Separate build and install package requirements for basic, X and OpenGL

### ISSUE THREAD

**Issue by illume** [pygame/pygame#306]
Originally reported by: **PanderMusubi (Bitbucket: [PanderMusubi](https://bitbucket.org/PanderMusubi), GitHub: [PanderMusubi](https://github.com/PanderMusubi))**

----------------------------------------

The packages that need to be installed for building and for installing pygame need to be organised into three groups:

* bare minimal for building
* minimal for building with support for X
* minimal for building with support for OpenGL (support for X implied)
* bare minimal for installing
* minimal for installing with support for X (recommend packages)
* minimal for installing with support for OpenGL (suggested packages)

This is important as pygame can easily be installed on more minimal systems suchas headless systems, Raspberry Pis without X, Raspberry Pis without OpenGL, etc.

See also:

* https://bitbucket.org/pygame/pygame/issues/107/pygame-192-release
* https://bitbucket.org/pygame/pygame/issues/305/minimalise-font-dependencies
* http://www.pygame.org/wiki/CompileUbuntu

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/306

**Comment by ankith26** [comment]
Been quite a while since this issue was opened, and there has been no much activity

Currently x11 and opengl are not bundled on any of our wheels, they just happen to be dynamically loaded by SDL at runtime only if available.

The compile instructions are also more minimal now, it's just installing SDL stuff with apt (which in turn installs everything needed) and distros like PiOS can make the required changes on the apt side of things to manage this without pygame having to do anything (from what I know, pi has better x11 and opengl support these days than in 2016)
