### ISSUE TITLE
full screen

### ISSUE THREAD

**Issue by lonely-unicorn** [pygame/pygame#3078]
What is the default way to make the pygame window full screen?

**Comment by Mega-JC** [comment]
@lonely-unicorn  Hello, the 'Issues' section in this repository is for reporting bug and issues about the library, not for smaller questions like  these. If you have questions, check the pygame documentation or ask in a pygame community on Discord or Reddit.

Using the `FULLSCREEN` flag for `pygame.display.set_mode()` is a common method for achieving fullscreen, other methods are up to you to discover in the documentation.

**Comment by MightyJosip** [comment]
Hello!

Thank you for your bug report in the Issues section of Pygame GitHub organization. After a long investigation where top experts for Pygame have gathered and discussed this problem we can confirm this has been fixed in the most recent Pygame version 🎉

You need to install Pygame with `python3 -m pip install pygame==2.1.2`
