### ISSUE TITLE
SDL2: Function to get a key from name is needed.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#309]
Originally reported by: **Miloslav Číž (Bitbucket: [tastyfish](https://bitbucket.org/tastyfish), GitHub: [tastyfish](https://github.com/tastyfish))**

----------------------------------------

In key module, there is a function pygame.key.name() that gets the name from a key code, but there is no function that does the opposite, i.e. get the key code from name. It would be easy to implement, just call SDL_GetKeyFromName.

It is needed because when for example someone uses the name() function to store key mappings in readable format, it is hard to load the key mapping back.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/309

**Comment by mweb** [comment]
The SDL_GetKeyFromName is a SDL 2.0 function. This is not available within SDL 1.2.

**Comment by takluyver** [comment]
I've re-targeted this for 2.0, since it sounds like it can't be fixed without upgrading to SDL 2.

There has been [some work](https://github.com/llindstrom/pygame_SDL2) on moving pygame to SDL2, but it hasn't been touched in some months. There are also forks like pygame_sdl2, but they're not super active either.
