### ISSUE TITLE
C code handling of input booleans

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3096]
I've just been looking the source code at how we handle receiving booleans from python
- Some code parses them as ints, using i in the PyArg_Parse
- Some code parses them as "boolean predicates", using p
- Some code parses them as Python objects and then uses PyObject_IsTrue

The problem with PyObject_IsTrue is that it's a truthiness check, not a True check. These pygame functions accept non empty strings as True, or arbitrary objects without a `__bool__` method.
The problem with parsing as ints is that the error message would be weird if someone put in the wrong object, theoretically.
I think they should all be using p, but I haven't tested the above claims much yet

**Comment by ankith26** [comment]
From the [docs](https://docs.python.org/3/c-api/arg.html)
> p ([bool](https://docs.python.org/3/library/functions.html#bool)) [int]
Tests the value passed in for truth (a boolean predicate) and converts the result to its equivalent C true/false integer value. Sets the int to 1 if the expression was true and 0 if it was false. This accepts any valid Python value. See [Truth Value Testing](https://docs.python.org/3/library/stdtypes.html#truth) for more information about how Python tests values for truth.
New in version 3.3.

So even `p` is a truthiness check, so code using `p` is pretty much the same as using `PyObject_IsTrue`, except the latter can be a bit more verbose

**Comment by Starbuck5** [comment]
> So even p is a truthiness check, so code using p is pretty much the same as using PyObject_IsTrue, except the latter can be a bit more verbose

I see. It's strange to me that there isn't just a "bool" setting. We could check against `Py_True` and `Py_False` themselves, but then `0` and `1` wouldn't work.

I wrote a new strategy for handling those pesky PyObjects:
```c
    PyObject* bool_obj;

    if (!PyArg_ParseTuple(args, "O", &bool_obj))
        return NULL;

    if (!PyLong_Check(bool_obj)) {
        //TODO: error handling
        PyObject* class = PyObject_GetAttrString(bool_obj, "__class__");
        PyObject* classname = PyObject_GetAttrString(class, "__name__");
        
        PyErr_Format(PyExc_TypeError, "A bool is required (got type %S)", classname);
        return NULL;
    }

    int val = PyLong_AsLong(bool_obj);
```

This does what I expect in parsing a boolean value.

Do you think it would be worth doing something like this? We could put that up as a macro in pygame.h or somewhere and get all the functions using this.

**Comment by robertpfeiffer** [comment]
> * Some code parses them as "boolean predicates", using p

I think some PyGame code was written before "p" was a thing.

> I see. It's strange to me that there isn't just a "bool" setting. We could check against Py_True and Py_False themselves, but then 0 and 1 wouldn't work.

That would be weird, given that `1==True` in Python

> Do you think it would be worth doing something like this?
Something like this, sure, but it *will* break some code somewhere.

**Comment by Starbuck5** [comment]
The freetype code actually uses real booleans only.

```py
>>> f = pygame.freetype.Font(None)
>>> f
Font('C:\Users\charl\AppData\Local\Programs\Python\Python39\lib\site-packages\pygame\freesansbold.ttf')
>>> f.wide = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: The style value must be a boolean
>>> f.wide = True
```

Pygame 3.0 make it this way for everything?

**Comment by ankith26** [comment]
I'm in favour of retaining `p` behaviour and using it consistently everywhere.

My comment on the linked PR which I'm reposting a part of here because I should have made this under this issue
> In python code, the most common way to handle bools is usually `if my_bool_flag: ...` and `if not my_bool_flag: ...`, and you would almost never see a `if my_bool_flag is True: ...`, `if my_bool_flag == False` or something of that sort (infact these are considered bad practices). So common python code is actually doing the equivalent of `p` in a sense, truthiness checks are more pythonic than hard true/false checks.

Now typehinting bools have always been an issue: most functions type arguments as `bool` even though they can technically accept any python object. In a sense this is wrong as already pointed above because now typechecking can error at what would pass at runtime. But this is a fairly widespread practice nonetheless and it would not cause much problems even if we decide to go with this. 

Another alternative is to declare a typealias for `Any` in pygame code, by the name `Bool`/`Boolean`/`SupportsBool`. This way typehinting is accurate, and the function signature is more descriptive now, adding `Any`s directly would definitely confuse people. However I don't think this is a widespread practice in the python ecosystem.

Changing behaviour will definitely break compatibility as already pointed above, and in this case I don't think it's worth doing
