### ISSUE TITLE
Port SDL_GetPowerInfo

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3101]
SDL_GetPowerInfo docs: https://wiki.libsdl.org/SDL_GetPowerInfo

I've been thinking about how to do this for a while, and this is what I've come up with:

All of the power info can be represented in a dict, returned by a `get_power_state` function perhaps.
```py
SDL_POWERSTATE_UNKNOWN	  {"battery": None, "plugged_in": None, "charging": None, "battery_seconds": None, "battery_percent": None}
SDL_POWERSTATE_ON_BATTERY {"battery": True, "plugged_in": False, "charging": False, "battery_seconds": seconds, "battery_percent": percent} 
SDL_POWERSTATE_NO_BATTERY {"battery": False, "plugged_in": True, "charging": False, "battery_seconds": None, "battery_percent": None}
SDL_POWERSTATE_CHARGING	  {"battery": True, "plugged_in": True, "charging": True, "battery_seconds": seconds, "battery_percent": percent} 
SDL_POWERSTATE_CHARGED	  {"battery": True, "plugged_in": True, "charging": False, "battery_seconds": seconds, "battery_percent": percent}
```

I didn't want to do an approach with constants because constants are not a very common python pattern. I also like how this approach allows you to focus in on the actual bit of information you might want. For example, does this computer have a battery? Or, is this computer plugged in?

Each bit of information is `True/False/None`, where `None` represents unknown. The numeric values (battery seconds left and battery percentage) are `Int/None`, where `None` against represents unknown, but also invalid (in the case of not having a battery).

I don't think anyone is clamoring for this functionality, but someone will find a use for it if we add it 😄

**Comment by robertpfeiffer** [comment]
Kind of weird that this API does not have "on AC power" as a state. Would a PC on AC power be "charging" or "unknown"?

**Comment by ankith26** [comment]
> Kind of weird that this API does not have "on AC power" as a state. Would a PC on AC power be "charging" or "unknown"?

That would be `battery = False` and `plugged_in = True` by the proposed API.

I like the proposed API, but I believe it would also be nice to directly export the SDL `power_state` on the pygame end, hopefully as an `Enum` so that users can choose the representation they want to deal with.

One option would be to add the `power_state` field directly to the export dict you are suggesting, another would be to make this a lil `PowerState` class. OOP does look a bit overkill here, but I think the dict is complex and heterogenous enough to need a dedicated class. This way, we also have better room to expand in the future if we ever need to add methods (unlikely) related to power things. The API of the class could look something like:

```py
# the POWERSTATE_* constants are exported from their respective SDL
# counterparts in pygame constants.c, but are also defined in an enum 
# from python code
# these POWERSTATE_* constants could be private too, or they could be
# exported because this way is consistent with how the other pygame
# constants are exported, so users can pick their preference.
class PowerState(Enum):
    UNKNOWN = POWERSTATE_UNKNOWN
    ON_BATTERY = POWERSTATE_ON_BATTERY
    NO_BATTERY = POWERSTATE_UNKNOWN
    CHARGING = POWERSTATE_CHARGING 
    CHARGED = POWERSTATE_CHARGED

class PowerInfo:
    seconds: float
    percent: float
    power_state: PowerState

    # just a regular constructor, no SDL API used
    def __init__(
        self, seconds: float, percent: float, power_state: PowerState
    ): ...

    # this constructs a PowerInfo instance from the SDL function
    # To discuss: maybe a better name for this?
    @classmethod
    def from_battery(cls: type[PowerInfo]) -> PowerInfo: ...

    # these are properties: these are read-only and these fields are
    # determined from power_state on demand
    @property
    def is_on_battery(self) -> bool: ...
    @property
    def is_charging(self) -> bool: ...
    @property
    def is_plugged_in(self) -> bool: ...
```

Also zoldalma has made some initial progress on this PR, just FYI so that anyone else does not start working on this :)
