### ISSUE TITLE
Not a Windows BMP file

### ISSUE THREAD

**Issue by SuperBoyne** [pygame/pygame#3147]
I have a Raspberry Pi 3B running Raspbian OS Lite with the XFCE desktop. Everything has been going fine, except for Pygame. When my programs attempt to load a PNG file, it will raise an error because it's not a Windows BMP file. I've uninstalled the default Pygame 1.6~ (which didn't raise that issue, but was outdated and had its own issues) and installed the latest (2.1.2) which does have that error. I do have Pillow installed, and my code runs on my Windows machine, and all of the other posts of this I've seen haven't helped. Does anybody know how to fix this?

**Comment by ankith26** [comment]
> I've uninstalled the default Pygame 1.6~

That's an *extremely* old version of pygame. Do you mean pygame 1.9.6 which is pre-installed with the latest PiOS? If pygame 1.6 is pre-installed on your OS, your OS distro must be like 15 years old at this point.

Anyways, this issue must be due to an installation problem on your end. Could you please report your distro name along with the python version it uses?

**Comment by SuperBoyne** [comment]
I fixed this by reinstalling Raspberry Pi OS Lite, installing python3-pip with apt, removing the folders for Pygame 1.9.1 (yes I got it wrong ankith26), and installing Pygame with pip.

**Comment by ankith26** [comment]
Nice to hear that it works now

**Comment by LevitatingBusinessMan** [comment]
I am having this issue on my raspberry pi with pygame 2.4.0, loading an svg.

Works fine outside of the pi

**Comment by arun184203** [comment]
well i am facing this issue in my garud linux , and tried installing latest version , but did't work
