### ISSUE TITLE
Rendering of the images is way off

### ISSUE THREAD

**Issue by tijko** [pygame/pygame#3153]
**Environment:**

- Windows 10 Enterprise (10.0.19042 Build 19042)
- Python 2.7.18
- SDL 2.0.10
- PyGame 1.9.6
- VideoCard: NVidia GeForce GTX 1650Ti
- Intel(R) UHD Graphics Family

**Current behavior:**

As soon as invoking the the program the blocks are rendered with what looks like binary bits written inside of them.

**Expected behavior:**

Clear blocks that I have uploaded and what had been rendered on previous systems.

**Screenshots**
![tetris-error](https://user-images.githubusercontent.com/1518884/165371213-8616b6e0-a708-41ca-8faf-a531b8b0d87f.png)

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Install all the base libraries and required versions
2. From a Bash terminal invoke `python tetris.py`
3. Observe the issues with the tiles...

Edit:
The link to my [Tetris](https://github.com/tijko/tetris) repository

**Comment by Starbuck5** [comment]
Ok, I assume you mean your tetris repository? It would be good to link that: https://github.com/tijko/Tetris

I have no idea what could cause something like this. Maybe it's the old version of pygame vs a newer version of Windows. But I've never seen a report of anything close to this on Windows before.

Pygame 2.0.3 is the last release that supports Python 2, please try that instead of 1.9.6.

> SDL 2.0.10
    PyGame 1.9.6

^ That's not a very likely configuration. Pygame 1.9.6 prebuilts come with SDL1, so you either built from source yourself or one of these is wrong.

**Comment by tijko** [comment]
@Starbuck5 This is great information to go on thanks I will follow up from here.

**Comment by robertpfeiffer** [comment]
This is amazing. This looks like you somehow run SDl1.2 with aalib backend or even libcaca on win10 Enterprise. And you say you are running pygame 1.9.6 based on SDL 2.0.10? Amazing.

**Comment by tijko** [comment]
@robertpfeiffer I was about to say amazing, right?  Its just amazing I couldn't think of any other words to describe it.

**Comment by tijko** [comment]
@Starbuck5 Had time to configure everything properly, as I'm doing this for fun on a new dev-box...its fixed and absolutely amazing!! Just so amazing

![tetris](https://user-images.githubusercontent.com/1518884/166183288-dd829ea8-46a4-4f50-929b-87a659bde4d7.png)
