### ISSUE TITLE
PyCharm: pygame.error: No available video device

### ISSUE THREAD

**Issue by Precola** [pygame/pygame#3169]
** Remote Server Environment: **
- **Operating system** :Ubuntu
- **Python version** :3.8.13
- **SDL version** (e.g. SDL 2.0.12):
- **PyGame version** :2.0.0.

**Current behavior:**
The codes are in the remote server. I run the code in pygame examples in different manners and met different results.
**1, If I run the code in pygame examples in the Windows MobaXterm, it works and show the game window.**
**2, If I open pycharm in the remote server and run the code in the remote pycharm, it occurs errors:**
```
X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  1 (X_ShmAttach)
  Serial number of failed request:  197
  Current serial number in output stream:  198
```
**3, If I run the code in the loacl pycharm, it occurs different errors:**
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/braincog/lib/python3.8/site-packages/pygame/examples/camera.py", line 105, in <module>
    main()
  File "/usr/local/anaconda3/envs/braincog/lib/python3.8/site-packages/pygame/examples/camera.py", line 100, in main
    VideoCapturePlayer().main()
  File "/usr/local/anaconda3/envs/braincog/lib/python3.8/site-packages/pygame/examples/camera.py", line 27, in __init__
    self.display = pg.display.set_mode(self.size, 0)
pygame.error: No available video device
```
**Expected behavior:**
I hope when I run the code in pycahrm, I can get the window of game.

**Comment by Starbuck5** [comment]
I don't think this is a pygame problem. It's a problem with remote server environment.

You run it through mobaXterm: it tries to send you the result but fails (probably because your Ubuntu uses Wayland instead of X11 or something)
You run it through pycharm: it tries to run it, but it can't open a window because it's on a server, totally expected. The server is headless perhaps, it doesn't have any display to open a window on.
