### ISSUE TITLE
pygame.font.match_font should match fonts from path

### ISSUE THREAD

**Issue by illume** [pygame/pygame#330]
Originally reported by: **Silas Gyger (Bitbucket: [Nearoo](https://bitbucket.org/Nearoo), GitHub: [Nearoo](https://github.com/Nearoo))**

----------------------------------------

I thought that it would be very useful if pygame.font.match_font would match fonts from a path as well. This code:

```
#!python

font = "Fonts/bar.ttf"
pygame.font.Font(pygame.font.match_font(font), 12)
```
should load the font "Fonts/bar.ttf".

The person that defines `font` wouldn't have to think about where the font is located exactly. I would suggest that `match_font` first checks if the font is available in the file system, and _then_ if it's available as a system font. Maybe even add an optional argument `installed_only` that makes `match_font` skip local font-files if set true.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/330

**Comment by MyreMylar** [comment]
I'm trying to puzzle out the use case for this. Mainly because, if I was using a custom font with my pygame application, I would always then distribute it with my pygame application. 

This would seem to be for people who distribute a script without an included font file, but then for some reason include a path to the non-existent font file in their code anyway?

Perhaps you can explain it the purpose of it @Nearoo ?

**Comment by Nearoo** [comment]
Sure. Note that this was some years ago, I'm not really invested anymore, so don't hesitate to drop it if you think it's irrelevant. 

Back then I was writing a small extension of pygame that allows for text input using the keyboard. I wanted clients to be able to choose themselves whether they want to use an an installed font or a font from a file implicitly by passing just a string. I solved with a simple if-else clause right [here](https://github.com/Nearoo/pygame-text-input/blob/master/pygame_textinput.py#L51).

Personally, I don't think it's worth the time anymore, it's 2 lines of code, and apparently used very little. Do as you wish.

**Comment by MyreMylar** [comment]
Hmm. I had look over the code and all the system fonts are stored in two dictionaries indexed by their 'font name' and another group of hard coded sets of aliases. There isn't a speedy way to look up a system font by it's file name and, I suspect, that filenames for fonts are not consistent anyway (because of .otf and .ttf file types at least).

So I think the only change we could make is to return `None` if a file path passed to match fonts was not valid or just return the file path back again if it was. But if that's all pygame is doing in the function I suppose it's not really matching fonts anymore.

I think something like your code:

    from pygame.font import match_font
    from pathlib import Path
    
    font_req = 'fonts/cour.ttf'
    # font_req = 'courier'  # uncomment each to try other types of input
    # font_req = 'nonsense11'
    font_path = font_req if Path(font_req).is_file() else match_font(font_req)
    
    print(font_path)

 is probably more clear than overloading match_font as to what is happening.

**Comment by Nearoo** [comment]
I agree 👍
