### ISSUE TITLE
Move global Vector API functions in a header with include fencing 

### ISSUE THREAD

**Issue by itzpr3d4t0r** [pygame/pygame#3340]
The vector class has the potential to be a faster alternative to the use of a length 2 tuple or list. It lets you have direct access to its coordinates and that simplifies many functions. When I tried to implement this functionality in the `collidepoint()` function in the `rect.c` file, I came across many issues with API. for example you can use `pgVector2_Check` and `pgVector3_Check` (because they're defined in `_pygame.h`), but cannot use the `pgVector` struct, nor `pgVector_Check` therefore blocking you from accessing the vector's field and using them.

I can quote some messages from Discord(pmp-p)

> it's a mess, they are declared multiple times https://github.com/pygame/pygame/blob/79c84b40fc3e6a3cae6aa604556e86ccb9f1dde7/src_c/math.c#L85
> ideally math.c should be included before rect.c in static.c
> and it should be called pg_math.c anyway, since math.c is already a thing in python

> so https://github.com/pygame/pygame/blob/79c84b40fc3e6a3cae6aa604556e86ccb9f1dde7/src_c/include/_pygame.h#L431 and https://github.com/pygame/pygame/blob/79c84b40fc3e6a3cae6aa604556e86ccb9f1dde7/src_c/math.c#L85  <= awful

The advice were:

> first math.c should not define stuff that are used globally, they should be in a header with include fencing
> as in "good" C

and 

> if you want to use pg_math internal defines it should be used with something like  #include "pg/math.h"  , thehy should not be thrown in a pygame.h bag 

So if i understand it correctly we need to somehow clean up our global definitions for Vector functions and structs, possibly moving them to a separate file and do some refactorings.
The objective should be to have an implementation and file/import organisation such that we can just import a file with vector stuff without breaking code and be able to use it where we want it.

**Comment by pmp-p** [comment]
"explicit is better than implicit" absolutely **everything** is mixed up from pygame.h and src_c/_pygame.h (!!) and src_c/include/_pygame.h (!!!) and defines change under the hood depending on some obscure undocumented flags ( like *_INTERNAL ). 

They certainly should never be duplicated because it's very hard to track when changing one definition.

my opinion is "if a header does not play well with a full static build when it's a bad one", it should be as easy to build one pygame module including everything as to build the actual singles ones.

btw static builds run faster because modern compilers can inline more stuff instead getting forced to  call function pointers, they are not just a **key** component to webassembly builds.

i'd suggest to begin splitting from public/private functions and organizing things marked INTERNAL maybe in a "private" folder as cpython does actually with cleaning up its C-api. It can only help to clarify things for https://github.com/pygame/pygame/issues/1357 and getting an abi3 module on the rails.

**Comment by itzpr3d4t0r** [comment]
Very interesting stuff. Looks like this is bigger than expected but i see there's hope for seeing this stuff changed. @ankith26 told me he'll probably take a look at this and start codin in a matter of weeks. Should we start with vector or by laying out this new organisation as a whole?

**Comment by pmp-p** [comment]
i think vector is a good start, it will allow to uncover that is wrong without disrupting everything

**Comment by itzpr3d4t0r** [comment]
Apparently including math in rect.c is duable, so i'm closing this for now. If in the future we'll make more cleanups, i hope this will come in handy.
