### ISSUE TITLE
Remove obsolete vidcapture camera backend

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3357]
Pygame's camera module, (src_py/camera.py) uses different strategies to try to get a working webcam backend.

At one point, videocapture / vidcapture was usable and used, another python library that could provide webcam functionality for Windows. However, that package is now obsolete (last updated in 2012), and we have a new camera backend for Windows now.

I'd like someone to remove this backend and relevant code.

- [ ] update documentation ( camera docs, documented env variable in "pygame" doc? )
- [ ] remove _camera_vidcapture.py source
- [ ] remove vidcapture support from camera.py
- [ ] figure out if there's something else I'm forgetting in this list that should be done

**Comment by MyreMylar** [comment]
What version of Windows does the new version of the camera backend support? IIRC it was 8 or was it 8.1?

Googling online suggests Windows 8.1 is EOL from Jan 2023.

**Comment by Starbuck5** [comment]
> What version of Windows does the new version of the camera backend support? IIRC it was 8 or was it 8.1?

It was unclear to me as I wrote it. It's been tested by Matiis, who runs some iteration of 8.

**Comment by MyreMylar** [comment]
Yeah I got it working a while back, I think I just downloaded binary versions from that random python windows binary website on a university server - that is now being shut down. 

Since then I've updated to a new PC and then Windows 11 and the new backend has been working fine on both Windows 10 and Windows 11 so I'm pretty sure it is safe to deprecate the old backend for new versions. 

I expect the intersection of people who run pre-windows 8, managed to download the binary vidcapture backend before the website was shut down (or built it themselves from source) and still want to keep up to date on the latest versions of pygame is a very small number.

**Comment by Starbuck5** [comment]
>  Hi. I would like to start contributing and this seems like a good first issue. Mind if I take it?

Sure, go ahead. I feel like a shill because I point this out a lot, but we have a `#contributing` channel on the pygame discord, if you want to ask questions in a more conversational format: https://discord.com/invite/ZuB2RySPRJ.

**Comment by SmashedFrenzy16** [comment]
> At one point, videocapture / vidcapture was usable and used, another python library that could provide webcam functionality for Windows. However, that package is now obsolete (last updated in 2012), and we have a new camera backend for Windows now.

Should't we keep it for legacy computers? Many people still use operating systems like windows 7.

**Comment by MyreMylar** [comment]
> > I'd like someone to remove this backend and relevant code.
> 
> Should't we keep it for legacy computers or at least make a new file for legacy camera modules? Many people still use operating systems like Windows 7.

The older versions of pygame are still available, if you simply must have a pygame camera module that runs on an 14 year old end of life operating system - then pygame has plenty of old versions available for you to use.
