### ISSUE TITLE
music module  failed log.

### ISSUE THREAD

**Issue by syz-lm** [pygame/pygame#3450]
![image](https://user-images.githubusercontent.com/111848062/190304144-cbd3c804-ec28-4390-9b84-429d8cb63c02.png)

**Comment by ankith26** [comment]
Hello!

I'm not familiar with this kind of errors, these don't seem python generated.

Can you also provide a minimal reproducer example, along with your platform details, software versions and mention the way you installed pygame?

**Comment by syz-lm** [comment]
https://github.com/syz-lm/playvim/blob/master/self_plugins/mp3player.py

Run. this code，you type into `next` in command line, the error may be occurs. 

![image](https://user-images.githubusercontent.com/111848062/190671850-7cc3007f-8527-477b-a97e-66c618b82cd4.png)

Thank you.

**Comment by ankith26** [comment]
Hmm... 
It could be an issue with your `mp3` music file being broken... Can you test those music files from an independent source? If they are not working with that too, then it's not a pygame bug

**Comment by MyreMylar** [comment]
> https://github.com/syz-lm/playvim/blob/master/self_plugins/mp3player.py
> 
> Run. this code，you type into `next` in command line, the error may be occurs.
> 
> ![image](https://user-images.githubusercontent.com/111848062/190671850-7cc3007f-8527-477b-a97e-66c618b82cd4.png)
> 
> Thank you.

I tried this code on windows and after removing:

https://github.com/syz-lm/playvim/blob/d8c08796c42ccbd96bda7c7f32f86d119018536e/self_plugins/mp3player.py#L348

and:

https://github.com/syz-lm/playvim/blob/d8c08796c42ccbd96bda7c7f32f86d119018536e/self_plugins/mp3player.py#L371

it worked with some downloaded test mp3s.

There is no `signal.alarm` function on windows anyway as it is platform specific. Also SIGALAM is somewhat broken with pygame in the current version. I submitted a patch to change this on 17th of April, but we haven't had a new full release since last Christmas. 

See:

https://github.com/pygame/pygame/pull/3142

If you are comfortable compiling pygame yourself you could also try that to see if it fixes your issue, but if you intend your mp3 player to work on windows I'd use something other than `SIGALARM` and `signal.alarm()`.

**Comment by syz-lm** [comment]
> Hmm... It could be an issue with your `mp3` music file being broken... Can you test those music files from an independent source? If they are not working with that too, then it's not a pygame bug

Really, there are two music files in question. thank you all.

**Comment by syz-lm** [comment]
> > https://github.com/syz-lm/playvim/blob/master/self_plugins/mp3player.py
> > Run. this code，you type into `next` in command line, the error may be occurs.
> > ![image](https://user-images.githubusercontent.com/111848062/190671850-7cc3007f-8527-477b-a97e-66c618b82cd4.png)
> > Thank you.
> 
> I tried this code on windows and after removing:
> 
> https://github.com/syz-lm/playvim/blob/d8c08796c42ccbd96bda7c7f32f86d119018536e/self_plugins/mp3player.py#L348
> 
> and:
> 
> https://github.com/syz-lm/playvim/blob/d8c08796c42ccbd96bda7c7f32f86d119018536e/self_plugins/mp3player.py#L371
> 
> it worked with some downloaded test mp3s.
> 
> There is no `signal.alarm` function on windows anyway as it is platform specific. Also SIGALAM is somewhat broken with pygame in the current version. I submitted a patch to change this on 17th of April, but we haven't had a new full release since last Christmas.
> 
> See:
> 
> #3142
> 
> If you are comfortable compiling pygame yourself you could also try that to see if it fixes your issue, but if you intend your mp3 player to work on windows I'd use something other than `SIGALARM` and `signal.alarm()`.

Thank you, there’s sth. wrong with some music files.
