### ISSUE TITLE
How can I configure the resignation of the screen pixels?

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [pygame/pygame#3476]
I know that by using pygame.display.set_mode() I can set the "pygame.RESIZABLE" flag but the problem is that the pixels of the screen do not fit the surface, that is, the window crops what is seen on the screen , how can I make the pixels of the screen reorganize or change according to the size of the window, and I mean that when the window is stretched those borders remain black, because I saw how to resize the pixels, but no I like that if the window is wider the pixels are wider.

I don't know if I made myself understood

**Comment by oddbookworm** [comment]
If I understand correctly, sounds like you'd like the `pygame.SCALED` flag

**Comment by ankith26** [comment]
Hmm, from what I understand, it seems like you want to pick a window size smaller than your current display so that your window fits the screen. One solution is to query the window dimensions with something like [`pygame.display.get_desktop_sizes`](https://www.pygame.org/docs/ref/display.html#pygame.display.get_desktop_sizes) and call `set_mode` with dimensions smaller than that.

PS: This issue tracker is for tracking bugs and such of pygame itself. If you need help with your pygame applications, feel free to ask on other internet forums like stackoverflow, reddit or discord.

**Comment by QuetzalcoutlDev** [comment]
Well I asked for help here because I searched in forums and they did not give me a solution that convinced me

**Comment by novialriptide** [comment]
> Well I asked for help here because I searched in forums and they did not give me a solution that convinced me

https://discord.gg/3wVrMhV4 and https://reddit.com/r/pygame are great places to ask for help
