### ISSUE TITLE
X Error of failed request:  BadValue

### ISSUE THREAD

**Issue by mahmoodn** [pygame/pygame#3481]
Hi, When I run a pygame-based python code, I get the following error:
```
pygame 2.1.2 (SDL 2.0.16, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  96
  Current serial number in output stream:  97
```
As I searched the web, it seems that the graphic driver is not compatible. However, I don't think the version is faulty.
Please see the information below:
```
NVIDIA RTX 2080Ti    Driver Version: 460.73.01    CUDA Version: 11.2
pygame 2.1.2
```
How can I debug more? I would like to see which driver version is needed for 2.1.2?

**Comment by ankith26** [comment]
Hello!
Does this issue reproduce for any pygame app you try, or are you doing something specific in the apps you tested? Can you also try updating pygame to the latest dev version, and see if the issue persists?

You can get more gl related info with `glxinfo`, can you post that output here along with any other platform info? Try running something like `glxgears` and see if that triggers the same issue (so that we can rule out any fault in pygame and/or SDL code)

**Comment by mahmoodn** [comment]
The `glxinfo` also returns the same error
```
$ glxinfo 
name of display: localhost:11.0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  41
  Current serial number in output stream:  42
```
It seems that there is a problem with the driver itself.

**Comment by fengsam6** [comment]
I meet this question in vnc serverer，I don‘t tknow pyagme or vnc question
