### ISSUE TITLE
tp_name of pygame types should be fully qualified (for better pydoc support)

### ISSUE THREAD

**Issue by miezebieze** [pygame/pygame#3483]
ohay
i'm used to use `pydoc` before searching the web and today i wanted to try my hand at sounds for the first time. after finding pygame.mixer i was confused what this `Sound` object was that the docstring was blabbing on about.

after consulting the online docs, i found out that for some reason [see title]. just to make sure, i tried `pydoc -k Sound` (does about the same as executing `help (Sound)` in the interpreter), which couldn't find it either.

`pydoc pygame.mixer.Sound` works but without knowing where to look it's no help.

**Comment by Starbuck5** [comment]
I don't understand how we would resolve this?

pydoc / help looks at the object's members to generate the docs?

```
>>> dir(pygame.mixer)
['Channel', 'ChannelType', 'Sound', 'SoundType', '_PYGAME_C_API', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_internal_mod_init', 'fadeout', 'find_channel', 'get_busy', 'get_init', 'get_num_channels', 'get_sdl_mixer_version', 'init', 'music', 'pause', 'pre_init', 'quit', 'set_num_channels', 'set_reserved', 'stop', 'unpause']
```

The Sound class is a member of the pygame.mixer module object, so I really have no idea why it wouldn't be picked up.

**Comment by miezebieze** [comment]
and there's more!
`ChannelType` and `SoundType` are two more that i could identify without even consulting pydoc.

in `pygame`, `Vector2` and `Vector3` don't show up, but `Color`, which is imported in the same way, does. at least the Vectors can be found in another module, although `pydoc -k Vector` doesn't find them either.

**Comment by Starbuck5** [comment]
> ChannelType and SoundType are two more that i could identify without even consulting pydoc.

What?
You could identify them without pydoc?
As in you couldn't find them with pydoc?

Again, I'm not sure how your points could actually be resolved. Would you like to submit a pull request?

**Comment by miezebieze** [comment]
> What? You could identify them without pydoc? As in you couldn't find them with pydoc?
i meant that because i just looked at it (as stated in my previous post) i knew it for a fact. of course i checked if it really was the case.

i know the basics of C but am unable to extract meaning from the source so i don't know how to resolve the problem either.
i was hoping someone else would know what's up and fix it.

**Comment by zoldalma999** [comment]
It may be because of `tp_name`. I can reproduce that `Color` and `Rect` (and some more) can be seen by doing `pydoc pygame`, but Vectors can't (and the opposite is true, so `pydoc pygame.color` does not show the Color class, but `pydoc pygame.math` lists all the vector classes). Which matches up with their name which is "pygame.Color" for color objects, but "pygame.math.VectorX" for vectors.

Additionally the [python docs](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_name) says:
> For types that are accessible as module globals, the string should be the full module name, followed by a dot, followed by the type name [...]. If the module is a submodule of a package, the full package name is part of the full module name. For example, a type named T defined in module M in subpackage Q in package P should have the tp_name initializer "P.Q.M.T".

As well as:
> For [statically allocated type objects](https://docs.python.org/3/c-api/typeobj.html#static-types), the tp_name field should contain a dot. Everything before the last dot is made accessible as the `__module__` attribute, and everything after the last dot is made accessible as the [`__name__`](https://docs.python.org/3/library/stdtypes.html#definition.__name__) attribute.

Looking over all the `tp_name`s, they are very inconsistent. Some are only the classnames, other are `pygame.Class`, there are a few that use macros, and then a few do `pygame.module.Class`.

Not sure how to name some objects that are really meant to be used as their shorthand such as Color, Rect, Surface (though I would go with their full name, so pygame.color.Color), but there is definitely some clean up to do here.

**Comment by ankith26** [comment]
Agree with zoldalma, looks like all type objects should have fully qualified `tp_name`s
