### ISSUE TITLE
Being able to handle events without initialising the video system

### ISSUE THREAD

**Issue by RMRubert** [pygame/pygame#3509]
I am trying to make program for a raspberry PI that will have no display or control. As such. I have installed a minimal distro that has not a graphical interface, just the console.

My problem is that I cannot use `pygame.event.get()` to know when a song has ended, because doing it triggers the following error:

```
File "/home/pi/gpio-music-box/test.py", line 20, in <module>
    for event in pygame.event.get():
pygame.error: video system not initialized
```
The code I am trying to run can be found [here](https://www.raspberry-pi-geek.com/Archive/2014/05/Pygame-modules-for-interactive-programs/(offset)/10) and I copy here for easy readibility.

```
import pygame

pygame.mixer.init()
# pygame.display.init()

# screen = pygame.display.set_mode ( ( 320 , 240 ) )

playlist = list()
playlist.append ( "/home/pi/Music/ES/A/ALASKA Y LOS PEGAMOIDES- Bailando.mp3" )
playlist.append ( "/home/pi/Music/ES/H/HOMBRES G- El ataque de las chicas cocodrilo.mp3" )
playlist.append ( "/home/pi/Music/ES/M/MANA- Rayando el sol.mp3" )

pygame.mixer.music.load ( playlist.pop() )      # Get the first track from the playlist
pygame.mixer.music.queue ( playlist.pop() )     # Queue the 2nd song
pygame.mixer.music.set_endevent ( pygame.USEREVENT )    # Setup the end track event
pygame.mixer.music.play()                       # Play the music

running = True
while running:
 for event in pygame.event.get():
  if event.type == pygame.USEREVENT:        # A track has ended
   if len ( playlist ) > 0:               # If there are more tracks in the queue...
      pygame.mixer.music.queue ( playlist.pop() ) # Queue the next one in the list
```

Mind that running `pygame.display.init()` will also trigger an error. Exactly this one: 

```
  File "/home/pi/gpio-music-box/test.py", line 4, in <module>
    pygame.display.init()
pygame.error: displayIndex must be in the range 0 - -1
```

**Comment by Starbuck5** [comment]
What about using [pygame.mixer.music.get_busy](https://www.pygame.org/docs/ref/music.html#pygame.mixer.music.get_busy)?

As soon as that returns False the music has stopped?

**Comment by RMRubert** [comment]
The problem I got with [pygame.mixer.music.get_busy](https://www.pygame.org/docs/ref/music.html#pygame.mixer.music.get_busy) is that I hit a wall with my knowledge. As it is not an event, it needs to run in some kind of loop, checking for it. But when the program is running that loop, it isn't listening to any of the buttons on the raspberry pi.

I am pretty sure it can be worked around, but with my knowledge I just don't know how to do it. At the end I moved to another library to play the files, which has solved this problem and brought new problems to the table (yay!). But I still thought that it will be neat if pygame could have events without a display. **Or at least make it clear in the documentation of set/get_endevent that they will fail without a display property.**

**Comment by ankith26** [comment]
The documentation for [`pygame.event`](https://www.pygame.org/docs/ref/event.html) does mention the restriction. I'm afraid we can't really fully lift this restriction (atleast not at the moment) because of how the SDL library (which is what pygame uses under the hood) closely ties display and event submodules together. But the underlying internal SDL restriction is that you can only "pump" events in a thread that initialised display, and event get usually implicitly pumps. So I suppose we could technically lift this restriction, but only in the case where `event.get` is called with `pump=False`

So we could implement your proposal, but since that will take a bit more time, I would suggest looking into a workaround (using `get_busy` on a loop)
Simply replace the event loop part of your code with something like (untested code)
```py
while running:
    # do any other handling here in this loop

    # this queues the next sound after one is done playing
    if not pygame.mixer.music.get_busy() and len(playlist) > 0:
        pygame.mixer.music.queue(playlist.pop()) # Queue the next one in the list
```
I'm assuming you are using another library to do any button handling

**Comment by Starbuck5** [comment]
It looks like Rethanon took care of you over in the subreddit- https://www.reddit.com/r/pygame/comments/ybq7el/trouble_with_end_music_event/
