### ISSUE TITLE
Error install Pygame with Python 3.11

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [pygame/pygame#3517]
**Description**

Hi, I'm part of the team maintaining [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) and with Python 3.11 released, I have started a PR to add support for it.
However, our CI is failing due to pygame not having a wheel for it, I believe. https://github.com/Farama-Foundation/Gymnasium/actions/runs/3313951017/jobs/5486408675

Looking through the issues, there are a couple of issues about this already but none of them seems to report the same error as our CI, https://github.com/pygame/pygame/issues/3459 

My questions are
1. Does pygame already support 3.11, if so, does anyone understand the error we get. We use pygame 2.1.0, we can update to the latest version
2. If not, is there a timeline on adding support?

**Comment by ankith26** [comment]
The latest pygame pre-release (2.1.3dev8) does release with python 3.11 wheels. The error being different doesn't matter because the issue is that pip tries to compile pygame from source when the wheel is missing, and obviously that can fail in different ways depending on the system trying to compile pygame.

The full 2.1.3 is expected to be released soon (hopefully within a week unless someone reports a major issue with the latest dev release now)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks
