### ISSUE TITLE
Using pygame with python3 on Mac

### ISSUE THREAD

**Issue by 99** [pygame/pygame#359]
Hi ,

I'm trying to make a simple program to run 
But it's failing with the below warning.

```
WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```
Can you please help to fix it ?
Thank you

Below is the simple script to help to reproduce it 

```
import pygame
import time

pygame.init()
screen = pygame.display.set_mode([800, 600])
image = pygame.image.load("python.png")

screen.blit(image, [0, 0])
pygame.display.flip()

time.sleep(5)
```

**Comment by OrionDark7** [comment]
Yeah I've had this same problem too. It doesn't stop the script from running, it just puts that message in the Python terminal-looking window. It doesn't seem like it would affect the sound quality either, it's just saying that the software that pygame uses is out of date. And you can easily hide it by just executing it with pythonw.

**Comment by cipri-tom** [comment]
@OrionDark7 is right, just use `pythonw` (ending with **w**) ! Thank you!

Details:

It really depends on how your `python3` is installed. The problem is that it should not be a virtual environment, but a framework (i.e. coming from a `something.app` package) and, most importantly, it should link to the macOS `CoreFoundation` Framework. See the last part of [this comment](https://github.com/ContinuumIO/anaconda-issues/issues/199#issuecomment-350534918) on Anaconda

**Comment by illume** [comment]
Thanks for all the debugging everyone. I added Anaconda instructions about pythonw to the https://www.pygame.org/wiki/GettingStarted page.

The console message will disappear with pygame 2.
