### ISSUE TITLE
Memory leak when calling pygame.image.load() per frame.

### ISSUE THREAD

**Issue by APPLCOLC** [pygame/pygame#3621]
**Environment:**

Windows 10 (Ameliorated Edition, Professional Edition)
Python 3.9.6
SDL 2.0.22
Pygame 2.1.3.dev8

**Current behavior:**

When calling pygame.image.load() every frame, even if not assigned to a variable, pygame leaks roughly 36 bytes of RAM every frame.
It attempts to regulate itself, but after running for roughly 4 hours the program gives up and lets it go up.

**Expected behavior:**

When calling pygame.image.load(), it should probably be expected that if the value is not assigned to a variable, it should not take up any RAM. 

**Screenshots**

![memleak](https://user-images.githubusercontent.com/120762118/208326554-5ed2f2b7-3490-4a6f-a05a-9fde81b31c72.png)
![image](https://user-images.githubusercontent.com/120762118/208326761-6f90d983-c922-4814-8e31-252dabee2b86.png)

**Steps to reproduce:**

1) import pygame
2) make a while loop that runs pygame.image.load() and then an image value

**Test code**

```
import pygame
while True:
    pygame.image.load("potato.png")
```

**Comment by Starbuck5** [comment]
I've done some investigation.

I believe this applies to every resource loader (except for pygame.freetype.Font)

I added a field to our SDL_RWops structs to track the file extension when a rwop is created, so the API can be more high level. I also updated `pgRWops_ReleaseObject` to free this extra memory. Apparently, `pgRWops_ReleaseObject` is not called when a RWop is released. The file object RWops have a special function get called, so I don't think they leak memory.

This won't be trivial to fix, but I don't think it'll be too hard.

**Comment by Starbuck5** [comment]
This may be more difficult to fix than I expected.

The `close` callback is already in use on the file-based RWops, because we're using SDL_RWFromFile. So if I want SDL_RWClose to deal with our custom field I have to monkey patch the `close` function, which doesn't seem particularly possible/ good in C.

So maybe our RWops can't be closed with SDL_RWclose and need pgRwops_Release (or whatever its called) to be used instead.

Right now only the freetype loader uses pgRwops_Release, all the rest use the `freesrc` parameters of their SDL functions.
