### ISSUE TITLE
pygame.mixer (corrupted size vs. prev_size while consolidating)

### ISSUE THREAD

**Issue by Red-exe-Engineer** [pygame/pygame#3692]
I don't know, but Google says C stuff so...

Happens at random when using this is a class, I don't know if it's because I'm using threading or not, needs more testing.
```py3
def _play(self, file: str):
    while mixer.music.get_busy():
        time.sleep(0.2)

    mixer.music.load(file)
    mixer.music.play()

    while mixer.music.get_busy():
        time.sleep(0.2)

def play(self, file: str):
    Thread(target=self._play, args=(file,)).start()
```

My system has weird audio bugs too, if I play more than one video at once media stops player, also audio just sometimes glitches.

Ask if you have a question, I'll try to check this every once in awhile

**Comment by Starbuck5** [comment]
Hello.
This post doesn't have much info in it. Our [bug report template](https://github.com/pygame/pygame/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) shows the kind of info we want.

`corrupted size vs. prev_size while consolidating` ? is that an error message?

When does this happen? Presumably you need to call the play function multiple times to get this error message?

You can't have multiple mixer.music tracks playing at once, isolating in a thread will not get around that.

**Comment by Red-exe-Engineer** [comment]
> You can't have multiple mixer.music tracks playing at once, threads will not get around that.

Thanks, but I'm not trying to play multiple files at once (hence the `while mixer.music.get_busy()`).

As for when it occurs I don't know, playing multiple media (audio/video at once) seems to cause problems for me so maybe that's the reasoning?.

**Comment by illume** [comment]
Hey hey @Red-exe-Engineer 

### Does this happen with previous versions of pygame?

It could be an issue with:
- pygame mixer
- or using threads with pygame mixer

Threads in python are a bit problematic with how they are implemented. Unless you're really careful with python threads, it's best if you can avoid them. Especially with games, because they can cause pauses or gaps in playback like here.

### Was there an error message somewhere?

Can you please paste the error message you get?

### It's been a while... comment to reopen?

It's been a while, so maybe you've moved on already. I'll close this. Let me know if it's still a problem, and comment here... we can reopen this if needed.
