### ISSUE TITLE
Issue with running pygame2.0 in Sugar desktop

### ISSUE THREAD

**Issue by chimosky** [pygame/pygame#3696]
Hi!

My name is Ibiam and I'm a maintainer at Sugar Labs, maintaining the [sugar desktop](https://www.sugarlabs.org/) and it's activities, we have a lot of activities that use pygame and we have a [sugargame module](https://github.com/sugarlabs/sugargame) that helps activities that use pygame run in sugar.

I'm trying to get it to support pygame2.0 so activities that use pygame can run properly in sugar but I've run into some issues, basically the sugargame module uses a `Gtk.Socket` and embeds the pygame display into the socket, `SDL_WINDOWID` is set before any pygame modules are initialized but when the test activity starts, there's just a black screen.

I'm having a hard time figuring out what the problem is as the test game works fine outside sugar and the `SDL_WINDOWID` is set to the id of the Gtk Socket and this worked fine in pygame 1.9.

I need help with figuring out what's wrong.

**Comment by MyreMylar** [comment]
Hello!

WE have actually been discussing this again recently in a pull request. 

SDL, the library pygame wraps, dropped support for `SDL_WINDOWID` when they switched from SDL 1 to SDL 2. Once we upgraded pygame to use SDL2, the support for this environment variable also when away in pygame.

However, there is a new - probably more intuitive way - to embed pygame displays in other windows in SDL 2 and there is currently an open [pull request here](https://github.com/pygame/pygame/pull/3685) for pygame that implements this feature.

Essentially instead of doing:

```
import os
os.environ['SDL_WINDOWID'] = window_id
display_surf = pygame.display.set_mode((800, 600))
```

You would do:
```
display_surf = pygame.display.set_mode((800, 600), hwnd=window_id)
```

I believe. Though I haven't tested the whole process extensively myself yet. 

If you are experienced with building libraries from scratch you could perhaps try this pull request and the new methodology and see if it works in your use case?

**Comment by chimosky** [comment]
> If you are experienced with building libraries from scratch you could perhaps try this pull request and the new methodology and see if it works in your use case?

I'll do that, thanks!

**Comment by illume** [comment]
The SDL_WINDOWID API being broken is considered a bug, and will be fixed.

I'm not sure the new API referenced that PR will be included in a release of pygame. It isn't merged yet either.

**Comment by novialriptide** [comment]
> The SDL_WINDOWID API being broken is considered a bug, and will be fixed.
> 
> I'm not sure the new API referenced that PR will be included in a release of pygame. It isn't merged yet either.

wdym "will be fixed", you've been inactive for months and kicked the entire active review team

**Comment by novialriptide** [comment]
> The SDL_WINDOWID API being broken is considered a bug, and will be fixed.
> 
> I'm not sure the new API referenced that PR will be included in a release of pygame. It isn't merged yet either.

wdym "will be fixed", you've been inactive for months and kicked the entire active review team

**Comment by illume** [comment]
There's a SDL_WINDOWID fix merged now.
