### ISSUE TITLE
Can't start Asteroids example

### ISSUE THREAD

**Issue by unster** [pygame/pygame#3701]
Hi team,

with following:

```
C:\Users\mikol\OneDrive\python\examples\asteroids>python --version
Python 3.10.9
```

```
C:\Users\mikol\OneDrive\python\examples\asteroids>pip show pygame
Name: pygame
Version: 2.1.2
Summary: Python Game Development
Home-page: https://www.pygame.org
Author: A community project.
Author-email: pygame@pygame.org
License: LGPL
Location: c:\users\mikol\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
```

I can't start Asteroids example game from Visual Studio Code:

```
PS C:\Users\mikol> & C:/Users/mikol/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/Users/mikol/OneDrive/python/examples/asteroids/main.py
pygame 2.1.2 (SDL 2.0.18, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\mikol\OneDrive\python\examples\asteroids\main.py", line 7, in <module>
    from actors import Player, Asteroid
  File "c:\Users\mikol\OneDrive\python\examples\asteroids\actors.py", line 7, in <module>
    class Player(Actor):
NameError: name 'Actor' is not defined
PS C:\Users\mikol> 
```

Please advise.

**Comment by gresm** [comment]
Question is: from where do you have asteroids example? Because this is for sure not from [pygame/examples](https://github.com/pygame/pygame/tree/main/examples). This issue probably has nothing with pygame itself, but the source of the example you have. ``Actor`` class doesn't exist in pygame library. Is there a chance that you are using pygame-zero example? ``Pygame-Zero`` does have an ``Actor`` class (pygame zero is an extension for pygame).

**Comment by oddbookworm** [comment]
I agree with gresm that this is probably from pygame zero's examples. In fact, here's the specific file that the error is complaining about in pygame zero's examples https://github.com/lordmauve/pgzero/blob/master/examples/asteroids/actors.py
