### ISSUE TITLE
Idea: BFXR-derived synthesizer

### ISSUE THREAD

**Issue by lordmauve** [pygame/pygame#404]
Pygame Zero recently added a very basic [tone generator](http://pygame-zero.readthedocs.io/en/stable/builtins.html#tone-generator) implemented using numpy and surfarrays.

There are many synthesizer libraries and endless possibilities for generating tones. However, in various Pyweeks and other projects I've found great value in [BFXR](https://www.bfxr.net/), a Flash-based synth which has a multitude of parameters to control. One of the nicest features is that it can generate random pickup, explosion, laser sounds and so on, by randomising various parameters within carefully picked ranges.

The ActionScript code for the BXFR synthesizer is here and is Apache licensed:

https://github.com/increpare/bfxr/blob/master/src/com/increpare/bfxr/synthesis/Synthesizer/SfxrSynth.as

It would be fairly difficult to port this code to numpy because this is written as a function that generates individual samples, not as manipulating multiple sample buffers. However I think it would be relatively easy to port this code to C. This would be a great feature to include in Pygame.

**Comment by illume** [comment]
That's quite a fun tool.

Funnily enough, I have a port of SFXR somewhere into python. sfxr is the original one from Ludum Dare, and it's in C. There's an SDL port on the page that I copied from. Unfortunately it's in one of my ancient archives... I couldn't find it with a quick look (Desktop/old/old/old/old/old/old/old/...).
http://drpetter.se/project_sfxr.html

I recall it took a day or so of frantic porting work. Lots of global variables and magic numbers. A lot of the fun is in the selection of simple generators, and simple effects... and then the chosen presets matched up to the sliders and buttons. But yeah, there's a C SDL1 version there, and only about 1200 lines.

Not sure it should be in pygame itself though (we already link 3 different c lib synths). Lots of people have done things like generators, envelopes and stuff it uses in python. But what makes it fun and useful is the named categorised presets and sliders imho.

**Comment by lordmauve** [comment]
What are the synth libs that Pygame links and how can I use them? I found the midi stuff, but that doesn't seem to do anything without physical midi devices, right?

**Comment by bitcraft** [comment]
Imo, there could be a nice benefit of a “batteries included” synth in the
spirit of SFXR. Without bundling it, windows users will never use it;
unless they are the masochistic type and enjoy building Pygame on windows.
I know you’ve got a lot on your plate Rene, but I don’t think it should be
written off either.

**Comment by lordmauve** [comment]
The needs of Pygame Zero would be:

* Needs to be fast/real time, preferably off game thread
* Needs to work with Pygame's mixer
* Needs no manual install steps

Something built into Pygame would be the best option; something that can be installed as a wheel and can populate a `pygame.mixer.Sound` (preferably with minimal copying) would be great.

**Comment by bitcraft** [comment]
Thanks for the detailed info @illume.  My frustration with timidity (and most midi libs!) makes me wish to see a sound/music library included with pygame, and its cool that you agree.  The ability to generate tones in realtime without exporting wav's, oggs, etc loading, organizing, etc would be really cool.  I wouldn't care if it is slow, as long as you could store a generated sound on disk or in memory for fast playback later (perhaps using the mixer API?).

These days, I'm not sure where midi is appropriate, though.  Most (99%?) of digital music creators today seem to be using software that won't work well with midi, due to all the creative techniques that midi doesn't support.  Add on top of that all the variations of sound fonts, the required midi drivers, sound daemons, etc....it seems like a lot more work for something most people wouldn't likely use.

If I had the time or ability, I would work on a software synth that roughly emulates vintage synth chips (or a binding).  Since I have neither the time or ability, all you get in my opinion.  😃

While I love power features like generators, considering that pygame brings in a lot of green programmers, any solution should have a "more simple" interface as well.

I agree with you too, the less C code the better.

@lordmauve I agree with your requirements, but I think its probably better as a "always included" feature, unless there are licensing issues.

**Comment by illume** [comment]
I was helping out a friend with his synth project... and came up with some examples of how to use pygame for sound generation (without numpy). Maybe useful or relevant. http://renesd.blogspot.com/2018/03/sound-generation-pygame-examples.html

**Comment by illume** [comment]
Whilst a cool idea, I guess this isn't going to be done by anyone any time soon.
