### ISSUE TITLE
pygame.error: > No available audio device when running pygame inside systemd with pulseaudio

### ISSUE THREAD

**Issue by moham96** [pygame/pygame#412]
when running pygame inside a systemd service I need to set 

```
Environment=DISPLAY=:0
Environment=HOME=/home/mohammad
Environment=XDG_RUNTIME_DIR=/run/user/1000
```

for the script to work, otherwise it would spit the error:

> pygame.error: > No available audio device

More explanation:
https://stackoverflow.com/questions/49059610/pygame-error-no-available-audio-device-when-running-pygame-inside-systemd-wit

**Comment by takluyver** [comment]
From your description on SO, I would guess that without those variables, it tries to use the ALSA audio device directly, but when something else uses PulseAudio, PA takes full control of the audio device. Setting those environment variables lets it find and connect to PA instead of trying to use ALSA directly.

There's some info on the Arch wiki about how connections to PA are made: https://wiki.archlinux.org/index.php/PulseAudio/Configuration#Connection_.26_authentication

**Comment by MyreMylar** [comment]
Recommend close as per @takluyver response. Unless you have further questions @moham96 ?

**Comment by MyreMylar** [comment]
Closing as above.
