### ISSUE TITLE
Deload a pygame.image

### ISSUE THREAD

**Issue by SomeoneUnknownForReal** [pygame/pygame#4228]
**Description**

I am making a feature in my rhythm game's chart editor to preview overlays which are animated and use images. The problem is that the when you want to see all of them the ram usage is like 3 gb. As I know from the docs and checking the image class there's no way to do that and it makes the game not compatible with devices that have ram below 8 gb.

**Comment by illume** [comment]
How many colors do they have? You could try reducing the color depth of the Surface, or the Surface size.

Another path could be to keep track of only the animations you need at that time. Then only decompress the images you need for the animation. Maybe it's fast enough.


I'm going to close this issue, because I don't know if it's a bug or a feature request.

**Comment by qhf566** [comment]
Who has a big factory, developed in the past 5 years, has not been operated in China, and has finished the development of the game, contact me 809996677
