### ISSUE TITLE
NPC basic in-game movement

### ISSUE THREAD

**Issue by ionbot04** [pygame/pygame#4308]
Issue Description
I am currently in the process of developing an NPC for my game, and I am focusing on implementing its movement mechanics. However, I am encountering several issues related to the use of the bitwise OR operator | in my code. Specifically, I am seeing error messages indicating that the operator | is not supported for various types. The error messages are as follows:

Operator "|" not supported for types "FloatConstant | IntConstant | LongConstant | StringConstant | Unknown"
Operator "|" not supported for types "FloatConstant" and "FloatConstant"
Operator "|" not supported for types "FloatConstant" and "IntConstant"
Operator "|" not supported for types "FloatConstant" and "StringConstant"
Operator "|" not supported for types "IntConstant" and "FloatConstant"
Operator "|" not supported for types "IntConstant" and "StringConstant"
Operator "|" not supported for types "StringConstant" and "FloatConstant"
Operator "|" not supported for types "StringConstant" and "IntConstant"
Operator "|" not supported for types "StringConstant" and "StringConstant"
These errors appear to be related to the handling of different data types within the code. I have thoroughly reviewed the sections where these errors are thrown, but I am unsure of the correct approach to resolve these type mismatches. Given that the issue is recurring and seems to involve various combinations of data types, I suspect there might be a fundamental misunderstanding or misuse of the operator in my implementation.

Additionally, while addressing these specific errors, I would appreciate it if you could review the entire code for any other potential issues or improvements. This includes examining the logic for NPC movement, the handling of user inputs, and the drawing functions to ensure that everything is functioning as expected.

Below is the code I am currently working with:

`import pygame
from pygame.locals import *
from OpenGL.GL import *
from OpenGL.GLU import *
import random

# Initialize Pygame
pygame.init()

# Set up display
width, height = 800, 600
pygame.display.set_mode((width, height), DOUBLEBUF | OPENGL)
gluPerspective(45, (width / height), 0.1, 50.0)
glTranslatef(0.0, 0.0, -5)

# NPC settings
npc_position = [0, 0, 0]
npc_direction = [random.uniform(-0.1, 0.1), random.uniform(-0.1, 0.1), 0]
npc_speed = 0.05

def draw_cube():
    glBegin(GL_QUADS)
    for face in faces:
        for vertex in face:
            glVertex3fv(vertices[vertex])
    glEnd()

# Define vertices and faces of a cube
vertices = [
    [1, -1, -1],
    [1, 1, -1],
    [-1, 1, -1],
    [-1, -1, -1],
    [1, -1, 1],
    [1, 1, 1],
    [-1, -1, 1],
    [-1, 1, 1]
]

faces = [
    (0, 1, 2, 3),
    (3, 2, 7, 6),
    (6, 7, 5, 4),
    (4, 5, 1, 0),
    (1, 5, 7, 2),
    (4, 0, 3, 6)
]

def move_npc():
    global npc_position, npc_direction
    npc_position[0] += npc_direction[0] * npc_speed
    npc_position[1] += npc_direction[1] * npc_speed

    # Change direction randomly if cube goes out of bounds
    if abs(npc_position[0]) > 2 or abs(npc_position[1]) > 2:
        npc_direction = [random.uniform(-0.1, 0.1), random.uniform(-0.1, 0.1), 0]

def handle_input():
    keys = pygame.key.get_pressed()
    if keys[K_e] and pygame.mouse.get_pressed()[0]:
        print("Clicked with 'E' and Left Click!")
        return True
    return False

# Main loop
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glLoadIdentity()

    # Move NPC unless "E" + Left Click is pressed
    if not handle_input():
        move_npc()

    # Draw NPC (cube)
    glPushMatrix()
    glTranslatef(npc_position[0], npc_position[1], npc_position[2])
    draw_cube()
    glPopMatrix()

    pygame.display.flip()
    pygame.time.wait(10)

pygame.quit()
`

Please review the code and provide guidance on how to address these type-related issues. If there are any other improvements or corrections needed, I would greatly appreciate your feedback.

Thank you for your assistance!

**Comment by LuckyIntel** [comment]
To be honest i've never used PyOpenGL so i can't do that much help.Can i ask why you're using time.wait?Also is gluPerspective in PyOpenGL working with radians?If it doesn't consider creating a function like this to get radians : 

```py
def radians(x): return x * (180 / math.pi)
```
About bitwise or operator, this is most likely to be a problem with your writing instead of PyGame.I think bitwise or operator behaves different in python.I don't know python operators that much.Consider using a document to see how python operators work.

If you're new to opengl stuff and concepts, try www.learnopengl.com

Not to adversite or anything but i also have WebGL and OpenGL examples in my profile you can check out if you need additional help.It's not in Python tho it is in Javascript and C++ but these concepts will also work in python i believe.

**Comment by ionbot04** [comment]
**Thank you for your response!** I appreciate your honesty and suggestions.

Regarding time.wait, I'm using it in the main loop to control the frame rate of the game, but I could consider switching to pygame.time.Clock() for more precise control.

As for gluPerspective, it's good to clarify that the function works with degrees, not radians. I'll take your suggestion to create a helper function for converting radians to degrees if needed, though in this case, degrees are already what's required.

Regarding the bitwise OR operator (|), you're correct that it's a Python-specific behavior and may differ from how it’s used in other languages. It seems my issue is related to using | with different data types, which is causing the errors. I’ll review the operator documentation and adjust the code accordingly.

Thank you for pointing me to learnopengl.com—it's a fantastic resource! I'll also take a look at your WebGL and OpenGL examples for additional insights, even if they’re in different languages. Understanding the core concepts can definitely help me in Python as well.

Thanks again for your assistance!

**Comment by LuckyIntel** [comment]
Also i don't know if python has a security for this but your aspect ratio can cause errors if python doesn't have a security.That's because when you minimize your pygame window i believe that it should return you a division error telling you that you can't do divisions with 0.However your pygame window seems to be already okay since your width and height is fixed to 800 and 600.When setting a resizable window it is a good exercise to have an aspect ratio variable that is calculated with some size callback.When aspect ratio is divided by 0, you must try giving aspect ratio a random value like 1/1 or 4/3.If the window width and height is always fixed you don't need to do these.In my OpenGL example, i have an aspect ratio calculation example in the onResize void.This simple 3-4 lines of code helps with aspect ratio issues.You can also see that onResize void is connected to a size callback.

Pardon me for my english.I am not a native.

**Comment by ionbot04** [comment]
Neither is my English good, but I really would like to thank you for your help, even though you don't know pyopengl that well.

**Comment by ionbot04** [comment]
I have fixed the issue! Woo Hoo! ❤️ Thanks.
