### ISSUE TITLE
Thick Line Bug

### ISSUE THREAD

**Issue by DaFluffyPotato** [pygame/pygame#448]
Drawing thick lines is a bit buggy.

- pygame.draw.line with width>1 http://www.pygame.org/docs/ref/draw.html#pygame.draw.line
- clip_and_draw_line_width in https://github.com/pygame/pygame/blob/20f3b376ffb087fb4995f2d58570203355357a04/src/draw.c#L685
- [x] example showing error.
- [x] unit test (good first issue)
- [x] src/draw.c fix

---

![pygame_bug](https://user-images.githubusercontent.com/28032741/39226850-027e6a6a-4823-11e8-893f-03c969c06c73.gif)

Which can result in this when making a bunch of short lines at different angles:
![pygame_bug](https://user-images.githubusercontent.com/28032741/39226878-39723f38-4823-11e8-9b34-25f858fb91e7.png)

Code for reproducing: https://pastebin.com/wNQj46E6
```python

#!/usr/bin/python3.4
import pygame, sys
mainClock = pygame.time.Clock()
from pygame.locals import *
pygame.init()
screen = pygame.display.set_mode((200,200),0,32)
while True:
    screen.fill((0,0,0))
    mx,my = pygame.mouse.get_pos()
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
    pygame.draw.line(screen,(255,255,255),(50,50),(mx,my),30)
    pygame.display.update()
    mainClock.tick(40)

```

**Comment by illume** [comment]
The trick is to draw not-antialiased lines in the middle parts. So only the edges of the rectangle are drawn with AA. This way none of those gaps should appear in the middle.

**Comment by DaFluffyPotato** [comment]
The issue I was trying to point out was the ends of the lines always being flat and changing angles. That’s what resulted in the problem in the picture.

**Comment by daniel-molina** [comment]
I am not sure if I understand correctly the problem, so I will report what I find. Using the following code:

```python
import pygame, sys
from pygame.locals import *

def draw_line(x,y):
    screen.fill((0,0,0))
    pygame.draw.line(screen,(255,255,255),(50,50),(x,y),30)
    pygame.display.update()

pygame.init()
screen = pygame.display.set_mode((200,200),0,32)

# Some images with no problems
# (line totally inside the screen)
for p in [(134,144),(74,0),(199,100)]:
    draw_line(*p)
    input()

# Some images with problems
# (line out of the screen due to the thickness)
for p in [(140,0),(0,120),(199,198)]:
    draw_line(*p)
    input()
```

I get the following images with no problems, when the white line is totally inside the screen

![im1](https://user-images.githubusercontent.com/42525051/44369163-bb2bcf80-a4d5-11e8-8ddf-06e8beef28f7.png) ![im2](https://user-images.githubusercontent.com/42525051/44369172-c121b080-a4d5-11e8-8842-010b2533747e.png) ![im3](https://user-images.githubusercontent.com/42525051/44369180-c7b02800-a4d5-11e8-8b4f-b529d026c5b2.png)

and the following ones with probably those gaps mentioned, only appearing when part of the line is outside the screen due to the thickness:

![im4](https://user-images.githubusercontent.com/42525051/44369217-f29a7c00-a4d5-11e8-97d4-b8e0264a5f2a.png) ![im5](https://user-images.githubusercontent.com/42525051/44369218-f29a7c00-a4d5-11e8-80a4-d404cdd5351a.png) ![im6](https://user-images.githubusercontent.com/42525051/44369219-f29a7c00-a4d5-11e8-9bb4-46a55092c3b5.png)

Maybe that distinction is the key for solving the bug.

**Comment by illume** [comment]
Oh good! It seems you have found a few failing cases :)

So the next step is to turn that code into a unittest. You could use the surf.get_at(...) to get a pixel which should be white, but is currently black in the failing examples you found.

**Comment by MightyJosip** [comment]
This is not the problem with drawing lines, but it is the problem with clipline function. If I disable it I get the line with no empty pixels, but sadly line doesn't stay within the screen. (if it touches the right bound of the surface it will continue to draw to the left). I will continue to try to fix this, but if I don't do that and someone else tries I just want to make sure he knows it is not the problem with the drawing itself.

**Comment by illume** [comment]
Good find! Thanks @MightyJosip

**Comment by illume** [comment]
Thanks to @MightyJosip, @DaFluffyPotato, @daniel-molina and @charlesej this is fixed.
