### ISSUE TITLE
Test suite : documentation and cleanup ?

### ISSUE THREAD

**Issue by e1000** [pygame/pygame#496]
Hello,

I tried to write some tests, but I found the test suite a bit confusing ;

First, the test code seems to follow a bit the principle of the *broken window* ;-) : 

[edit : transformed this list into a check lst]

- [x] some 15 occurences of the strange pattern `if 1: <code_block>` 
- [ ] cleanup many deprecated legacy `assert*` and `fail*` methods
- [x] cleanup *sndarray_test* : `arraytype` is always `= "numpy"` (l. 20), but many there are many occurences of `if [not] arraytype: ...`
- [ ] *image_test.py* : use the **tempfile** module instead of `finally: os.remove` 
- [x] *mixer_test.py* : use `assertRaises` instead of `try/except/else`
- [x] use `setUp` and `tearDown` instead of `try/finally` like in *midi_test.py* (maybe splitting some *TestCases* in different classes)
- [ ] Need of big PEP8 cleanup (white space, unused imports, commented code that seems to have no meaning, etc )

[edit] ~~If~~ we support only Python >= 2.7 , so we ~~could~~ can

- [x] use  `unittest.skip` and  `unittest.skipIf` decorators instead of indentation (cf *test/surflock_test.py*) etc
- [x] use of `setUpClass` and `tearDownClass` where it makes sense
- [x] use `with self.assertRaises` 

I'd also like some documentation of how the suite works, specially for following points:
 
* where does "*pygame.tests*" package come from and what's the meaning of *test* vs *pygame.tests* import ? Related to that, the need and meaning of **is_pygame_pkg** ?
 Why can't we use the standard `python -m unittest test_module.TestCase` ?
* why do we copy-paste the docstring of the methods into the test suite ?  (the *docstring* of the methods might evolve, while these commmented docstrings are 10 years old; 
  copying each time seems strange & the developer can look it up anyway...)
* how does the *sth_tags.py* work ?
* The *midi_test.py* uses in test method *docstrings* sth like `|tags: interactive|` ; what's the
  meaning of it?
* what is the meaning of `test/util/build_page/` ? 

I could do the standard code cleanup, but it would be very noisy commits, possibly generating annoying merge conflicts. Which cleanups should be done or not ? One big test-cleanup Pull request ok ?

**Comment by e1000** [comment]
Oh, one more thing : the very useful [lets-write-unittest post](http://renesd.blogspot.com/2018/07/draft-of-lets-write-unit-test.html) refers to *Python3/unittest*, but since 2.7 many things has been added, like **unittest.mock** (which might be helpfull to use anyway, but as 3rd party library in Python2), **subTest** , etc so this might be misleading ...

**Comment by illume** [comment]
Hello!

thanks for the very valuable list of improvements we could make.

Please check out test/README.txt for some documentation on the test runner.

The interactive 'tag' is a way for us to mark tests that need a human there to drive them.
The pygame tests are designed so that they can be run in an installed instance of pygame. So you can run them with `python -m pygame.tests` as well. This is important to be able to allow end users to run tests for us, and for us to also test the installed pygame. The setup.py file is where it knows how to move the 'test' folder into pygame.tests at installation time.

In regards to being able to contribute a test, I'd suggest focusing on one small thing. It's easy to get lost in the giant tumble of such a large old code base and start thinking about the multitude of ways that it could be improved on a global level. And with pygame, there is an almost unlimited amount of areas that need improvement.

In time each of the test files should be cleaned up (to be pylint clean). We have been through a process of 'modernization' with some of the C files, but we also need to do this with the test files. This 'refactoring' should happen in small commits so we can make sure no 'regressions' creep in, and also so that it's easier for people to review the changes.

cheers,

**Comment by e1000** [comment]
Concerning tagging of tests, there seem to be many different styles : For modules, I've seen both `sth_tags.py` and a `__tags__`, then `__tags__` at class level, then some special way for methods  with the docstring .

Any chance to reduce it to two ways of doing it, eg : 

* `__tags__` at module or class level
* a `@tag('hello')` decorator

?
