### ISSUE TITLE
docs not being included

### ISSUE THREAD

**Issue by illume** [pygame/pygame#519]
From https://twitter.com/pygame_org/status/1036699852334411781
```
Ubuntu based distro.

In fact, the error I get when I run "python -m http://pygame.docs " on my terminal is precisely "(~home_folder)/.local/lib/python3.5/site-packages/pygame/docs/index.html: No such file or directory".
```

The tar.gz and .whl files have the docs. https://pypi.org/project/Pygame/#files

Maybe it has to do with how it was installed? pip(with what options?) or apt-get?

**Comment by algorithmpub** [comment]
Thank you for creating the issue. I don't have the exact details of my pip install, except for the fact I used pip3, since I use pygame with my python 3 version.

Details:
OS: Lubuntu 16.04 LTS 32-bits
Installation: via pip3 (additionally, I don't remember having updating the library via pip3 but I guess there's a slight chance that I did so)
Python: 3.5.2
Pygame: 1.9.3

Problem description: As mentioned above, when I run the "python -m pygame.docs" command on my terminal I get precisely the following error message: "(~home_folder)/.local/lib/python3.5/site-packages/pygame/docs/index.html: No such file or directory". After taking a good look in the folder mentioned on the error message, I noticed not only the index.html file is missing, but the folder doesn't seem to be completed. The exact contents were:
__init__.py
logos.html
__main__.py
__pycache__
pygame_logo.gif
pygame_powered.gif
pygame_small.gif
pygame_tiny.gif
ref/docscomments.json

And nothing more. Perhaps this was a problem on installation? I can't really tell since the "python -m pygame.docs" command was something I only tried recently, after more than a year of using the library in this same computer. And despite all that, all my pygame applications work fine, never had a single issue besides this one. Even, the "python -m pygame.tests" command runs all the tests nicely.

**Comment by algorithmpub** [comment]
obs.: somehow github displayed the init and main files and the pycache folder without the leading and trailing double underscores, but they have them.

**Comment by MyreMylar** [comment]
This is exactly what happens if the pygame code is built from source (rather than a pypi package). The docs are built separately from the setup.py file with:

`python setup.py docs`

When you are in the pygame source directory. So are not be included if you just do:

`python setup.py build`
`pip install . -U`

Or something similar. 

The solution for the average user who ends up building pygame from source (which can be triggered in lots of edge installation cases):

a) Simplest:  read the docs online at pygame.org/docs
b) Slightly more complex: Build the docs from source after grabbing the source from GitHub as well with the command above.

**Comment by MyreMylar** [comment]
Closing this because the docs are definitely manually buildable from source, included in wheels and available online.
