### ISSUE TITLE
pygame infects stdout

### ISSUE THREAD

**Issue by metulburr** [pygame/pygame#542]
```
>>> import pygame
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
>>>
```

Anything written which uses pygame, infects stdout with this. Unacceptable behavior for a library.

**Comment by ase1590** [comment]
just remove it from the [__init__.py file](https://github.com/pygame/pygame/blob/master/src_py/__init__.py#L495) if you have such an issue with it.

**Comment by metulburr** [comment]
you can remove it but the point is users should not have to

**Comment by illume** [comment]
'Infects' is maybe the wrong word, but I understand where you are coming from.

- If a user wants to remove that for other people in their pygame using app, they can wrap stdout whilst they import pygame.
- Locally, people can comment out the print line in their pygame install at `pygame/__init__.py` file. `import pygame;print(pygame.__file__)`
- Or, they could help pygame 2 get done - which is when this will be considered for removal next.

Why is it there? We(and I) needed (and need) help. Because pygame needs contributors. It has millions of users, and less than 0.001% contribute anything to it. Of course putting a link there doesn't actually attract contributors, spending months cleaning up pygame, writing docs, and helping people contribute does.

**Comment by Julian-O** [comment]
[PygameSilent](https://pypi.org/project/pygamesilent/) is a new shim for PyGame that applies the #559 workaround more easily than directly applying environment variables or overriding stdout at every import.

**Comment by illume** [comment]
Opinions are like... you.

**Comment by illume** [comment]
@Julian-O stop spamming repos. Your package is buggy and pointless. People can just use PYGAME_HIDE_SUPPORT_PROMPT. Rather than depending on a potentially dangerous random package from someone who has done nothing noteworthy.

**Comment by metulburr** [comment]
Nice. Im glad you guys added this. 
PYGAME_HIDE_SUPPORT_PROMPT
Thanks.

**Comment by monokal** [comment]
I'm having the same issue now with pygame spamming my project's STDOUT. Setting `os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"` isn't disabling it either for some reason (Python 3.8.1, pygame 1.9.6, pipenv venv).

**Comment by monokal** [comment]
Just a note to anyone who may come across this via Google, etc. You must set the environment variable BEFORE importing pygame. E.g:

```python
os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'
import pygame
```

**Comment by slzero-X** [comment]
Okay this drama needs to end, don't like it? Tough, nothing is free dude. While you argue that pygame is, keeping it in development is not free.
