### ISSUE TITLE
Unclean source tarball 1.9.4

### ISSUE THREAD

**Issue by Natureshadow** [pygame/pygame#543]
Hi,

the source tarball for 1.9.4 uplaoded to PyPI contains a lot of stuff that should not be in there, among that are pre-built Python objects in __pycache__ directories and pyc files, pre-built documentation along with code copies of Sphinx, jQuery and underscore files, and the like.

Can you please upload a new, clean source tarball, probably as 1.9.4.post1 or something?

This makes updating the Debian package unnecessarily difficult.

Thanks!

**Comment by illume** [comment]
Thanks for pointing that out.

Would waiting for a pygame 1.9.5 be an ok option instead of doing a separate pygame 1.9.4 release? I'd prefer to make the release scripts work so they don't include all that stuff you mentioned next time, rather than doing it manually. I'm guessing 2-4 weeks away. There's no major bugs or features to finish before the release, except for getting the source release to not include this junk you mentioned.

But if you'd prefer a 'post' release for other timing reasons, I will make one for you.

ps. For anyone else reading and wondering about 'post' in versions... 'postN' is a valid name as per pep440. See https://www.python.org/dev/peps/pep-0440/#post-releases

**Comment by Natureshadow** [comment]
2-4 weeks is ok. I wouldn't want to wait much longer because this is currently preventing pygame being in Debian buster at all.

**Comment by illume** [comment]
Ok, thanks. I'll see how we're going in a week on 1.9.5, and can decide then.

cheers,

**Comment by Natureshadow** [comment]
Pinging because 10d >> 7d ;)

**Comment by Natureshadow** [comment]
There still does not seem to be any progress. Please upload a valid 1.9.4 release tarball.

**Comment by illume** [comment]
Hi,

I hope this one is better:
https://www.pygame.org/ftp/pygame-1.9.4.post1.tar.gz

956e43144348d9a05a40d5a381b5eaee  pygame-1.9.4.post1.tar.gz
9eb5938710f2750da3995cab64b3ca8c88d92c73  pygame-1.9.4.post1.tar.gz

I did a fresh checkout and `python setup.py sdist`, after changing the version in setup.py to "1.9.4.post1".

**Comment by Natureshadow** [comment]
Looks good. Please upload that tarball to PyPI so we can automatically process it from there.

**Comment by illume** [comment]
Thanks for that.
Here it is: https://pypi.org/manage/project/Pygame/release/1.9.4.post1/

**Comment by illume** [comment]
Apparently just uploading the post1 source release makes many versions of pip download the wrong file. I can't just rename the files and upload them, because of a consistency check against using the same files. Making all those files again would take about a day of effort.

So, I need to either:
- remove the 1.9.4.post1 release from pypi, 
- remove the 1.9.4.tar.gz from pypi,
- and upload the 1.9.4.post1 release as 1.9.4.tar.gz

However, I can't replace the 1.9.4 tar.gz file on pypi without breaking other systems which use the checksums of that file.

I'm removing 1.9.4.post1 release from pypi until I figure out what to do.

**Comment by Natureshadow** [comment]
> Apparently just uploading the post1 source release makes many versions of
> pip download the wrong file.  I can't just rename the files and upload
> them, because of a consistency check against using the same files.  Making
> all those files again would take about a day of effort.
> 
> So, I need to either:
> - remove the 1.9.4.post1 release from pypi, 
> - remove the 1.9.4.tar.gz from pypi,
> - and upload the 1.9.4.post1 release as 1.9.4.tar.gz
> 
> However, I can't replace the 1.9.4 tar.gz file on pypi without breaking other systems which use the checksums of that file.
> 
> I'm removing 1.9.4.post1 release from pypi until I figure out what to do.

No!

Do NOT break correctly funcitoning software just because some other software
is broken.

I can tell you that havin a .post1 version works perfectly, even with pip,
so please fix whatever is wrong instead of breaking everything else.

You must NEVER remove a release that was once uploaded.

Please make sure the exact tarball that was on PyPI as 1.9.4.post1 stays
available there. Thanks!

**Comment by illume** [comment]
pygame-1.9.4.post1 is still available at: 
https://www.pygame.org/ftp/pygame-1.9.4.post1.tar.gz

**Comment by Natureshadow** [comment]
> pygame-1.9.4.post1 is still available at: 
> https://www.pygame.org/ftp/pygame-1.9.4.post1.tar.gz

I will not re-upload a package to change the URL the source was retrieved
from. Please keep all releases in one place.

If you want, I can certainly help you find out what's wrong with pip, if you
catch me on XMPP or by e-mail, but by all means don't break other people's
stuff after you gave them a release.

**Comment by illume** [comment]
You're advocating to break all downloads for an unreleased Debian package affecting you, verses breaking things for thousands of other people. I choose to break it for the unreleased package that could be fixed by changing a URL.

If you don't want to move it back to using the https://www.pygame.org/ftp/ as it was before, then fine. That's your choice.

**Comment by Natureshadow** [comment]
> You're advocating to break all downloads for an unreleased Debian package
> affecting you, verses breaking things for thousands of other people.  I
> choose to break it for the unreleased package that could be fixed by
> changing a URL.

This has nothing to do with reality. I do not see why uploading a valid
version to PyPI should break pip. Versions with .post1 are proven to work
flawlessly with pip.

Why not explain what you think the issue with pip is?

Also, the package is *not* unreleased.

**Comment by Natureshadow** [comment]
> If you don't want to move it back to using the https://www.pygame.org/ftp/
> as it was before, then fine.  That's your choice.

Well, we did not switch to PyPI just so, but because the site you mention
was out of sync for months or even years…

**Comment by illume** [comment]
I appologise for the inconvenience, but this is the least shit option available.

**Comment by Natureshadow** [comment]
> I appologise for the inconvenience, but this is the least shit option available.

Maybe it wouldn't be if you said what the issue with pip seems to be and
gave others a chance to look into it.
