### ISSUE TITLE
Still two test failures on little-endian

### ISSUE THREAD

**Issue by Natureshadow** [pygame/pygame#587]
Hi,

we still have the following test failures:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902035
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902036

I skipped the tests in Debian with a local patch, but please also do something about it upstream for the next release ☺.

**Comment by plugwash** [comment]
Hi

I am the guy who filed those two Debian bug reports. I don't personally care much for either ppc64el or s390x but the build failures were blocking migration of pygame to testing and I do want to see a python3-pygame package in testing. 

Debian bug 902035 is a  failure of test_render_args on ppc64el. I have not looked into it deeply but it looks like some sort of font rendering discrepancy. Natureshadow skipped that test in Debian on ppc64el which seems like a reasonable course of action to me. 

Debian bug 902036 is a failure of bufferproxy_test on s390x. Natureshadow appears to have been a bit confused about this bug, he responded to a testsuite failure on s390x by disabling a test on ppc64el. I just tested and after re-enabling the bufferproxy test on ppc64el the package still builds for me (on a Debian porterbox).

After Natureshadow uploaded 1.9.4.post1+dfsg-1 and I noticed that s390x was still failing I decided to dig into the code and see if I could find the actual cause of the bug and I was able to do so. 

The issue turned out to be a single character typo, "Py_VERSION_HEX" was used instead of "PY_VERSION_HEX" in a #if . The #if was used to choose a format string based on the python version. On 64-bit architectures this led to reading a 32-bit value into a 64-bit variable. The variable was previously initialised to zero, so on little endian this worked, but on big endian it resulted in a value 4294967296 times larger than it should be causing the test to fail.

After posting the fix to the Debian bug I went to put together a pull request upstream, but it appears that the broken #if has been ripped out as part of ripping out support for python versions below 2.6 ( https://github.com/pygame/pygame/commit/49b930a7e759b00bb5f018b38f16d46ca3a6fa85#diff-203285152c5b04bc49b0b23e2ef82817 ), so the latest upstream development code looks OK (I haven't actually tested it though).

**Comment by dlon** [comment]
I think 902035 is a bug rather than a bad test. It renders black text on a white background, and the result is a yellow (255, 255, 0) pixel or background. Why would there be yellow anywhere?

**Comment by stefanor** [comment]
> Debian bug 902035 is a failure of test_render_args on ppc64el. I have not looked into it deeply but it looks like some sort of font rendering discrepancy. Natureshadow skipped that test in Debian on ppc64el which seems like a reasonable course of action to me.

Debian is still carrying a patch to skip this. We should probably keep this bug open until that is applied upstream, or the issue is resolved.
