### ISSUE TITLE
Python type stubs for pygame

### ISSUE THREAD

**Issue by rchen152** [pygame/pygame#668]
I'd like to contribute some type stubs for pygame to https://github.com/python/typeshed, a repository of Python type information that is used by type checkers. Per https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library, I'm first opening this issue to request permission from the maintainers of pygame.

**Comment by illume** [comment]
Great :) Thank you.

Some thoughts and questions below...

---

It would be preferable to have them inside of pygame, because they would also be useful for documentation and maintenance would be easier. Does this sound ok? I wonder if there are some advantages to adding them into the typeshed?

We are a python2, and python3 single code base, with a mixture of python/C/Cython - so type stubs would maybe make sense (rather than specifying them inline).

The files would probably live in src_py/ So for example, src_py/display.pyi ?

The docs currently have a form of argument and type specification which is not machine checked, and not entirely consistent.

Maybe you know of a good workflow which uses the types in documentation? Also, perhaps [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints) can be used, or modified to allow using the type definitions in documentation. It's also possible to defer the task of using the types in documentation to another time, if there is no known good workflow for this.

Perhaps we need to modify some sort of sphinx autodoc tool for this. We already generate .h files containing documentation for our C modules from the restructured text docs.

The test suite doesn't have 100% coverage, but may be useful to generate type hints by recording. There are also many examples/ both included in pygame and elsewhere. The chimp.py, and aliens.py examples are probably a good place to start for deciding which modules to type first. Core parts are things like Rect, Surface, display.set_mode, sprite, image.load, and draw. So these would perhaps be good for the first modules to do? Would it be good to do one or two parts at a time completely?

We use appveyor, and travisci for continuous integration. The buildconfig folder is where we are trying to keep as much config as possible if any needs to be added.

Links to our developer guide and such can be found here: https://www.pygame.org/wiki/Contribute

**Comment by illume** [comment]
pep 561 is relevant: https://www.python.org/dev/peps/pep-0561/

**Comment by illume** [comment]
numpy is making a `numpy-stubs` package available.
https://github.com/numpy/numpy-stubs

**Comment by illume** [comment]
I asked for some feedback on the typing-sig mailing list.
https://mail.python.org/archives/list/typing-sig@python.org/thread/QPJC7PM6V46GTM24DEXY2BTZSEH623X6/

- `__annotations__` is not supported by C defined functions. So using type stubs seems the only possible way.
- python ast module can read python stubs. Not the python 2 commented ones. So it's possible to extend sphinx-autodoc-typehints with this.

**Comment by rchen152** [comment]
Sorry for the late response! To be honest, this isn't something I have a ton of time to spend on - a few months ago, I wrote a few pygame stubs (bufferproxy, color, event, joystick, rect, surface) that https://github.com/google/pytype uses to type-check Google code, and I was looking for somewhere Google-external to put them in case anyone else might find them useful. I'm happy to send a PR for these to wherever you'd like them to go (the only reason I suggested typeshed is that it's the most straightforward way I know to make typing information available to type checkers), but I don't think I can do more stubs or make changes to pygame tooling. Does that still sound ok to you?

**Comment by illume** [comment]
That would be wonderful :)

How about putting them in buildconfig/pygame-stubs for now?

**Comment by rchen152** [comment]
I sent https://github.com/pygame/pygame/pull/678.

**Comment by illume** [comment]
Closing this because another issue is open for tracking testing/implementation of types in:
https://github.com/pygame/pygame/issues/839
