### ISSUE TITLE
Conan, the C/C++ package manager for CI dependencies

### ISSUE THREAD

**Issue by notpygame** [pygame/pygame#997]
Status:
- conan is being used for the mac release. 
- [ ] no portmidi package is available for conan (I've requested a portmidi package here: https://github.com/conan-io/conan-center-index/issues/3009)
- [ ] On windows there is a problem with some dependencies and conan (sdl_ttf at least I think).
- [ ] ubuntu/debian/raspberian linux has various issues.
- [ ] the SDL conan packages don't seem to get much attention (they are still on bincrafters for example)

---
For making binary wheels we currently have to maintain dependencies on Linux, Windows, and Mac builds. In the future we may also want to support iOS, Android, and ...

Instead, maybe [conan](https://conan.io) works well enough for us now? The benefit being we can use packages maintained by other people(and help out too). There are now SDL2, portmidi, and various other packages we use. Judging by the SDL2 package, it gets a lot of attention.

There's no docs (after a short search) on using it for the dependencies of python distutils extensions, but conan is itself written in python so I'm sure they'll be able to get something working.

**Comment by illume** [comment]
Not really related, but useful for testing on MacOS using virtual machines. https://github.com/myspaghetti/macos-guest-virtualbox

**Comment by illume** [comment]
Conan doesn't have direct support for distutils projects as of yet. It does however have "generators" which can create build output, and some people have used this before for their packages.

- Using a generator: https://docs.conan.io/en/latest/howtos/custom_generators.html
- Using the json generator and some glue code: https://dmerej.info/blog/post/chuck-norris-part-5-python-cffi/
- json generator docs https://docs.conan.io/en/latest/reference/generators/json.html

## proposal

- a buildconfig/config_conan.py would be made (starting from config_unix.py probably).
- declare dependencies(libsdl, libpng, etc) in a 'conanfile.txt', using the json generator (somewhere in buildconfig/).
- conan_config.py would read the json file for library paths, and include paths.
- setup.py would need to be changed to allow using conan, rather than the one detected. (maybe with a command line arg, or environment variable).
- conan_config.py would install/upgrade the dependencies by default.

**Comment by illume** [comment]
The only dependency I can't find is `portmidi`.

https://github.com/bincrafters/conan-sdl2
https://github.com/bincrafters/conan-sdl2_mixer
https://github.com/bincrafters/conan-sdl2_image
https://github.com/bincrafters/conan-sdl2_ttf
https://github.com/bincrafters/conan-fluidsynth

https://conan.io/center/libpng/1.6.37/
https://conan.io/center/zlib/1.2.11/
https://conan.io/center/freetype/2.10.1/
https://conan.io/center/flac/1.3.3/
https://conan.io/center/libwebp/1.1.0/
https://conan.io/center/libmpg123/1.25.13/
https://conan.io/center/ogg/1.3.4/
https://conan.io/center/vorbis/1.3.6/

**Comment by illume** [comment]
Install conan and add the bincrafters repo...

```
pip install conan
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
```

**Comment by MyreMylar** [comment]
I believe this is the issue that is hopefully eventually going to solve the problems with out of date downloaded dependencies when self compiling on windows.

**Comment by illume** [comment]
Yeah, I hope it will work nicely on windows too! Seems to be one of their most popular platforms, so I'm hopeful.

One place was using it with android for cross compiling, so I'm hopeful it might be useful there too. https://docs.conan.io/en/latest/integrations/ide/android_studio.html

**Comment by illume** [comment]
Status:
- it is being used for the mac release. 
- no portmidi package is available for conan.
- On windows there is a problem with some dependencies and conan (sdl_ttf at least I think).

**Comment by illume** [comment]
Started a portmidi package here: https://github.com/conan-io/conan-center-index/pull/3186

**Comment by illume** [comment]
The PR needs finishing and moving to the new repo: https://github.com/bincrafters/conan-sdl2/pull/29

**Comment by illume** [comment]
At this point I've given up on conan. 
Mainly because conan is still in flux, and some of our dependencies aren't in their port trees.
Additionally, the game dev crowd don't seem to be so interested in conan. So there's not good maintenance because not so many people are using our libs.
The existing code is sort of broken, with some dependencies disappearing, and the place they forced people to upload binaries has closed down.

I made some updates in this branch(https://github.com/pygame/pygame/tree/conan2021103), but I won't be continuing with conan.

Closing. I don't see conan being useful in the near to mid term for pygame.
