### ISSUE TITLE
Add bgcolor attribute to freetype.Font

### ISSUE THREAD

**Issue by math2001** [pygame/pygame#998]
`freetype.Font` has `fgcolor` attribute but no `bgcolor` one. Is there any reason for this inconsistency?

**Comment by MyreMylar** [comment]
I would guess the reason is that most text is rendered with a transparent background. 

Right now there is no default background colour variable declared in the font object to set, with a bgcolor property if it did exist. If you don't set a background colour when calling `render()` on a `freetype.Font` object it just passes 0 to the relevant function and continues happily on. With the foreground colour you absolutely need it to render text, so if you don't pass a colour it goes to the default value stored on the font to grab one.

It would be a slightly more awkward code construction I suppose as you'd have to distinguish between the case where a default background colour wasn't set and where it was as well as whether one was passed in to the render function.

If I was going to add it I guess I'd add this to `src_c/freetype.h`:

    typedef struct {
        PyObject_HEAD
        pgFontId id;
        PyObject *path;
        int is_scalable;
        int is_bg_col_set;  // Add this to check if bgcolor has been set by user 
    
        Scale_t face_size;
        FT_Int16 style;
        FT_Int16 render_flags;
        double strength;
        double underline_adjustment;
        FT_UInt resolution;
        Angle_t rotation;
        FT_Matrix transform;
        FT_Byte fgcolor[4];
        FT_Byte bgcolor[4];  // Add this to store the default bg color

    
        struct freetypeinstance_ *freetype;  /* Personal reference */
        struct fontinternals_ *_internals;
    } pgFontObject; 

And then something like this for the render function in `src_c/_freetype.c`:

        if (bg_color_obj) {
            if (!pg_RGBAFromColorObj(bg_color_obj, (Uint8 *)&bg_color)) {
                PyErr_SetString(PyExc_TypeError, "bgcolor must be a Color");
                goto error;
            }
        }
        else{
            if (self->is_bg_col_set){
                bg_color_obj = 1; // Using this as a boolean flag now
                bg_color.r = self->bgcolor[0];
                bg_color.g = self->bgcolor[1];
                bg_color.b = self->bgcolor[2];
                bg_color.a = self->bgcolor[3];
            }
            else{
               bg_color_obj = 0;
            }
        }

And the getter and setters for the property:

    static PyObject *
    _ftfont_getbgcolor(pgFontObject *self, void *closure)
    {
        return pgColor_New(self->bgcolor);
    }

    static int
    _ftfont_setbgcolor(pgFontObject *self, PyObject *value, void *closure)
    {
        if (!pg_RGBAFromObj(value, self->bgcolor)) {
            PyErr_Format(PyExc_AttributeError,
                         "unable to convert %128s object to a color",
                         Py_TYPE(value)->tp_name);
            return -1;
        }
        else{
            self->is_bg_col_set = 1;
        }
        return 0;
    }

And so on...

**Comment by MyreMylar** [comment]
I feel like I talked myself into adding this halfway through the above comment, so I may as well.

**Comment by MyreMylar** [comment]
This is merged to master and should be in the next release.
